catalogMode: prefer
shellEmulator: true
trustPolicy: no-downgrade

packages:
  - apps/**
  - '!**/dist/**'
overrides:
  array-flatten: npm:@nolyfill/array-flatten@^1.0.44
  axios: npm:feaxios@^0.0.23
  is-core-module: npm:@nolyfill/is-core-module@^1.0.39
  isarray: npm:@nolyfill/isarray@^1.0.44
  safe-buffer: npm:@nolyfill/safe-buffer@^1.0.44
  safer-buffer: npm:@nolyfill/safer-buffer@^1.0.44
  side-channel: npm:@nolyfill/side-channel@^1.0.44
  string.prototype.matchall: npm:@nolyfill/string.prototype.matchall@^1.0.44
catalog:
  '@antfu/eslint-config': ^8.2.0
  '@moeru/eslint-config': 0.1.0-beta.19
  '@moeru/std': 0.1.0-beta.17
  '@proj-airi/ui': ^0.11.3
  '@types/node': ^24.12.2
  '@types/splitpanes': ^2.2.6
  '@unocss/eslint-config': ^66.6.8
  '@unocss/eslint-plugin': ^66.6.8
  '@unocss/preset-mini': ^66.6.8
  '@unocss/preset-web-fonts': ^66.6.8
  '@unocss/reset': ^66.6.8
  '@vitejs/plugin-vue': ^6.0.6
  '@vue-macros/volar': ^3.1.2
  eslint: ^9.39.1
  eslint-plugin-oxlint: ^1.73.0
  oxlint: ^1.74.0
  splitpanes: ^4.1.2
  typescript: ^5.9.3
  unocss: ^66.6.8
  unplugin-vue-router: ^0.19.2
  vite: ^8.0.10
  vue: ^3.5.32
  vue-macros: ^3.1.4
  vue-router: ^4.6.3
  vue-tsc: ^3.2.0
