// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: recorder-minecraft/catalog/v1/plays.proto
// Protobuf Java Version: 4.33.2

package dev.recorderminecraft.catalog.v1;

/**
 * Protobuf type {@code recorder_minecraft.catalog.v1.FinalInventoryItem}
 */
@com.google.protobuf.Generated
public final class FinalInventoryItem extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:recorder_minecraft.catalog.v1.FinalInventoryItem)
    FinalInventoryItemOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "FinalInventoryItem");
  }
  // Use FinalInventoryItem.newBuilder() to construct.
  private FinalInventoryItem(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private FinalInventoryItem() {
    itemId_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return dev.recorderminecraft.catalog.v1.Plays.internal_static_recorder_minecraft_catalog_v1_FinalInventoryItem_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return dev.recorderminecraft.catalog.v1.Plays.internal_static_recorder_minecraft_catalog_v1_FinalInventoryItem_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            dev.recorderminecraft.catalog.v1.FinalInventoryItem.class, dev.recorderminecraft.catalog.v1.FinalInventoryItem.Builder.class);
  }

  public static final int SLOT_FIELD_NUMBER = 1;
  private int slot_ = 0;
  /**
   * <pre>
   * Player inventory slot number.
   * </pre>
   *
   * <code>int32 slot = 1 [json_name = "slot"];</code>
   * @return The slot.
   */
  @java.lang.Override
  public int getSlot() {
    return slot_;
  }

  public static final int ITEM_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object itemId_ = "";
  /**
   * <pre>
   * Namespaced Minecraft item identifier.
   * </pre>
   *
   * <code>string item_id = 2 [json_name = "itemId"];</code>
   * @return The itemId.
   */
  @java.lang.Override
  public java.lang.String getItemId() {
    java.lang.Object ref = itemId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      itemId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Namespaced Minecraft item identifier.
   * </pre>
   *
   * <code>string item_id = 2 [json_name = "itemId"];</code>
   * @return The bytes for itemId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getItemIdBytes() {
    java.lang.Object ref = itemId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      itemId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COUNT_FIELD_NUMBER = 3;
  private int count_ = 0;
  /**
   * <code>int32 count = 3 [json_name = "count"];</code>
   * @return The count.
   */
  @java.lang.Override
  public int getCount() {
    return count_;
  }

  public static final int DAMAGE_FIELD_NUMBER = 4;
  private int damage_ = 0;
  /**
   * <code>int32 damage = 4 [json_name = "damage"];</code>
   * @return The damage.
   */
  @java.lang.Override
  public int getDamage() {
    return damage_;
  }

  public static final int MAX_DAMAGE_FIELD_NUMBER = 5;
  private int maxDamage_ = 0;
  /**
   * <code>int32 max_damage = 5 [json_name = "maxDamage"];</code>
   * @return The maxDamage.
   */
  @java.lang.Override
  public int getMaxDamage() {
    return maxDamage_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (slot_ != 0) {
      output.writeInt32(1, slot_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(itemId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, itemId_);
    }
    if (count_ != 0) {
      output.writeInt32(3, count_);
    }
    if (damage_ != 0) {
      output.writeInt32(4, damage_);
    }
    if (maxDamage_ != 0) {
      output.writeInt32(5, maxDamage_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (slot_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, slot_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(itemId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, itemId_);
    }
    if (count_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, count_);
    }
    if (damage_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, damage_);
    }
    if (maxDamage_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, maxDamage_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof dev.recorderminecraft.catalog.v1.FinalInventoryItem)) {
      return super.equals(obj);
    }
    dev.recorderminecraft.catalog.v1.FinalInventoryItem other = (dev.recorderminecraft.catalog.v1.FinalInventoryItem) obj;

    if (getSlot()
        != other.getSlot()) return false;
    if (!getItemId()
        .equals(other.getItemId())) return false;
    if (getCount()
        != other.getCount()) return false;
    if (getDamage()
        != other.getDamage()) return false;
    if (getMaxDamage()
        != other.getMaxDamage()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SLOT_FIELD_NUMBER;
    hash = (53 * hash) + getSlot();
    hash = (37 * hash) + ITEM_ID_FIELD_NUMBER;
    hash = (53 * hash) + getItemId().hashCode();
    hash = (37 * hash) + COUNT_FIELD_NUMBER;
    hash = (53 * hash) + getCount();
    hash = (37 * hash) + DAMAGE_FIELD_NUMBER;
    hash = (53 * hash) + getDamage();
    hash = (37 * hash) + MAX_DAMAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMaxDamage();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static dev.recorderminecraft.catalog.v1.FinalInventoryItem parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.recorderminecraft.catalog.v1.FinalInventoryItem parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.recorderminecraft.catalog.v1.FinalInventoryItem parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.recorderminecraft.catalog.v1.FinalInventoryItem parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.recorderminecraft.catalog.v1.FinalInventoryItem parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.recorderminecraft.catalog.v1.FinalInventoryItem parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.recorderminecraft.catalog.v1.FinalInventoryItem parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static dev.recorderminecraft.catalog.v1.FinalInventoryItem parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static dev.recorderminecraft.catalog.v1.FinalInventoryItem parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static dev.recorderminecraft.catalog.v1.FinalInventoryItem parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static dev.recorderminecraft.catalog.v1.FinalInventoryItem parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static dev.recorderminecraft.catalog.v1.FinalInventoryItem parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(dev.recorderminecraft.catalog.v1.FinalInventoryItem prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code recorder_minecraft.catalog.v1.FinalInventoryItem}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:recorder_minecraft.catalog.v1.FinalInventoryItem)
      dev.recorderminecraft.catalog.v1.FinalInventoryItemOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dev.recorderminecraft.catalog.v1.Plays.internal_static_recorder_minecraft_catalog_v1_FinalInventoryItem_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dev.recorderminecraft.catalog.v1.Plays.internal_static_recorder_minecraft_catalog_v1_FinalInventoryItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dev.recorderminecraft.catalog.v1.FinalInventoryItem.class, dev.recorderminecraft.catalog.v1.FinalInventoryItem.Builder.class);
    }

    // Construct using dev.recorderminecraft.catalog.v1.FinalInventoryItem.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      slot_ = 0;
      itemId_ = "";
      count_ = 0;
      damage_ = 0;
      maxDamage_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return dev.recorderminecraft.catalog.v1.Plays.internal_static_recorder_minecraft_catalog_v1_FinalInventoryItem_descriptor;
    }

    @java.lang.Override
    public dev.recorderminecraft.catalog.v1.FinalInventoryItem getDefaultInstanceForType() {
      return dev.recorderminecraft.catalog.v1.FinalInventoryItem.getDefaultInstance();
    }

    @java.lang.Override
    public dev.recorderminecraft.catalog.v1.FinalInventoryItem build() {
      dev.recorderminecraft.catalog.v1.FinalInventoryItem result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public dev.recorderminecraft.catalog.v1.FinalInventoryItem buildPartial() {
      dev.recorderminecraft.catalog.v1.FinalInventoryItem result = new dev.recorderminecraft.catalog.v1.FinalInventoryItem(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(dev.recorderminecraft.catalog.v1.FinalInventoryItem result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.slot_ = slot_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.itemId_ = itemId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.count_ = count_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.damage_ = damage_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.maxDamage_ = maxDamage_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof dev.recorderminecraft.catalog.v1.FinalInventoryItem) {
        return mergeFrom((dev.recorderminecraft.catalog.v1.FinalInventoryItem)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(dev.recorderminecraft.catalog.v1.FinalInventoryItem other) {
      if (other == dev.recorderminecraft.catalog.v1.FinalInventoryItem.getDefaultInstance()) return this;
      if (other.getSlot() != 0) {
        setSlot(other.getSlot());
      }
      if (!other.getItemId().isEmpty()) {
        itemId_ = other.itemId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getCount() != 0) {
        setCount(other.getCount());
      }
      if (other.getDamage() != 0) {
        setDamage(other.getDamage());
      }
      if (other.getMaxDamage() != 0) {
        setMaxDamage(other.getMaxDamage());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              slot_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              itemId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              count_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              damage_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              maxDamage_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int slot_ ;
    /**
     * <pre>
     * Player inventory slot number.
     * </pre>
     *
     * <code>int32 slot = 1 [json_name = "slot"];</code>
     * @return The slot.
     */
    @java.lang.Override
    public int getSlot() {
      return slot_;
    }
    /**
     * <pre>
     * Player inventory slot number.
     * </pre>
     *
     * <code>int32 slot = 1 [json_name = "slot"];</code>
     * @param value The slot to set.
     * @return This builder for chaining.
     */
    public Builder setSlot(int value) {

      slot_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Player inventory slot number.
     * </pre>
     *
     * <code>int32 slot = 1 [json_name = "slot"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSlot() {
      bitField0_ = (bitField0_ & ~0x00000001);
      slot_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object itemId_ = "";
    /**
     * <pre>
     * Namespaced Minecraft item identifier.
     * </pre>
     *
     * <code>string item_id = 2 [json_name = "itemId"];</code>
     * @return The itemId.
     */
    public java.lang.String getItemId() {
      java.lang.Object ref = itemId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        itemId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Namespaced Minecraft item identifier.
     * </pre>
     *
     * <code>string item_id = 2 [json_name = "itemId"];</code>
     * @return The bytes for itemId.
     */
    public com.google.protobuf.ByteString
        getItemIdBytes() {
      java.lang.Object ref = itemId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        itemId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Namespaced Minecraft item identifier.
     * </pre>
     *
     * <code>string item_id = 2 [json_name = "itemId"];</code>
     * @param value The itemId to set.
     * @return This builder for chaining.
     */
    public Builder setItemId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      itemId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Namespaced Minecraft item identifier.
     * </pre>
     *
     * <code>string item_id = 2 [json_name = "itemId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearItemId() {
      itemId_ = getDefaultInstance().getItemId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Namespaced Minecraft item identifier.
     * </pre>
     *
     * <code>string item_id = 2 [json_name = "itemId"];</code>
     * @param value The bytes for itemId to set.
     * @return This builder for chaining.
     */
    public Builder setItemIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      itemId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int count_ ;
    /**
     * <code>int32 count = 3 [json_name = "count"];</code>
     * @return The count.
     */
    @java.lang.Override
    public int getCount() {
      return count_;
    }
    /**
     * <code>int32 count = 3 [json_name = "count"];</code>
     * @param value The count to set.
     * @return This builder for chaining.
     */
    public Builder setCount(int value) {

      count_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 count = 3 [json_name = "count"];</code>
     * @return This builder for chaining.
     */
    public Builder clearCount() {
      bitField0_ = (bitField0_ & ~0x00000004);
      count_ = 0;
      onChanged();
      return this;
    }

    private int damage_ ;
    /**
     * <code>int32 damage = 4 [json_name = "damage"];</code>
     * @return The damage.
     */
    @java.lang.Override
    public int getDamage() {
      return damage_;
    }
    /**
     * <code>int32 damage = 4 [json_name = "damage"];</code>
     * @param value The damage to set.
     * @return This builder for chaining.
     */
    public Builder setDamage(int value) {

      damage_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 damage = 4 [json_name = "damage"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDamage() {
      bitField0_ = (bitField0_ & ~0x00000008);
      damage_ = 0;
      onChanged();
      return this;
    }

    private int maxDamage_ ;
    /**
     * <code>int32 max_damage = 5 [json_name = "maxDamage"];</code>
     * @return The maxDamage.
     */
    @java.lang.Override
    public int getMaxDamage() {
      return maxDamage_;
    }
    /**
     * <code>int32 max_damage = 5 [json_name = "maxDamage"];</code>
     * @param value The maxDamage to set.
     * @return This builder for chaining.
     */
    public Builder setMaxDamage(int value) {

      maxDamage_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int32 max_damage = 5 [json_name = "maxDamage"];</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxDamage() {
      bitField0_ = (bitField0_ & ~0x00000010);
      maxDamage_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:recorder_minecraft.catalog.v1.FinalInventoryItem)
  }

  // @@protoc_insertion_point(class_scope:recorder_minecraft.catalog.v1.FinalInventoryItem)
  private static final dev.recorderminecraft.catalog.v1.FinalInventoryItem DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new dev.recorderminecraft.catalog.v1.FinalInventoryItem();
  }

  public static dev.recorderminecraft.catalog.v1.FinalInventoryItem getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FinalInventoryItem>
      PARSER = new com.google.protobuf.AbstractParser<FinalInventoryItem>() {
    @java.lang.Override
    public FinalInventoryItem parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<FinalInventoryItem> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FinalInventoryItem> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public dev.recorderminecraft.catalog.v1.FinalInventoryItem getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

