// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/proj-airi/mc-play-recorder/databases/minerec-scene/ent/blob"
	"github.com/proj-airi/mc-play-recorder/databases/minerec-scene/ent/entityversion"
)

// EntityVersionCreate is the builder for creating a EntityVersion entity.
type EntityVersionCreate struct {
	config
	mutation *EntityVersionMutation
	hooks    []Hook
}

// SetInstanceID sets the "instance_id" field.
func (_c *EntityVersionCreate) SetInstanceID(v string) *EntityVersionCreate {
	_c.mutation.SetInstanceID(v)
	return _c
}

// SetNetworkID sets the "network_id" field.
func (_c *EntityVersionCreate) SetNetworkID(v int64) *EntityVersionCreate {
	_c.mutation.SetNetworkID(v)
	return _c
}

// SetNillableNetworkID sets the "network_id" field if the given value is not nil.
func (_c *EntityVersionCreate) SetNillableNetworkID(v *int64) *EntityVersionCreate {
	if v != nil {
		_c.SetNetworkID(*v)
	}
	return _c
}

// SetDimension sets the "dimension" field.
func (_c *EntityVersionCreate) SetDimension(v string) *EntityVersionCreate {
	_c.mutation.SetDimension(v)
	return _c
}

// SetTypeID sets the "type_id" field.
func (_c *EntityVersionCreate) SetTypeID(v string) *EntityVersionCreate {
	_c.mutation.SetTypeID(v)
	return _c
}

// SetStartTick sets the "start_tick" field.
func (_c *EntityVersionCreate) SetStartTick(v int64) *EntityVersionCreate {
	_c.mutation.SetStartTick(v)
	return _c
}

// SetEndTick sets the "end_tick" field.
func (_c *EntityVersionCreate) SetEndTick(v int64) *EntityVersionCreate {
	_c.mutation.SetEndTick(v)
	return _c
}

// SetMinX sets the "min_x" field.
func (_c *EntityVersionCreate) SetMinX(v float64) *EntityVersionCreate {
	_c.mutation.SetMinX(v)
	return _c
}

// SetMinY sets the "min_y" field.
func (_c *EntityVersionCreate) SetMinY(v float64) *EntityVersionCreate {
	_c.mutation.SetMinY(v)
	return _c
}

// SetMinZ sets the "min_z" field.
func (_c *EntityVersionCreate) SetMinZ(v float64) *EntityVersionCreate {
	_c.mutation.SetMinZ(v)
	return _c
}

// SetMaxX sets the "max_x" field.
func (_c *EntityVersionCreate) SetMaxX(v float64) *EntityVersionCreate {
	_c.mutation.SetMaxX(v)
	return _c
}

// SetMaxY sets the "max_y" field.
func (_c *EntityVersionCreate) SetMaxY(v float64) *EntityVersionCreate {
	_c.mutation.SetMaxY(v)
	return _c
}

// SetMaxZ sets the "max_z" field.
func (_c *EntityVersionCreate) SetMaxZ(v float64) *EntityVersionCreate {
	_c.mutation.SetMaxZ(v)
	return _c
}

// SetBlobSha256 sets the "blob_sha256" field.
func (_c *EntityVersionCreate) SetBlobSha256(v string) *EntityVersionCreate {
	_c.mutation.SetBlobSha256(v)
	return _c
}

// SetID sets the "id" field.
func (_c *EntityVersionCreate) SetID(v int64) *EntityVersionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetBlobID sets the "blob" edge to the Blob entity by ID.
func (_c *EntityVersionCreate) SetBlobID(id string) *EntityVersionCreate {
	_c.mutation.SetBlobID(id)
	return _c
}

// SetBlob sets the "blob" edge to the Blob entity.
func (_c *EntityVersionCreate) SetBlob(v *Blob) *EntityVersionCreate {
	return _c.SetBlobID(v.ID)
}

// Mutation returns the EntityVersionMutation object of the builder.
func (_c *EntityVersionCreate) Mutation() *EntityVersionMutation {
	return _c.mutation
}

// Save creates the EntityVersion in the database.
func (_c *EntityVersionCreate) Save(ctx context.Context) (*EntityVersion, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EntityVersionCreate) SaveX(ctx context.Context) *EntityVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EntityVersionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EntityVersionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EntityVersionCreate) check() error {
	if _, ok := _c.mutation.InstanceID(); !ok {
		return &ValidationError{Name: "instance_id", err: errors.New(`ent: missing required field "EntityVersion.instance_id"`)}
	}
	if _, ok := _c.mutation.Dimension(); !ok {
		return &ValidationError{Name: "dimension", err: errors.New(`ent: missing required field "EntityVersion.dimension"`)}
	}
	if _, ok := _c.mutation.TypeID(); !ok {
		return &ValidationError{Name: "type_id", err: errors.New(`ent: missing required field "EntityVersion.type_id"`)}
	}
	if _, ok := _c.mutation.StartTick(); !ok {
		return &ValidationError{Name: "start_tick", err: errors.New(`ent: missing required field "EntityVersion.start_tick"`)}
	}
	if _, ok := _c.mutation.EndTick(); !ok {
		return &ValidationError{Name: "end_tick", err: errors.New(`ent: missing required field "EntityVersion.end_tick"`)}
	}
	if _, ok := _c.mutation.MinX(); !ok {
		return &ValidationError{Name: "min_x", err: errors.New(`ent: missing required field "EntityVersion.min_x"`)}
	}
	if _, ok := _c.mutation.MinY(); !ok {
		return &ValidationError{Name: "min_y", err: errors.New(`ent: missing required field "EntityVersion.min_y"`)}
	}
	if _, ok := _c.mutation.MinZ(); !ok {
		return &ValidationError{Name: "min_z", err: errors.New(`ent: missing required field "EntityVersion.min_z"`)}
	}
	if _, ok := _c.mutation.MaxX(); !ok {
		return &ValidationError{Name: "max_x", err: errors.New(`ent: missing required field "EntityVersion.max_x"`)}
	}
	if _, ok := _c.mutation.MaxY(); !ok {
		return &ValidationError{Name: "max_y", err: errors.New(`ent: missing required field "EntityVersion.max_y"`)}
	}
	if _, ok := _c.mutation.MaxZ(); !ok {
		return &ValidationError{Name: "max_z", err: errors.New(`ent: missing required field "EntityVersion.max_z"`)}
	}
	if _, ok := _c.mutation.BlobSha256(); !ok {
		return &ValidationError{Name: "blob_sha256", err: errors.New(`ent: missing required field "EntityVersion.blob_sha256"`)}
	}
	if v, ok := _c.mutation.BlobSha256(); ok {
		if err := entityversion.BlobSha256Validator(v); err != nil {
			return &ValidationError{Name: "blob_sha256", err: fmt.Errorf(`ent: validator failed for field "EntityVersion.blob_sha256": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := entityversion.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "EntityVersion.id": %w`, err)}
		}
	}
	if len(_c.mutation.BlobIDs()) == 0 {
		return &ValidationError{Name: "blob", err: errors.New(`ent: missing required edge "EntityVersion.blob"`)}
	}
	return nil
}

func (_c *EntityVersionCreate) sqlSave(ctx context.Context) (*EntityVersion, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EntityVersionCreate) createSpec() (*EntityVersion, *sqlgraph.CreateSpec) {
	var (
		_node = &EntityVersion{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(entityversion.Table, sqlgraph.NewFieldSpec(entityversion.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.InstanceID(); ok {
		_spec.SetField(entityversion.FieldInstanceID, field.TypeString, value)
		_node.InstanceID = value
	}
	if value, ok := _c.mutation.NetworkID(); ok {
		_spec.SetField(entityversion.FieldNetworkID, field.TypeInt64, value)
		_node.NetworkID = &value
	}
	if value, ok := _c.mutation.Dimension(); ok {
		_spec.SetField(entityversion.FieldDimension, field.TypeString, value)
		_node.Dimension = value
	}
	if value, ok := _c.mutation.TypeID(); ok {
		_spec.SetField(entityversion.FieldTypeID, field.TypeString, value)
		_node.TypeID = value
	}
	if value, ok := _c.mutation.StartTick(); ok {
		_spec.SetField(entityversion.FieldStartTick, field.TypeInt64, value)
		_node.StartTick = value
	}
	if value, ok := _c.mutation.EndTick(); ok {
		_spec.SetField(entityversion.FieldEndTick, field.TypeInt64, value)
		_node.EndTick = value
	}
	if value, ok := _c.mutation.MinX(); ok {
		_spec.SetField(entityversion.FieldMinX, field.TypeFloat64, value)
		_node.MinX = value
	}
	if value, ok := _c.mutation.MinY(); ok {
		_spec.SetField(entityversion.FieldMinY, field.TypeFloat64, value)
		_node.MinY = value
	}
	if value, ok := _c.mutation.MinZ(); ok {
		_spec.SetField(entityversion.FieldMinZ, field.TypeFloat64, value)
		_node.MinZ = value
	}
	if value, ok := _c.mutation.MaxX(); ok {
		_spec.SetField(entityversion.FieldMaxX, field.TypeFloat64, value)
		_node.MaxX = value
	}
	if value, ok := _c.mutation.MaxY(); ok {
		_spec.SetField(entityversion.FieldMaxY, field.TypeFloat64, value)
		_node.MaxY = value
	}
	if value, ok := _c.mutation.MaxZ(); ok {
		_spec.SetField(entityversion.FieldMaxZ, field.TypeFloat64, value)
		_node.MaxZ = value
	}
	if nodes := _c.mutation.BlobIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   entityversion.BlobTable,
			Columns: []string{entityversion.BlobColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(blob.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.BlobSha256 = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// EntityVersionCreateBulk is the builder for creating many EntityVersion entities in bulk.
type EntityVersionCreateBulk struct {
	config
	err      error
	builders []*EntityVersionCreate
}

// Save creates the EntityVersion entities in the database.
func (_c *EntityVersionCreateBulk) Save(ctx context.Context) ([]*EntityVersion, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*EntityVersion, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EntityVersionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EntityVersionCreateBulk) SaveX(ctx context.Context) []*EntityVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EntityVersionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EntityVersionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
