// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: recorder-minecraft/catalog/v1/plays.proto

package catalogv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PlaySummary is a transient read-only projection of completed Play inputs.
type PlaySummary struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Inclusive Server tick count from the metadata start tick through the end tick.
	DurationTicks uint64 `protobuf:"varint,1,opt,name=duration_ticks,json=durationTicks,proto3" json:"duration_ticks,omitempty"`
	// Sum in blocks of three-dimensional displacement between successive same-dimension Player states.
	ObservedPathDistanceBlocks float64 `protobuf:"fixed64,2,opt,name=observed_path_distance_blocks,json=observedPathDistanceBlocks,proto3" json:"observed_path_distance_blocks,omitempty"`
	// Percentage from 0 through 100 of duration ticks without recorded player activity.
	IdlePercentage float64 `protobuf:"fixed64,3,opt,name=idle_percentage,json=idlePercentage,proto3" json:"idle_percentage,omitempty"`
	// Number of Player state snapshots used by this summary.
	PlayerStateCount uint64 `protobuf:"varint,4,opt,name=player_state_count,json=playerStateCount,proto3" json:"player_state_count,omitempty"`
	// Slot-preserving inventory from the final Player state.
	FinalInventory []*FinalInventoryItem `protobuf:"bytes,5,rep,name=final_inventory,json=finalInventory,proto3" json:"final_inventory,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PlaySummary) Reset() {
	*x = PlaySummary{}
	mi := &file_recorder_minecraft_catalog_v1_plays_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaySummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaySummary) ProtoMessage() {}

func (x *PlaySummary) ProtoReflect() protoreflect.Message {
	mi := &file_recorder_minecraft_catalog_v1_plays_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaySummary.ProtoReflect.Descriptor instead.
func (*PlaySummary) Descriptor() ([]byte, []int) {
	return file_recorder_minecraft_catalog_v1_plays_proto_rawDescGZIP(), []int{0}
}

func (x *PlaySummary) GetDurationTicks() uint64 {
	if x != nil {
		return x.DurationTicks
	}
	return 0
}

func (x *PlaySummary) GetObservedPathDistanceBlocks() float64 {
	if x != nil {
		return x.ObservedPathDistanceBlocks
	}
	return 0
}

func (x *PlaySummary) GetIdlePercentage() float64 {
	if x != nil {
		return x.IdlePercentage
	}
	return 0
}

func (x *PlaySummary) GetPlayerStateCount() uint64 {
	if x != nil {
		return x.PlayerStateCount
	}
	return 0
}

func (x *PlaySummary) GetFinalInventory() []*FinalInventoryItem {
	if x != nil {
		return x.FinalInventory
	}
	return nil
}

type FinalInventoryItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Player inventory slot number.
	Slot int32 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	// Namespaced Minecraft item identifier.
	ItemId        string `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Count         int32  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Damage        int32  `protobuf:"varint,4,opt,name=damage,proto3" json:"damage,omitempty"`
	MaxDamage     int32  `protobuf:"varint,5,opt,name=max_damage,json=maxDamage,proto3" json:"max_damage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalInventoryItem) Reset() {
	*x = FinalInventoryItem{}
	mi := &file_recorder_minecraft_catalog_v1_plays_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalInventoryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalInventoryItem) ProtoMessage() {}

func (x *FinalInventoryItem) ProtoReflect() protoreflect.Message {
	mi := &file_recorder_minecraft_catalog_v1_plays_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalInventoryItem.ProtoReflect.Descriptor instead.
func (*FinalInventoryItem) Descriptor() ([]byte, []int) {
	return file_recorder_minecraft_catalog_v1_plays_proto_rawDescGZIP(), []int{1}
}

func (x *FinalInventoryItem) GetSlot() int32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *FinalInventoryItem) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *FinalInventoryItem) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *FinalInventoryItem) GetDamage() int32 {
	if x != nil {
		return x.Damage
	}
	return 0
}

func (x *FinalInventoryItem) GetMaxDamage() int32 {
	if x != nil {
		return x.MaxDamage
	}
	return 0
}

var File_recorder_minecraft_catalog_v1_plays_proto protoreflect.FileDescriptor

const file_recorder_minecraft_catalog_v1_plays_proto_rawDesc = "" +
	"\n" +
	")recorder-minecraft/catalog/v1/plays.proto\x12\x1drecorder_minecraft.catalog.v1\"\xaa\x02\n" +
	"\vPlaySummary\x12%\n" +
	"\x0eduration_ticks\x18\x01 \x01(\x04R\rdurationTicks\x12A\n" +
	"\x1dobserved_path_distance_blocks\x18\x02 \x01(\x01R\x1aobservedPathDistanceBlocks\x12'\n" +
	"\x0fidle_percentage\x18\x03 \x01(\x01R\x0eidlePercentage\x12,\n" +
	"\x12player_state_count\x18\x04 \x01(\x04R\x10playerStateCount\x12Z\n" +
	"\x0ffinal_inventory\x18\x05 \x03(\v21.recorder_minecraft.catalog.v1.FinalInventoryItemR\x0efinalInventory\"\x8e\x01\n" +
	"\x12FinalInventoryItem\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x05R\x04slot\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\tR\x06itemId\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\x12\x16\n" +
	"\x06damage\x18\x04 \x01(\x05R\x06damage\x12\x1d\n" +
	"\n" +
	"max_damage\x18\x05 \x01(\x05R\tmaxDamageB\x81\x01\n" +
	" dev.recorderminecraft.catalog.v1P\x01Z[github.com/proj-airi/recorder-minecraft/apis/sdk/go/recorder-minecraft/catalog/v1;catalogv1b\x06proto3"

var (
	file_recorder_minecraft_catalog_v1_plays_proto_rawDescOnce sync.Once
	file_recorder_minecraft_catalog_v1_plays_proto_rawDescData []byte
)

func file_recorder_minecraft_catalog_v1_plays_proto_rawDescGZIP() []byte {
	file_recorder_minecraft_catalog_v1_plays_proto_rawDescOnce.Do(func() {
		file_recorder_minecraft_catalog_v1_plays_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_recorder_minecraft_catalog_v1_plays_proto_rawDesc), len(file_recorder_minecraft_catalog_v1_plays_proto_rawDesc)))
	})
	return file_recorder_minecraft_catalog_v1_plays_proto_rawDescData
}

var file_recorder_minecraft_catalog_v1_plays_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_recorder_minecraft_catalog_v1_plays_proto_goTypes = []any{
	(*PlaySummary)(nil),        // 0: recorder_minecraft.catalog.v1.PlaySummary
	(*FinalInventoryItem)(nil), // 1: recorder_minecraft.catalog.v1.FinalInventoryItem
}
var file_recorder_minecraft_catalog_v1_plays_proto_depIdxs = []int32{
	1, // 0: recorder_minecraft.catalog.v1.PlaySummary.final_inventory:type_name -> recorder_minecraft.catalog.v1.FinalInventoryItem
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_recorder_minecraft_catalog_v1_plays_proto_init() }
func file_recorder_minecraft_catalog_v1_plays_proto_init() {
	if File_recorder_minecraft_catalog_v1_plays_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_recorder_minecraft_catalog_v1_plays_proto_rawDesc), len(file_recorder_minecraft_catalog_v1_plays_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_recorder_minecraft_catalog_v1_plays_proto_goTypes,
		DependencyIndexes: file_recorder_minecraft_catalog_v1_plays_proto_depIdxs,
		MessageInfos:      file_recorder_minecraft_catalog_v1_plays_proto_msgTypes,
	}.Build()
	File_recorder_minecraft_catalog_v1_plays_proto = out.File
	file_recorder_minecraft_catalog_v1_plays_proto_goTypes = nil
	file_recorder_minecraft_catalog_v1_plays_proto_depIdxs = nil
}
