// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mc-play-recorder/artifacts/v1/scene_extraction.proto
// Protobuf Java Version: 4.33.2

package dev.minerec.artifacts.v1;

/**
 * Protobuf type {@code mc_play_recorder.artifacts.v1.BlockEntityBlob}
 */
@com.google.protobuf.Generated
public final class BlockEntityBlob extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:mc_play_recorder.artifacts.v1.BlockEntityBlob)
    BlockEntityBlobOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "BlockEntityBlob");
  }
  // Use BlockEntityBlob.newBuilder() to construct.
  private BlockEntityBlob(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private BlockEntityBlob() {
    dimension_ = "";
    typeId_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return dev.minerec.artifacts.v1.SceneExtraction.internal_static_mc_play_recorder_artifacts_v1_BlockEntityBlob_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return dev.minerec.artifacts.v1.SceneExtraction.internal_static_mc_play_recorder_artifacts_v1_BlockEntityBlob_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            dev.minerec.artifacts.v1.BlockEntityBlob.class, dev.minerec.artifacts.v1.BlockEntityBlob.Builder.class);
  }

  private int bitField0_;
  public static final int DIMENSION_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object dimension_ = "";
  /**
   * <code>string dimension = 1 [json_name = "dimension"];</code>
   * @return The dimension.
   */
  @java.lang.Override
  public java.lang.String getDimension() {
    java.lang.Object ref = dimension_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dimension_ = s;
      return s;
    }
  }
  /**
   * <code>string dimension = 1 [json_name = "dimension"];</code>
   * @return The bytes for dimension.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDimensionBytes() {
    java.lang.Object ref = dimension_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dimension_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int X_FIELD_NUMBER = 2;
  private int x_ = 0;
  /**
   * <code>int32 x = 2 [json_name = "x"];</code>
   * @return The x.
   */
  @java.lang.Override
  public int getX() {
    return x_;
  }

  public static final int Y_FIELD_NUMBER = 3;
  private int y_ = 0;
  /**
   * <code>int32 y = 3 [json_name = "y"];</code>
   * @return The y.
   */
  @java.lang.Override
  public int getY() {
    return y_;
  }

  public static final int Z_FIELD_NUMBER = 4;
  private int z_ = 0;
  /**
   * <code>int32 z = 4 [json_name = "z"];</code>
   * @return The z.
   */
  @java.lang.Override
  public int getZ() {
    return z_;
  }

  public static final int TYPE_ID_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object typeId_ = "";
  /**
   * <code>string type_id = 5 [json_name = "typeId"];</code>
   * @return The typeId.
   */
  @java.lang.Override
  public java.lang.String getTypeId() {
    java.lang.Object ref = typeId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      typeId_ = s;
      return s;
    }
  }
  /**
   * <code>string type_id = 5 [json_name = "typeId"];</code>
   * @return The bytes for typeId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTypeIdBytes() {
    java.lang.Object ref = typeId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      typeId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NBT_FIELD_NUMBER = 6;
  private dev.minerec.artifacts.v1.EncodedValue nbt_;
  /**
   * <code>.mc_play_recorder.artifacts.v1.EncodedValue nbt = 6 [json_name = "nbt"];</code>
   * @return Whether the nbt field is set.
   */
  @java.lang.Override
  public boolean hasNbt() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.mc_play_recorder.artifacts.v1.EncodedValue nbt = 6 [json_name = "nbt"];</code>
   * @return The nbt.
   */
  @java.lang.Override
  public dev.minerec.artifacts.v1.EncodedValue getNbt() {
    return nbt_ == null ? dev.minerec.artifacts.v1.EncodedValue.getDefaultInstance() : nbt_;
  }
  /**
   * <code>.mc_play_recorder.artifacts.v1.EncodedValue nbt = 6 [json_name = "nbt"];</code>
   */
  @java.lang.Override
  public dev.minerec.artifacts.v1.EncodedValueOrBuilder getNbtOrBuilder() {
    return nbt_ == null ? dev.minerec.artifacts.v1.EncodedValue.getDefaultInstance() : nbt_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(dimension_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, dimension_);
    }
    if (x_ != 0) {
      output.writeInt32(2, x_);
    }
    if (y_ != 0) {
      output.writeInt32(3, y_);
    }
    if (z_ != 0) {
      output.writeInt32(4, z_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(typeId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, typeId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(6, getNbt());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(dimension_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, dimension_);
    }
    if (x_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, x_);
    }
    if (y_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, y_);
    }
    if (z_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, z_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(typeId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, typeId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getNbt());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof dev.minerec.artifacts.v1.BlockEntityBlob)) {
      return super.equals(obj);
    }
    dev.minerec.artifacts.v1.BlockEntityBlob other = (dev.minerec.artifacts.v1.BlockEntityBlob) obj;

    if (!getDimension()
        .equals(other.getDimension())) return false;
    if (getX()
        != other.getX()) return false;
    if (getY()
        != other.getY()) return false;
    if (getZ()
        != other.getZ()) return false;
    if (!getTypeId()
        .equals(other.getTypeId())) return false;
    if (hasNbt() != other.hasNbt()) return false;
    if (hasNbt()) {
      if (!getNbt()
          .equals(other.getNbt())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DIMENSION_FIELD_NUMBER;
    hash = (53 * hash) + getDimension().hashCode();
    hash = (37 * hash) + X_FIELD_NUMBER;
    hash = (53 * hash) + getX();
    hash = (37 * hash) + Y_FIELD_NUMBER;
    hash = (53 * hash) + getY();
    hash = (37 * hash) + Z_FIELD_NUMBER;
    hash = (53 * hash) + getZ();
    hash = (37 * hash) + TYPE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTypeId().hashCode();
    if (hasNbt()) {
      hash = (37 * hash) + NBT_FIELD_NUMBER;
      hash = (53 * hash) + getNbt().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static dev.minerec.artifacts.v1.BlockEntityBlob parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.minerec.artifacts.v1.BlockEntityBlob parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.minerec.artifacts.v1.BlockEntityBlob parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.minerec.artifacts.v1.BlockEntityBlob parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.minerec.artifacts.v1.BlockEntityBlob parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.minerec.artifacts.v1.BlockEntityBlob parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.minerec.artifacts.v1.BlockEntityBlob parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static dev.minerec.artifacts.v1.BlockEntityBlob parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static dev.minerec.artifacts.v1.BlockEntityBlob parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static dev.minerec.artifacts.v1.BlockEntityBlob parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static dev.minerec.artifacts.v1.BlockEntityBlob parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static dev.minerec.artifacts.v1.BlockEntityBlob parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(dev.minerec.artifacts.v1.BlockEntityBlob prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code mc_play_recorder.artifacts.v1.BlockEntityBlob}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mc_play_recorder.artifacts.v1.BlockEntityBlob)
      dev.minerec.artifacts.v1.BlockEntityBlobOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dev.minerec.artifacts.v1.SceneExtraction.internal_static_mc_play_recorder_artifacts_v1_BlockEntityBlob_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dev.minerec.artifacts.v1.SceneExtraction.internal_static_mc_play_recorder_artifacts_v1_BlockEntityBlob_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dev.minerec.artifacts.v1.BlockEntityBlob.class, dev.minerec.artifacts.v1.BlockEntityBlob.Builder.class);
    }

    // Construct using dev.minerec.artifacts.v1.BlockEntityBlob.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetNbtFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      dimension_ = "";
      x_ = 0;
      y_ = 0;
      z_ = 0;
      typeId_ = "";
      nbt_ = null;
      if (nbtBuilder_ != null) {
        nbtBuilder_.dispose();
        nbtBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return dev.minerec.artifacts.v1.SceneExtraction.internal_static_mc_play_recorder_artifacts_v1_BlockEntityBlob_descriptor;
    }

    @java.lang.Override
    public dev.minerec.artifacts.v1.BlockEntityBlob getDefaultInstanceForType() {
      return dev.minerec.artifacts.v1.BlockEntityBlob.getDefaultInstance();
    }

    @java.lang.Override
    public dev.minerec.artifacts.v1.BlockEntityBlob build() {
      dev.minerec.artifacts.v1.BlockEntityBlob result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public dev.minerec.artifacts.v1.BlockEntityBlob buildPartial() {
      dev.minerec.artifacts.v1.BlockEntityBlob result = new dev.minerec.artifacts.v1.BlockEntityBlob(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(dev.minerec.artifacts.v1.BlockEntityBlob result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.dimension_ = dimension_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.x_ = x_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.y_ = y_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.z_ = z_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.typeId_ = typeId_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.nbt_ = nbtBuilder_ == null
            ? nbt_
            : nbtBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof dev.minerec.artifacts.v1.BlockEntityBlob) {
        return mergeFrom((dev.minerec.artifacts.v1.BlockEntityBlob)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(dev.minerec.artifacts.v1.BlockEntityBlob other) {
      if (other == dev.minerec.artifacts.v1.BlockEntityBlob.getDefaultInstance()) return this;
      if (!other.getDimension().isEmpty()) {
        dimension_ = other.dimension_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getX() != 0) {
        setX(other.getX());
      }
      if (other.getY() != 0) {
        setY(other.getY());
      }
      if (other.getZ() != 0) {
        setZ(other.getZ());
      }
      if (!other.getTypeId().isEmpty()) {
        typeId_ = other.typeId_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.hasNbt()) {
        mergeNbt(other.getNbt());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              dimension_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              x_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              y_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              z_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              typeId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  internalGetNbtFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object dimension_ = "";
    /**
     * <code>string dimension = 1 [json_name = "dimension"];</code>
     * @return The dimension.
     */
    public java.lang.String getDimension() {
      java.lang.Object ref = dimension_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dimension_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string dimension = 1 [json_name = "dimension"];</code>
     * @return The bytes for dimension.
     */
    public com.google.protobuf.ByteString
        getDimensionBytes() {
      java.lang.Object ref = dimension_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dimension_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string dimension = 1 [json_name = "dimension"];</code>
     * @param value The dimension to set.
     * @return This builder for chaining.
     */
    public Builder setDimension(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      dimension_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string dimension = 1 [json_name = "dimension"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDimension() {
      dimension_ = getDefaultInstance().getDimension();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string dimension = 1 [json_name = "dimension"];</code>
     * @param value The bytes for dimension to set.
     * @return This builder for chaining.
     */
    public Builder setDimensionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      dimension_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int x_ ;
    /**
     * <code>int32 x = 2 [json_name = "x"];</code>
     * @return The x.
     */
    @java.lang.Override
    public int getX() {
      return x_;
    }
    /**
     * <code>int32 x = 2 [json_name = "x"];</code>
     * @param value The x to set.
     * @return This builder for chaining.
     */
    public Builder setX(int value) {

      x_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 x = 2 [json_name = "x"];</code>
     * @return This builder for chaining.
     */
    public Builder clearX() {
      bitField0_ = (bitField0_ & ~0x00000002);
      x_ = 0;
      onChanged();
      return this;
    }

    private int y_ ;
    /**
     * <code>int32 y = 3 [json_name = "y"];</code>
     * @return The y.
     */
    @java.lang.Override
    public int getY() {
      return y_;
    }
    /**
     * <code>int32 y = 3 [json_name = "y"];</code>
     * @param value The y to set.
     * @return This builder for chaining.
     */
    public Builder setY(int value) {

      y_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 y = 3 [json_name = "y"];</code>
     * @return This builder for chaining.
     */
    public Builder clearY() {
      bitField0_ = (bitField0_ & ~0x00000004);
      y_ = 0;
      onChanged();
      return this;
    }

    private int z_ ;
    /**
     * <code>int32 z = 4 [json_name = "z"];</code>
     * @return The z.
     */
    @java.lang.Override
    public int getZ() {
      return z_;
    }
    /**
     * <code>int32 z = 4 [json_name = "z"];</code>
     * @param value The z to set.
     * @return This builder for chaining.
     */
    public Builder setZ(int value) {

      z_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 z = 4 [json_name = "z"];</code>
     * @return This builder for chaining.
     */
    public Builder clearZ() {
      bitField0_ = (bitField0_ & ~0x00000008);
      z_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object typeId_ = "";
    /**
     * <code>string type_id = 5 [json_name = "typeId"];</code>
     * @return The typeId.
     */
    public java.lang.String getTypeId() {
      java.lang.Object ref = typeId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        typeId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string type_id = 5 [json_name = "typeId"];</code>
     * @return The bytes for typeId.
     */
    public com.google.protobuf.ByteString
        getTypeIdBytes() {
      java.lang.Object ref = typeId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        typeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string type_id = 5 [json_name = "typeId"];</code>
     * @param value The typeId to set.
     * @return This builder for chaining.
     */
    public Builder setTypeId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      typeId_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string type_id = 5 [json_name = "typeId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTypeId() {
      typeId_ = getDefaultInstance().getTypeId();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string type_id = 5 [json_name = "typeId"];</code>
     * @param value The bytes for typeId to set.
     * @return This builder for chaining.
     */
    public Builder setTypeIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      typeId_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private dev.minerec.artifacts.v1.EncodedValue nbt_;
    private com.google.protobuf.SingleFieldBuilder<
        dev.minerec.artifacts.v1.EncodedValue, dev.minerec.artifacts.v1.EncodedValue.Builder, dev.minerec.artifacts.v1.EncodedValueOrBuilder> nbtBuilder_;
    /**
     * <code>.mc_play_recorder.artifacts.v1.EncodedValue nbt = 6 [json_name = "nbt"];</code>
     * @return Whether the nbt field is set.
     */
    public boolean hasNbt() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>.mc_play_recorder.artifacts.v1.EncodedValue nbt = 6 [json_name = "nbt"];</code>
     * @return The nbt.
     */
    public dev.minerec.artifacts.v1.EncodedValue getNbt() {
      if (nbtBuilder_ == null) {
        return nbt_ == null ? dev.minerec.artifacts.v1.EncodedValue.getDefaultInstance() : nbt_;
      } else {
        return nbtBuilder_.getMessage();
      }
    }
    /**
     * <code>.mc_play_recorder.artifacts.v1.EncodedValue nbt = 6 [json_name = "nbt"];</code>
     */
    public Builder setNbt(dev.minerec.artifacts.v1.EncodedValue value) {
      if (nbtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        nbt_ = value;
      } else {
        nbtBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.mc_play_recorder.artifacts.v1.EncodedValue nbt = 6 [json_name = "nbt"];</code>
     */
    public Builder setNbt(
        dev.minerec.artifacts.v1.EncodedValue.Builder builderForValue) {
      if (nbtBuilder_ == null) {
        nbt_ = builderForValue.build();
      } else {
        nbtBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.mc_play_recorder.artifacts.v1.EncodedValue nbt = 6 [json_name = "nbt"];</code>
     */
    public Builder mergeNbt(dev.minerec.artifacts.v1.EncodedValue value) {
      if (nbtBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          nbt_ != null &&
          nbt_ != dev.minerec.artifacts.v1.EncodedValue.getDefaultInstance()) {
          getNbtBuilder().mergeFrom(value);
        } else {
          nbt_ = value;
        }
      } else {
        nbtBuilder_.mergeFrom(value);
      }
      if (nbt_ != null) {
        bitField0_ |= 0x00000020;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.mc_play_recorder.artifacts.v1.EncodedValue nbt = 6 [json_name = "nbt"];</code>
     */
    public Builder clearNbt() {
      bitField0_ = (bitField0_ & ~0x00000020);
      nbt_ = null;
      if (nbtBuilder_ != null) {
        nbtBuilder_.dispose();
        nbtBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.mc_play_recorder.artifacts.v1.EncodedValue nbt = 6 [json_name = "nbt"];</code>
     */
    public dev.minerec.artifacts.v1.EncodedValue.Builder getNbtBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return internalGetNbtFieldBuilder().getBuilder();
    }
    /**
     * <code>.mc_play_recorder.artifacts.v1.EncodedValue nbt = 6 [json_name = "nbt"];</code>
     */
    public dev.minerec.artifacts.v1.EncodedValueOrBuilder getNbtOrBuilder() {
      if (nbtBuilder_ != null) {
        return nbtBuilder_.getMessageOrBuilder();
      } else {
        return nbt_ == null ?
            dev.minerec.artifacts.v1.EncodedValue.getDefaultInstance() : nbt_;
      }
    }
    /**
     * <code>.mc_play_recorder.artifacts.v1.EncodedValue nbt = 6 [json_name = "nbt"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        dev.minerec.artifacts.v1.EncodedValue, dev.minerec.artifacts.v1.EncodedValue.Builder, dev.minerec.artifacts.v1.EncodedValueOrBuilder> 
        internalGetNbtFieldBuilder() {
      if (nbtBuilder_ == null) {
        nbtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            dev.minerec.artifacts.v1.EncodedValue, dev.minerec.artifacts.v1.EncodedValue.Builder, dev.minerec.artifacts.v1.EncodedValueOrBuilder>(
                getNbt(),
                getParentForChildren(),
                isClean());
        nbt_ = null;
      }
      return nbtBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:mc_play_recorder.artifacts.v1.BlockEntityBlob)
  }

  // @@protoc_insertion_point(class_scope:mc_play_recorder.artifacts.v1.BlockEntityBlob)
  private static final dev.minerec.artifacts.v1.BlockEntityBlob DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new dev.minerec.artifacts.v1.BlockEntityBlob();
  }

  public static dev.minerec.artifacts.v1.BlockEntityBlob getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BlockEntityBlob>
      PARSER = new com.google.protobuf.AbstractParser<BlockEntityBlob>() {
    @java.lang.Override
    public BlockEntityBlob parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<BlockEntityBlob> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BlockEntityBlob> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public dev.minerec.artifacts.v1.BlockEntityBlob getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

