// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mc-play-recorder/artifacts/v1/scene_extraction.proto
// Protobuf Java Version: 4.33.2

package dev.minerec.artifacts.v1;

@com.google.protobuf.Generated
public interface BlockEntityBlobOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mc_play_recorder.artifacts.v1.BlockEntityBlob)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string dimension = 1 [json_name = "dimension"];</code>
   * @return The dimension.
   */
  java.lang.String getDimension();
  /**
   * <code>string dimension = 1 [json_name = "dimension"];</code>
   * @return The bytes for dimension.
   */
  com.google.protobuf.ByteString
      getDimensionBytes();

  /**
   * <code>int32 x = 2 [json_name = "x"];</code>
   * @return The x.
   */
  int getX();

  /**
   * <code>int32 y = 3 [json_name = "y"];</code>
   * @return The y.
   */
  int getY();

  /**
   * <code>int32 z = 4 [json_name = "z"];</code>
   * @return The z.
   */
  int getZ();

  /**
   * <code>string type_id = 5 [json_name = "typeId"];</code>
   * @return The typeId.
   */
  java.lang.String getTypeId();
  /**
   * <code>string type_id = 5 [json_name = "typeId"];</code>
   * @return The bytes for typeId.
   */
  com.google.protobuf.ByteString
      getTypeIdBytes();

  /**
   * <code>.mc_play_recorder.artifacts.v1.EncodedValue nbt = 6 [json_name = "nbt"];</code>
   * @return Whether the nbt field is set.
   */
  boolean hasNbt();
  /**
   * <code>.mc_play_recorder.artifacts.v1.EncodedValue nbt = 6 [json_name = "nbt"];</code>
   * @return The nbt.
   */
  dev.minerec.artifacts.v1.EncodedValue getNbt();
  /**
   * <code>.mc_play_recorder.artifacts.v1.EncodedValue nbt = 6 [json_name = "nbt"];</code>
   */
  dev.minerec.artifacts.v1.EncodedValueOrBuilder getNbtOrBuilder();
}
