// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mc-play-recorder/artifacts/v1/common.proto
// Protobuf Java Version: 4.33.2

package dev.minerec.artifacts.v1;

@com.google.protobuf.Generated
public final class Common extends com.google.protobuf.GeneratedFile {
  private Common() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "Common");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mc_play_recorder_artifacts_v1_Vector3_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mc_play_recorder_artifacts_v1_Vector3_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mc_play_recorder_artifacts_v1_Rotation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mc_play_recorder_artifacts_v1_Rotation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mc_play_recorder_artifacts_v1_TickRange_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mc_play_recorder_artifacts_v1_TickRange_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mc_play_recorder_artifacts_v1_ArtifactFile_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mc_play_recorder_artifacts_v1_ArtifactFile_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n*mc-play-recorder/artifacts/v1/common.p" +
      "roto\022\035mc_play_recorder.artifacts.v1\"3\n\007V" +
      "ector3\022\014\n\001x\030\001 \001(\001R\001x\022\014\n\001y\030\002 \001(\001R\001y\022\014\n\001z\030" +
      "\003 \001(\001R\001z\"M\n\010Rotation\022\020\n\003yaw\030\001 \001(\001R\003yaw\022\024" +
      "\n\005pitch\030\002 \001(\001R\005pitch\022\031\n\010head_yaw\030\003 \001(\001R\007" +
      "headYaw\"G\n\tTickRange\022\035\n\nfirst_tick\030\001 \001(\003" +
      "R\tfirstTick\022\033\n\tlast_tick\030\002 \001(\003R\010lastTick" +
      "\"x\n\014ArtifactFile\022\022\n\004path\030\001 \001(\tR\004path\022\026\n\006" +
      "sha256\030\002 \001(\tR\006sha256\022\035\n\nsize_bytes\030\003 \001(\004" +
      "R\tsizeBytes\022\035\n\nmedia_type\030\004 \001(\tR\tmediaTy" +
      "peBy\n\030dev.minerec.artifacts.v1P\001Z[github" +
      ".com/proj-airi/mc-play-recorder/apis/sdk" +
      "/go/mc-play-recorder/artifacts/v1;artifa" +
      "ctsv1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_mc_play_recorder_artifacts_v1_Vector3_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_mc_play_recorder_artifacts_v1_Vector3_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_mc_play_recorder_artifacts_v1_Vector3_descriptor,
        new java.lang.String[] { "X", "Y", "Z", });
    internal_static_mc_play_recorder_artifacts_v1_Rotation_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_mc_play_recorder_artifacts_v1_Rotation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_mc_play_recorder_artifacts_v1_Rotation_descriptor,
        new java.lang.String[] { "Yaw", "Pitch", "HeadYaw", });
    internal_static_mc_play_recorder_artifacts_v1_TickRange_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_mc_play_recorder_artifacts_v1_TickRange_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_mc_play_recorder_artifacts_v1_TickRange_descriptor,
        new java.lang.String[] { "FirstTick", "LastTick", });
    internal_static_mc_play_recorder_artifacts_v1_ArtifactFile_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_mc_play_recorder_artifacts_v1_ArtifactFile_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_mc_play_recorder_artifacts_v1_ArtifactFile_descriptor,
        new java.lang.String[] { "Path", "Sha256", "SizeBytes", "MediaType", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
