// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mc-play-recorder/artifacts/v1/scene_extraction.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package dev.minerec.artifacts.v1;

@kotlin.jvm.JvmName("-initializeentityMetadata")
public inline fun entityMetadata(block: dev.minerec.artifacts.v1.EntityMetadataKt.Dsl.() -> kotlin.Unit): dev.minerec.artifacts.v1.EntityMetadata =
  dev.minerec.artifacts.v1.EntityMetadataKt.Dsl._create(dev.minerec.artifacts.v1.EntityMetadata.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `mc_play_recorder.artifacts.v1.EntityMetadata`
 */
public object EntityMetadataKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: dev.minerec.artifacts.v1.EntityMetadata.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: dev.minerec.artifacts.v1.EntityMetadata.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): dev.minerec.artifacts.v1.EntityMetadata = _builder.build()

    /**
     * `int32 index = 1 [json_name = "index"];`
     */
    public var index: kotlin.Int
      @kotlin.jvm.JvmName("getIndex")
        get() = _builder.index
      @kotlin.jvm.JvmName("setIndex")
        set(value) {
        _builder.index = value
      }
    /**
     * `int32 index = 1 [json_name = "index"];`
     */
    public fun clearIndex() {
      _builder.clearIndex()
    }

    /**
     * `.mc_play_recorder.artifacts.v1.EncodedValue value = 2 [json_name = "value"];`
     */
    public var value: dev.minerec.artifacts.v1.EncodedValue
      @kotlin.jvm.JvmName("getValue")
        get() = _builder.value
      @kotlin.jvm.JvmName("setValue")
        set(value) {
        _builder.value = value
      }
    /**
     * `.mc_play_recorder.artifacts.v1.EncodedValue value = 2 [json_name = "value"];`
     */
    public fun clearValue() {
      _builder.clearValue()
    }
    /**
     * `.mc_play_recorder.artifacts.v1.EncodedValue value = 2 [json_name = "value"];`
     * @return Whether the value field is set.
     */
    public fun hasValue(): kotlin.Boolean {
      return _builder.hasValue()
    }

    public val EntityMetadataKt.Dsl.valueOrNull: dev.minerec.artifacts.v1.EncodedValue?
      get() = _builder.valueOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun dev.minerec.artifacts.v1.EntityMetadata.copy(block: `dev.minerec.artifacts.v1`.EntityMetadataKt.Dsl.() -> kotlin.Unit): dev.minerec.artifacts.v1.EntityMetadata =
  `dev.minerec.artifacts.v1`.EntityMetadataKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val dev.minerec.artifacts.v1.EntityMetadataOrBuilder.valueOrNull: dev.minerec.artifacts.v1.EncodedValue?
  get() = if (hasValue()) getValue() else null

