// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mc-play-recorder/artifacts/v1/scene_extraction.proto
// Protobuf Java Version: 4.33.2

package dev.minerec.artifacts.v1;

@com.google.protobuf.Generated
public interface EntityAttributeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mc_play_recorder.artifacts.v1.EntityAttribute)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string attribute_id = 1 [json_name = "attributeId"];</code>
   * @return The attributeId.
   */
  java.lang.String getAttributeId();
  /**
   * <code>string attribute_id = 1 [json_name = "attributeId"];</code>
   * @return The bytes for attributeId.
   */
  com.google.protobuf.ByteString
      getAttributeIdBytes();

  /**
   * <code>double base = 2 [json_name = "base"];</code>
   * @return The base.
   */
  double getBase();

  /**
   * <code>repeated .mc_play_recorder.artifacts.v1.AttributeModifier modifiers = 3 [json_name = "modifiers"];</code>
   */
  java.util.List<dev.minerec.artifacts.v1.AttributeModifier> 
      getModifiersList();
  /**
   * <code>repeated .mc_play_recorder.artifacts.v1.AttributeModifier modifiers = 3 [json_name = "modifiers"];</code>
   */
  dev.minerec.artifacts.v1.AttributeModifier getModifiers(int index);
  /**
   * <code>repeated .mc_play_recorder.artifacts.v1.AttributeModifier modifiers = 3 [json_name = "modifiers"];</code>
   */
  int getModifiersCount();
  /**
   * <code>repeated .mc_play_recorder.artifacts.v1.AttributeModifier modifiers = 3 [json_name = "modifiers"];</code>
   */
  java.util.List<? extends dev.minerec.artifacts.v1.AttributeModifierOrBuilder> 
      getModifiersOrBuilderList();
  /**
   * <code>repeated .mc_play_recorder.artifacts.v1.AttributeModifier modifiers = 3 [json_name = "modifiers"];</code>
   */
  dev.minerec.artifacts.v1.AttributeModifierOrBuilder getModifiersOrBuilder(
      int index);
}
