// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mc-play-recorder/artifacts/v1/actions.proto
// Protobuf Java Version: 4.33.2

package dev.minerec.artifacts.v1;

/**
 * Protobuf type {@code mc_play_recorder.artifacts.v1.PacketIdentity}
 */
@com.google.protobuf.Generated
public final class PacketIdentity extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:mc_play_recorder.artifacts.v1.PacketIdentity)
    PacketIdentityOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "PacketIdentity");
  }
  // Use PacketIdentity.newBuilder() to construct.
  private PacketIdentity(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PacketIdentity() {
    packetClass_ = "";
    packetType_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return dev.minerec.artifacts.v1.Actions.internal_static_mc_play_recorder_artifacts_v1_PacketIdentity_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return dev.minerec.artifacts.v1.Actions.internal_static_mc_play_recorder_artifacts_v1_PacketIdentity_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            dev.minerec.artifacts.v1.PacketIdentity.class, dev.minerec.artifacts.v1.PacketIdentity.Builder.class);
  }

  public static final int PACKET_CLASS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object packetClass_ = "";
  /**
   * <code>string packet_class = 1 [json_name = "packetClass"];</code>
   * @return The packetClass.
   */
  @java.lang.Override
  public java.lang.String getPacketClass() {
    java.lang.Object ref = packetClass_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      packetClass_ = s;
      return s;
    }
  }
  /**
   * <code>string packet_class = 1 [json_name = "packetClass"];</code>
   * @return The bytes for packetClass.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPacketClassBytes() {
    java.lang.Object ref = packetClass_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      packetClass_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PACKET_TYPE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object packetType_ = "";
  /**
   * <code>string packet_type = 2 [json_name = "packetType"];</code>
   * @return The packetType.
   */
  @java.lang.Override
  public java.lang.String getPacketType() {
    java.lang.Object ref = packetType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      packetType_ = s;
      return s;
    }
  }
  /**
   * <code>string packet_type = 2 [json_name = "packetType"];</code>
   * @return The bytes for packetType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPacketTypeBytes() {
    java.lang.Object ref = packetType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      packetType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RAW_BYTES_AVAILABLE_FIELD_NUMBER = 3;
  private boolean rawBytesAvailable_ = false;
  /**
   * <code>bool raw_bytes_available = 3 [json_name = "rawBytesAvailable"];</code>
   * @return The rawBytesAvailable.
   */
  @java.lang.Override
  public boolean getRawBytesAvailable() {
    return rawBytesAvailable_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(packetClass_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, packetClass_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(packetType_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, packetType_);
    }
    if (rawBytesAvailable_ != false) {
      output.writeBool(3, rawBytesAvailable_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(packetClass_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, packetClass_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(packetType_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, packetType_);
    }
    if (rawBytesAvailable_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, rawBytesAvailable_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof dev.minerec.artifacts.v1.PacketIdentity)) {
      return super.equals(obj);
    }
    dev.minerec.artifacts.v1.PacketIdentity other = (dev.minerec.artifacts.v1.PacketIdentity) obj;

    if (!getPacketClass()
        .equals(other.getPacketClass())) return false;
    if (!getPacketType()
        .equals(other.getPacketType())) return false;
    if (getRawBytesAvailable()
        != other.getRawBytesAvailable()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PACKET_CLASS_FIELD_NUMBER;
    hash = (53 * hash) + getPacketClass().hashCode();
    hash = (37 * hash) + PACKET_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getPacketType().hashCode();
    hash = (37 * hash) + RAW_BYTES_AVAILABLE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getRawBytesAvailable());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static dev.minerec.artifacts.v1.PacketIdentity parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.minerec.artifacts.v1.PacketIdentity parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.minerec.artifacts.v1.PacketIdentity parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.minerec.artifacts.v1.PacketIdentity parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.minerec.artifacts.v1.PacketIdentity parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.minerec.artifacts.v1.PacketIdentity parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.minerec.artifacts.v1.PacketIdentity parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static dev.minerec.artifacts.v1.PacketIdentity parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static dev.minerec.artifacts.v1.PacketIdentity parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static dev.minerec.artifacts.v1.PacketIdentity parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static dev.minerec.artifacts.v1.PacketIdentity parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static dev.minerec.artifacts.v1.PacketIdentity parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(dev.minerec.artifacts.v1.PacketIdentity prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code mc_play_recorder.artifacts.v1.PacketIdentity}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mc_play_recorder.artifacts.v1.PacketIdentity)
      dev.minerec.artifacts.v1.PacketIdentityOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dev.minerec.artifacts.v1.Actions.internal_static_mc_play_recorder_artifacts_v1_PacketIdentity_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dev.minerec.artifacts.v1.Actions.internal_static_mc_play_recorder_artifacts_v1_PacketIdentity_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dev.minerec.artifacts.v1.PacketIdentity.class, dev.minerec.artifacts.v1.PacketIdentity.Builder.class);
    }

    // Construct using dev.minerec.artifacts.v1.PacketIdentity.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      packetClass_ = "";
      packetType_ = "";
      rawBytesAvailable_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return dev.minerec.artifacts.v1.Actions.internal_static_mc_play_recorder_artifacts_v1_PacketIdentity_descriptor;
    }

    @java.lang.Override
    public dev.minerec.artifacts.v1.PacketIdentity getDefaultInstanceForType() {
      return dev.minerec.artifacts.v1.PacketIdentity.getDefaultInstance();
    }

    @java.lang.Override
    public dev.minerec.artifacts.v1.PacketIdentity build() {
      dev.minerec.artifacts.v1.PacketIdentity result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public dev.minerec.artifacts.v1.PacketIdentity buildPartial() {
      dev.minerec.artifacts.v1.PacketIdentity result = new dev.minerec.artifacts.v1.PacketIdentity(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(dev.minerec.artifacts.v1.PacketIdentity result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.packetClass_ = packetClass_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.packetType_ = packetType_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.rawBytesAvailable_ = rawBytesAvailable_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof dev.minerec.artifacts.v1.PacketIdentity) {
        return mergeFrom((dev.minerec.artifacts.v1.PacketIdentity)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(dev.minerec.artifacts.v1.PacketIdentity other) {
      if (other == dev.minerec.artifacts.v1.PacketIdentity.getDefaultInstance()) return this;
      if (!other.getPacketClass().isEmpty()) {
        packetClass_ = other.packetClass_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getPacketType().isEmpty()) {
        packetType_ = other.packetType_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getRawBytesAvailable() != false) {
        setRawBytesAvailable(other.getRawBytesAvailable());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              packetClass_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              packetType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              rawBytesAvailable_ = input.readBool();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object packetClass_ = "";
    /**
     * <code>string packet_class = 1 [json_name = "packetClass"];</code>
     * @return The packetClass.
     */
    public java.lang.String getPacketClass() {
      java.lang.Object ref = packetClass_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        packetClass_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string packet_class = 1 [json_name = "packetClass"];</code>
     * @return The bytes for packetClass.
     */
    public com.google.protobuf.ByteString
        getPacketClassBytes() {
      java.lang.Object ref = packetClass_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        packetClass_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string packet_class = 1 [json_name = "packetClass"];</code>
     * @param value The packetClass to set.
     * @return This builder for chaining.
     */
    public Builder setPacketClass(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      packetClass_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string packet_class = 1 [json_name = "packetClass"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPacketClass() {
      packetClass_ = getDefaultInstance().getPacketClass();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string packet_class = 1 [json_name = "packetClass"];</code>
     * @param value The bytes for packetClass to set.
     * @return This builder for chaining.
     */
    public Builder setPacketClassBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      packetClass_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object packetType_ = "";
    /**
     * <code>string packet_type = 2 [json_name = "packetType"];</code>
     * @return The packetType.
     */
    public java.lang.String getPacketType() {
      java.lang.Object ref = packetType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        packetType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string packet_type = 2 [json_name = "packetType"];</code>
     * @return The bytes for packetType.
     */
    public com.google.protobuf.ByteString
        getPacketTypeBytes() {
      java.lang.Object ref = packetType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        packetType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string packet_type = 2 [json_name = "packetType"];</code>
     * @param value The packetType to set.
     * @return This builder for chaining.
     */
    public Builder setPacketType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      packetType_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string packet_type = 2 [json_name = "packetType"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPacketType() {
      packetType_ = getDefaultInstance().getPacketType();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string packet_type = 2 [json_name = "packetType"];</code>
     * @param value The bytes for packetType to set.
     * @return This builder for chaining.
     */
    public Builder setPacketTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      packetType_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private boolean rawBytesAvailable_ ;
    /**
     * <code>bool raw_bytes_available = 3 [json_name = "rawBytesAvailable"];</code>
     * @return The rawBytesAvailable.
     */
    @java.lang.Override
    public boolean getRawBytesAvailable() {
      return rawBytesAvailable_;
    }
    /**
     * <code>bool raw_bytes_available = 3 [json_name = "rawBytesAvailable"];</code>
     * @param value The rawBytesAvailable to set.
     * @return This builder for chaining.
     */
    public Builder setRawBytesAvailable(boolean value) {

      rawBytesAvailable_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>bool raw_bytes_available = 3 [json_name = "rawBytesAvailable"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRawBytesAvailable() {
      bitField0_ = (bitField0_ & ~0x00000004);
      rawBytesAvailable_ = false;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:mc_play_recorder.artifacts.v1.PacketIdentity)
  }

  // @@protoc_insertion_point(class_scope:mc_play_recorder.artifacts.v1.PacketIdentity)
  private static final dev.minerec.artifacts.v1.PacketIdentity DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new dev.minerec.artifacts.v1.PacketIdentity();
  }

  public static dev.minerec.artifacts.v1.PacketIdentity getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PacketIdentity>
      PARSER = new com.google.protobuf.AbstractParser<PacketIdentity>() {
    @java.lang.Override
    public PacketIdentity parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PacketIdentity> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PacketIdentity> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public dev.minerec.artifacts.v1.PacketIdentity getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

