// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mc-play-recorder/artifacts/v1/actions.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package dev.minerec.artifacts.v1;

@kotlin.jvm.JvmName("-initializeplayerAction")
public inline fun playerAction(block: dev.minerec.artifacts.v1.PlayerActionKt.Dsl.() -> kotlin.Unit): dev.minerec.artifacts.v1.PlayerAction =
  dev.minerec.artifacts.v1.PlayerActionKt.Dsl._create(dev.minerec.artifacts.v1.PlayerAction.newBuilder()).apply { block() }._build()
/**
 * ```
 * PlayerAction models one line of actions.json. apply_sequence is optional
 * because synthetic control_state records do not originate in packet apply.
 * ```
 *
 * Protobuf type `mc_play_recorder.artifacts.v1.PlayerAction`
 */
public object PlayerActionKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: dev.minerec.artifacts.v1.PlayerAction.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: dev.minerec.artifacts.v1.PlayerAction.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): dev.minerec.artifacts.v1.PlayerAction = _builder.build()

    /**
     * `uint32 schema_version = 1 [json_name = "schemaVersion"];`
     */
    public var schemaVersion: kotlin.Int
      @kotlin.jvm.JvmName("getSchemaVersion")
        get() = _builder.schemaVersion
      @kotlin.jvm.JvmName("setSchemaVersion")
        set(value) {
        _builder.schemaVersion = value
      }
    /**
     * `uint32 schema_version = 1 [json_name = "schemaVersion"];`
     */
    public fun clearSchemaVersion() {
      _builder.clearSchemaVersion()
    }

    /**
     * `string source_record_type = 2 [json_name = "sourceRecordType"];`
     */
    public var sourceRecordType: kotlin.String
      @kotlin.jvm.JvmName("getSourceRecordType")
        get() = _builder.sourceRecordType
      @kotlin.jvm.JvmName("setSourceRecordType")
        set(value) {
        _builder.sourceRecordType = value
      }
    /**
     * `string source_record_type = 2 [json_name = "sourceRecordType"];`
     */
    public fun clearSourceRecordType() {
      _builder.clearSourceRecordType()
    }

    /**
     * `string connection_id = 3 [json_name = "connectionId"];`
     */
    public var connectionId: kotlin.String
      @kotlin.jvm.JvmName("getConnectionId")
        get() = _builder.connectionId
      @kotlin.jvm.JvmName("setConnectionId")
        set(value) {
        _builder.connectionId = value
      }
    /**
     * `string connection_id = 3 [json_name = "connectionId"];`
     */
    public fun clearConnectionId() {
      _builder.clearConnectionId()
    }

    /**
     * `string player_uuid = 4 [json_name = "playerUuid"];`
     */
    public var playerUuid: kotlin.String
      @kotlin.jvm.JvmName("getPlayerUuid")
        get() = _builder.playerUuid
      @kotlin.jvm.JvmName("setPlayerUuid")
        set(value) {
        _builder.playerUuid = value
      }
    /**
     * `string player_uuid = 4 [json_name = "playerUuid"];`
     */
    public fun clearPlayerUuid() {
      _builder.clearPlayerUuid()
    }

    /**
     * `int64 server_tick = 5 [json_name = "serverTick"];`
     */
    public var serverTick: kotlin.Long
      @kotlin.jvm.JvmName("getServerTick")
        get() = _builder.serverTick
      @kotlin.jvm.JvmName("setServerTick")
        set(value) {
        _builder.serverTick = value
      }
    /**
     * `int64 server_tick = 5 [json_name = "serverTick"];`
     */
    public fun clearServerTick() {
      _builder.clearServerTick()
    }

    /**
     * `uint64 sequence = 6 [json_name = "sequence"];`
     */
    public var sequence: kotlin.Long
      @kotlin.jvm.JvmName("getSequence")
        get() = _builder.sequence
      @kotlin.jvm.JvmName("setSequence")
        set(value) {
        _builder.sequence = value
      }
    /**
     * `uint64 sequence = 6 [json_name = "sequence"];`
     */
    public fun clearSequence() {
      _builder.clearSequence()
    }

    /**
     * `optional uint64 apply_sequence = 7 [json_name = "applySequence"];`
     */
    public var applySequence: kotlin.Long
      @kotlin.jvm.JvmName("getApplySequence")
        get() = _builder.applySequence
      @kotlin.jvm.JvmName("setApplySequence")
        set(value) {
        _builder.applySequence = value
      }
    /**
     * `optional uint64 apply_sequence = 7 [json_name = "applySequence"];`
     */
    public fun clearApplySequence() {
      _builder.clearApplySequence()
    }
    /**
     * `optional uint64 apply_sequence = 7 [json_name = "applySequence"];`
     * @return Whether the applySequence field is set.
     */
    public fun hasApplySequence(): kotlin.Boolean {
      return _builder.hasApplySequence()
    }

    /**
     * `.mc_play_recorder.artifacts.v1.ControlState control_state = 20 [json_name = "controlState"];`
     */
    public var controlState: dev.minerec.artifacts.v1.ControlState
      @kotlin.jvm.JvmName("getControlState")
        get() = _builder.controlState
      @kotlin.jvm.JvmName("setControlState")
        set(value) {
        _builder.controlState = value
      }
    /**
     * `.mc_play_recorder.artifacts.v1.ControlState control_state = 20 [json_name = "controlState"];`
     */
    public fun clearControlState() {
      _builder.clearControlState()
    }
    /**
     * `.mc_play_recorder.artifacts.v1.ControlState control_state = 20 [json_name = "controlState"];`
     * @return Whether the controlState field is set.
     */
    public fun hasControlState(): kotlin.Boolean {
      return _builder.hasControlState()
    }

    /**
     * `.mc_play_recorder.artifacts.v1.CameraOrPositionAction camera_or_position = 21 [json_name = "cameraOrPosition"];`
     */
    public var cameraOrPosition: dev.minerec.artifacts.v1.CameraOrPositionAction
      @kotlin.jvm.JvmName("getCameraOrPosition")
        get() = _builder.cameraOrPosition
      @kotlin.jvm.JvmName("setCameraOrPosition")
        set(value) {
        _builder.cameraOrPosition = value
      }
    /**
     * `.mc_play_recorder.artifacts.v1.CameraOrPositionAction camera_or_position = 21 [json_name = "cameraOrPosition"];`
     */
    public fun clearCameraOrPosition() {
      _builder.clearCameraOrPosition()
    }
    /**
     * `.mc_play_recorder.artifacts.v1.CameraOrPositionAction camera_or_position = 21 [json_name = "cameraOrPosition"];`
     * @return Whether the cameraOrPosition field is set.
     */
    public fun hasCameraOrPosition(): kotlin.Boolean {
      return _builder.hasCameraOrPosition()
    }

    /**
     * `.mc_play_recorder.artifacts.v1.MovementControlsAction movement_controls = 22 [json_name = "movementControls"];`
     */
    public var movementControls: dev.minerec.artifacts.v1.MovementControlsAction
      @kotlin.jvm.JvmName("getMovementControls")
        get() = _builder.movementControls
      @kotlin.jvm.JvmName("setMovementControls")
        set(value) {
        _builder.movementControls = value
      }
    /**
     * `.mc_play_recorder.artifacts.v1.MovementControlsAction movement_controls = 22 [json_name = "movementControls"];`
     */
    public fun clearMovementControls() {
      _builder.clearMovementControls()
    }
    /**
     * `.mc_play_recorder.artifacts.v1.MovementControlsAction movement_controls = 22 [json_name = "movementControls"];`
     * @return Whether the movementControls field is set.
     */
    public fun hasMovementControls(): kotlin.Boolean {
      return _builder.hasMovementControls()
    }

    /**
     * `.mc_play_recorder.artifacts.v1.PacketAction player_action = 23 [json_name = "playerAction"];`
     */
    public var playerAction: dev.minerec.artifacts.v1.PacketAction
      @kotlin.jvm.JvmName("getPlayerAction")
        get() = _builder.playerAction
      @kotlin.jvm.JvmName("setPlayerAction")
        set(value) {
        _builder.playerAction = value
      }
    /**
     * `.mc_play_recorder.artifacts.v1.PacketAction player_action = 23 [json_name = "playerAction"];`
     */
    public fun clearPlayerAction() {
      _builder.clearPlayerAction()
    }
    /**
     * `.mc_play_recorder.artifacts.v1.PacketAction player_action = 23 [json_name = "playerAction"];`
     * @return Whether the playerAction field is set.
     */
    public fun hasPlayerAction(): kotlin.Boolean {
      return _builder.hasPlayerAction()
    }

    /**
     * `.mc_play_recorder.artifacts.v1.PacketAction protocol_ack = 24 [json_name = "protocolAck"];`
     */
    public var protocolAck: dev.minerec.artifacts.v1.PacketAction
      @kotlin.jvm.JvmName("getProtocolAck")
        get() = _builder.protocolAck
      @kotlin.jvm.JvmName("setProtocolAck")
        set(value) {
        _builder.protocolAck = value
      }
    /**
     * `.mc_play_recorder.artifacts.v1.PacketAction protocol_ack = 24 [json_name = "protocolAck"];`
     */
    public fun clearProtocolAck() {
      _builder.clearProtocolAck()
    }
    /**
     * `.mc_play_recorder.artifacts.v1.PacketAction protocol_ack = 24 [json_name = "protocolAck"];`
     * @return Whether the protocolAck field is set.
     */
    public fun hasProtocolAck(): kotlin.Boolean {
      return _builder.hasProtocolAck()
    }

    /**
     * `.mc_play_recorder.artifacts.v1.PacketAction swing = 25 [json_name = "swing"];`
     */
    public var swing: dev.minerec.artifacts.v1.PacketAction
      @kotlin.jvm.JvmName("getSwing")
        get() = _builder.swing
      @kotlin.jvm.JvmName("setSwing")
        set(value) {
        _builder.swing = value
      }
    /**
     * `.mc_play_recorder.artifacts.v1.PacketAction swing = 25 [json_name = "swing"];`
     */
    public fun clearSwing() {
      _builder.clearSwing()
    }
    /**
     * `.mc_play_recorder.artifacts.v1.PacketAction swing = 25 [json_name = "swing"];`
     * @return Whether the swing field is set.
     */
    public fun hasSwing(): kotlin.Boolean {
      return _builder.hasSwing()
    }

    /**
     * `.mc_play_recorder.artifacts.v1.TextRedactedAction text_redacted = 26 [json_name = "textRedacted"];`
     */
    public var textRedacted: dev.minerec.artifacts.v1.TextRedactedAction
      @kotlin.jvm.JvmName("getTextRedacted")
        get() = _builder.textRedacted
      @kotlin.jvm.JvmName("setTextRedacted")
        set(value) {
        _builder.textRedacted = value
      }
    /**
     * `.mc_play_recorder.artifacts.v1.TextRedactedAction text_redacted = 26 [json_name = "textRedacted"];`
     */
    public fun clearTextRedacted() {
      _builder.clearTextRedacted()
    }
    /**
     * `.mc_play_recorder.artifacts.v1.TextRedactedAction text_redacted = 26 [json_name = "textRedacted"];`
     * @return Whether the textRedacted field is set.
     */
    public fun hasTextRedacted(): kotlin.Boolean {
      return _builder.hasTextRedacted()
    }

    /**
     * `.mc_play_recorder.artifacts.v1.PacketAction tick_boundary = 27 [json_name = "tickBoundary"];`
     */
    public var tickBoundary: dev.minerec.artifacts.v1.PacketAction
      @kotlin.jvm.JvmName("getTickBoundary")
        get() = _builder.tickBoundary
      @kotlin.jvm.JvmName("setTickBoundary")
        set(value) {
        _builder.tickBoundary = value
      }
    /**
     * `.mc_play_recorder.artifacts.v1.PacketAction tick_boundary = 27 [json_name = "tickBoundary"];`
     */
    public fun clearTickBoundary() {
      _builder.clearTickBoundary()
    }
    /**
     * `.mc_play_recorder.artifacts.v1.PacketAction tick_boundary = 27 [json_name = "tickBoundary"];`
     * @return Whether the tickBoundary field is set.
     */
    public fun hasTickBoundary(): kotlin.Boolean {
      return _builder.hasTickBoundary()
    }

    /**
     * `.mc_play_recorder.artifacts.v1.PacketAction packet = 28 [json_name = "packet"];`
     */
    public var packet: dev.minerec.artifacts.v1.PacketAction
      @kotlin.jvm.JvmName("getPacket")
        get() = _builder.packet
      @kotlin.jvm.JvmName("setPacket")
        set(value) {
        _builder.packet = value
      }
    /**
     * `.mc_play_recorder.artifacts.v1.PacketAction packet = 28 [json_name = "packet"];`
     */
    public fun clearPacket() {
      _builder.clearPacket()
    }
    /**
     * `.mc_play_recorder.artifacts.v1.PacketAction packet = 28 [json_name = "packet"];`
     * @return Whether the packet field is set.
     */
    public fun hasPacket(): kotlin.Boolean {
      return _builder.hasPacket()
    }
    public val payloadCase: dev.minerec.artifacts.v1.PlayerAction.PayloadCase
    @kotlin.jvm.JvmName("getPayloadCase")
      get() = _builder.getPayloadCase()

    public fun clearPayload() {
      _builder.clearPayload()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun dev.minerec.artifacts.v1.PlayerAction.copy(block: `dev.minerec.artifacts.v1`.PlayerActionKt.Dsl.() -> kotlin.Unit): dev.minerec.artifacts.v1.PlayerAction =
  `dev.minerec.artifacts.v1`.PlayerActionKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val dev.minerec.artifacts.v1.PlayerActionOrBuilder.controlStateOrNull: dev.minerec.artifacts.v1.ControlState?
  get() = if (hasControlState()) getControlState() else null

public val dev.minerec.artifacts.v1.PlayerActionOrBuilder.cameraOrPositionOrNull: dev.minerec.artifacts.v1.CameraOrPositionAction?
  get() = if (hasCameraOrPosition()) getCameraOrPosition() else null

public val dev.minerec.artifacts.v1.PlayerActionOrBuilder.movementControlsOrNull: dev.minerec.artifacts.v1.MovementControlsAction?
  get() = if (hasMovementControls()) getMovementControls() else null

public val dev.minerec.artifacts.v1.PlayerActionOrBuilder.playerActionOrNull: dev.minerec.artifacts.v1.PacketAction?
  get() = if (hasPlayerAction()) getPlayerAction() else null

public val dev.minerec.artifacts.v1.PlayerActionOrBuilder.protocolAckOrNull: dev.minerec.artifacts.v1.PacketAction?
  get() = if (hasProtocolAck()) getProtocolAck() else null

public val dev.minerec.artifacts.v1.PlayerActionOrBuilder.swingOrNull: dev.minerec.artifacts.v1.PacketAction?
  get() = if (hasSwing()) getSwing() else null

public val dev.minerec.artifacts.v1.PlayerActionOrBuilder.textRedactedOrNull: dev.minerec.artifacts.v1.TextRedactedAction?
  get() = if (hasTextRedacted()) getTextRedacted() else null

public val dev.minerec.artifacts.v1.PlayerActionOrBuilder.tickBoundaryOrNull: dev.minerec.artifacts.v1.PacketAction?
  get() = if (hasTickBoundary()) getTickBoundary() else null

public val dev.minerec.artifacts.v1.PlayerActionOrBuilder.packetOrNull: dev.minerec.artifacts.v1.PacketAction?
  get() = if (hasPacket()) getPacket() else null

