// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mc-play-recorder/artifacts/v1/common.proto
// Protobuf Java Version: 4.33.2

package dev.minerec.artifacts.v1;

@com.google.protobuf.Generated
public interface RotationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mc_play_recorder.artifacts.v1.Rotation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double yaw = 1 [json_name = "yaw"];</code>
   * @return The yaw.
   */
  double getYaw();

  /**
   * <code>double pitch = 2 [json_name = "pitch"];</code>
   * @return The pitch.
   */
  double getPitch();

  /**
   * <code>double head_yaw = 3 [json_name = "headYaw"];</code>
   * @return The headYaw.
   */
  double getHeadYaw();
}
