// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mc-play-recorder/artifacts/v1/scene_extraction.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package dev.minerec.artifacts.v1;

@kotlin.jvm.JvmName("-initializesceneStreamResult")
public inline fun sceneStreamResult(block: dev.minerec.artifacts.v1.SceneStreamResultKt.Dsl.() -> kotlin.Unit): dev.minerec.artifacts.v1.SceneStreamResult =
  dev.minerec.artifacts.v1.SceneStreamResultKt.Dsl._create(dev.minerec.artifacts.v1.SceneStreamResult.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `mc_play_recorder.artifacts.v1.SceneStreamResult`
 */
public object SceneStreamResultKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: dev.minerec.artifacts.v1.SceneStreamResult.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: dev.minerec.artifacts.v1.SceneStreamResult.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): dev.minerec.artifacts.v1.SceneStreamResult = _builder.build()

    /**
     * `string path = 1 [json_name = "path"];`
     */
    public var path: kotlin.String
      @kotlin.jvm.JvmName("getPath")
        get() = _builder.path
      @kotlin.jvm.JvmName("setPath")
        set(value) {
        _builder.path = value
      }
    /**
     * `string path = 1 [json_name = "path"];`
     */
    public fun clearPath() {
      _builder.clearPath()
    }

    /**
     * `string frames = 2 [json_name = "frames"];`
     */
    public var frames: kotlin.String
      @kotlin.jvm.JvmName("getFrames")
        get() = _builder.frames
      @kotlin.jvm.JvmName("setFrames")
        set(value) {
        _builder.frames = value
      }
    /**
     * `string frames = 2 [json_name = "frames"];`
     */
    public fun clearFrames() {
      _builder.clearFrames()
    }

    /**
     * `string changes = 3 [json_name = "changes"];`
     */
    public var changes: kotlin.String
      @kotlin.jvm.JvmName("getChanges")
        get() = _builder.changes
      @kotlin.jvm.JvmName("setChanges")
        set(value) {
        _builder.changes = value
      }
    /**
     * `string changes = 3 [json_name = "changes"];`
     */
    public fun clearChanges() {
      _builder.clearChanges()
    }

    /**
     * `string blobs_directory = 4 [json_name = "blobsDirectory"];`
     */
    public var blobsDirectory: kotlin.String
      @kotlin.jvm.JvmName("getBlobsDirectory")
        get() = _builder.blobsDirectory
      @kotlin.jvm.JvmName("setBlobsDirectory")
        set(value) {
        _builder.blobsDirectory = value
      }
    /**
     * `string blobs_directory = 4 [json_name = "blobsDirectory"];`
     */
    public fun clearBlobsDirectory() {
      _builder.clearBlobsDirectory()
    }

    /**
     * `uint64 frame_count = 5 [json_name = "frameCount"];`
     */
    public var frameCount: kotlin.Long
      @kotlin.jvm.JvmName("getFrameCount")
        get() = _builder.frameCount
      @kotlin.jvm.JvmName("setFrameCount")
        set(value) {
        _builder.frameCount = value
      }
    /**
     * `uint64 frame_count = 5 [json_name = "frameCount"];`
     */
    public fun clearFrameCount() {
      _builder.clearFrameCount()
    }

    /**
     * `uint64 change_count = 6 [json_name = "changeCount"];`
     */
    public var changeCount: kotlin.Long
      @kotlin.jvm.JvmName("getChangeCount")
        get() = _builder.changeCount
      @kotlin.jvm.JvmName("setChangeCount")
        set(value) {
        _builder.changeCount = value
      }
    /**
     * `uint64 change_count = 6 [json_name = "changeCount"];`
     */
    public fun clearChangeCount() {
      _builder.clearChangeCount()
    }

    /**
     * `uint64 blob_count = 7 [json_name = "blobCount"];`
     */
    public var blobCount: kotlin.Long
      @kotlin.jvm.JvmName("getBlobCount")
        get() = _builder.blobCount
      @kotlin.jvm.JvmName("setBlobCount")
        set(value) {
        _builder.blobCount = value
      }
    /**
     * `uint64 blob_count = 7 [json_name = "blobCount"];`
     */
    public fun clearBlobCount() {
      _builder.clearBlobCount()
    }

    /**
     * `uint64 blob_bytes = 8 [json_name = "blobBytes"];`
     */
    public var blobBytes: kotlin.Long
      @kotlin.jvm.JvmName("getBlobBytes")
        get() = _builder.blobBytes
      @kotlin.jvm.JvmName("setBlobBytes")
        set(value) {
        _builder.blobBytes = value
      }
    /**
     * `uint64 blob_bytes = 8 [json_name = "blobBytes"];`
     */
    public fun clearBlobBytes() {
      _builder.clearBlobBytes()
    }

    /**
     * `string frames_sha256 = 9 [json_name = "framesSha256"];`
     */
    public var framesSha256: kotlin.String
      @kotlin.jvm.JvmName("getFramesSha256")
        get() = _builder.framesSha256
      @kotlin.jvm.JvmName("setFramesSha256")
        set(value) {
        _builder.framesSha256 = value
      }
    /**
     * `string frames_sha256 = 9 [json_name = "framesSha256"];`
     */
    public fun clearFramesSha256() {
      _builder.clearFramesSha256()
    }

    /**
     * `uint64 frames_size_bytes = 10 [json_name = "framesSizeBytes"];`
     */
    public var framesSizeBytes: kotlin.Long
      @kotlin.jvm.JvmName("getFramesSizeBytes")
        get() = _builder.framesSizeBytes
      @kotlin.jvm.JvmName("setFramesSizeBytes")
        set(value) {
        _builder.framesSizeBytes = value
      }
    /**
     * `uint64 frames_size_bytes = 10 [json_name = "framesSizeBytes"];`
     */
    public fun clearFramesSizeBytes() {
      _builder.clearFramesSizeBytes()
    }

    /**
     * `string changes_sha256 = 11 [json_name = "changesSha256"];`
     */
    public var changesSha256: kotlin.String
      @kotlin.jvm.JvmName("getChangesSha256")
        get() = _builder.changesSha256
      @kotlin.jvm.JvmName("setChangesSha256")
        set(value) {
        _builder.changesSha256 = value
      }
    /**
     * `string changes_sha256 = 11 [json_name = "changesSha256"];`
     */
    public fun clearChangesSha256() {
      _builder.clearChangesSha256()
    }

    /**
     * `uint64 changes_size_bytes = 12 [json_name = "changesSizeBytes"];`
     */
    public var changesSizeBytes: kotlin.Long
      @kotlin.jvm.JvmName("getChangesSizeBytes")
        get() = _builder.changesSizeBytes
      @kotlin.jvm.JvmName("setChangesSizeBytes")
        set(value) {
        _builder.changesSizeBytes = value
      }
    /**
     * `uint64 changes_size_bytes = 12 [json_name = "changesSizeBytes"];`
     */
    public fun clearChangesSizeBytes() {
      _builder.clearChangesSizeBytes()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun dev.minerec.artifacts.v1.SceneStreamResult.copy(block: `dev.minerec.artifacts.v1`.SceneStreamResultKt.Dsl.() -> kotlin.Unit): dev.minerec.artifacts.v1.SceneStreamResult =
  `dev.minerec.artifacts.v1`.SceneStreamResultKt.Dsl._create(this.toBuilder()).apply { block() }._build()

