// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mc-play-recorder/artifacts/v1/scene_extraction.proto
// Protobuf Java Version: 4.33.2

package dev.minerec.artifacts.v1;

@com.google.protobuf.Generated
public final class SceneExtraction extends com.google.protobuf.GeneratedFile {
  private SceneExtraction() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "SceneExtraction");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mc_play_recorder_artifacts_v1_SceneExtractionJob_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mc_play_recorder_artifacts_v1_SceneExtractionJob_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mc_play_recorder_artifacts_v1_SceneSourceReplay_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mc_play_recorder_artifacts_v1_SceneSourceReplay_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mc_play_recorder_artifacts_v1_SubjectPose_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mc_play_recorder_artifacts_v1_SubjectPose_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mc_play_recorder_artifacts_v1_SceneExtractionResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mc_play_recorder_artifacts_v1_SceneExtractionResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mc_play_recorder_artifacts_v1_SceneExtractionResult_IgnoredPacketCountsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mc_play_recorder_artifacts_v1_SceneExtractionResult_IgnoredPacketCountsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mc_play_recorder_artifacts_v1_SceneStreamResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mc_play_recorder_artifacts_v1_SceneStreamResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mc_play_recorder_artifacts_v1_SceneFrameRecord_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mc_play_recorder_artifacts_v1_SceneFrameRecord_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mc_play_recorder_artifacts_v1_SceneChangeRecord_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mc_play_recorder_artifacts_v1_SceneChangeRecord_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mc_play_recorder_artifacts_v1_SegmentBegin_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mc_play_recorder_artifacts_v1_SegmentBegin_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mc_play_recorder_artifacts_v1_SectionChange_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mc_play_recorder_artifacts_v1_SectionChange_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mc_play_recorder_artifacts_v1_EntityChange_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mc_play_recorder_artifacts_v1_EntityChange_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mc_play_recorder_artifacts_v1_BlockEntityChange_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mc_play_recorder_artifacts_v1_BlockEntityChange_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mc_play_recorder_artifacts_v1_SceneBlobPayload_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mc_play_recorder_artifacts_v1_SceneBlobPayload_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mc_play_recorder_artifacts_v1_SectionBlob_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mc_play_recorder_artifacts_v1_SectionBlob_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mc_play_recorder_artifacts_v1_BlockState_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mc_play_recorder_artifacts_v1_BlockState_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mc_play_recorder_artifacts_v1_BlockState_PropertiesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mc_play_recorder_artifacts_v1_BlockState_PropertiesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mc_play_recorder_artifacts_v1_EncodedValue_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mc_play_recorder_artifacts_v1_EncodedValue_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mc_play_recorder_artifacts_v1_EntityBlob_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mc_play_recorder_artifacts_v1_EntityBlob_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mc_play_recorder_artifacts_v1_Bounds_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mc_play_recorder_artifacts_v1_Bounds_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mc_play_recorder_artifacts_v1_EntityMetadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mc_play_recorder_artifacts_v1_EntityMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mc_play_recorder_artifacts_v1_Equipment_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mc_play_recorder_artifacts_v1_Equipment_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mc_play_recorder_artifacts_v1_EntityAttribute_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mc_play_recorder_artifacts_v1_EntityAttribute_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mc_play_recorder_artifacts_v1_AttributeModifier_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mc_play_recorder_artifacts_v1_AttributeModifier_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mc_play_recorder_artifacts_v1_EntityEffect_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mc_play_recorder_artifacts_v1_EntityEffect_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mc_play_recorder_artifacts_v1_PlayerListInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mc_play_recorder_artifacts_v1_PlayerListInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mc_play_recorder_artifacts_v1_BlockEntityBlob_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mc_play_recorder_artifacts_v1_BlockEntityBlob_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n4mc-play-recorder/artifacts/v1/scene_ex" +
      "traction.proto\022\035mc_play_recorder.artifac" +
      "ts.v1\032*mc-play-recorder/artifacts/v1/com" +
      "mon.proto\032*mc-play-recorder/artifacts/v1" +
      "/events.proto\"\221\005\n\022SceneExtractionJob\022\025\n\006" +
      "job_id\030\001 \001(\tR\005jobId\022\035\n\nsession_id\030\002 \001(\tR" +
      "\tsessionId\022\037\n\013player_uuid\030\003 \001(\tR\nplayerU" +
      "uid\022#\n\rconnection_id\030\004 \001(\tR\014connectionId" +
      "\022>\n\005ticks\030\005 \001(\0132(.mc_play_recorder.artif" +
      "acts.v1.TickRangeR\005ticks\022\024\n\005scope\030\006 \001(\tR" +
      "\005scope\022\'\n\017metadata_policy\030\007 \001(\tR\016metadat" +
      "aPolicy\022<\n\032flashback_capture_contract\030\010 " +
      "\001(\tR\030flashbackCaptureContract\022W\n\016source_" +
      "replays\030\t \003(\01320.mc_play_recorder.artifac" +
      "ts.v1.SceneSourceReplayR\rsourceReplays\022P" +
      "\n\rsubject_poses\030\n \001(\0132+.mc_play_recorder" +
      ".artifacts.v1.ArtifactFileR\014subjectPoses" +
      "\022P\n\rsource_events\030\013 \001(\0132+.mc_play_record" +
      "er.artifacts.v1.ArtifactFileR\014sourceEven" +
      "ts\022\037\n\013output_path\030\014 \001(\tR\noutputPath\022$\n\016s" +
      "top_when_done\030\r \001(\010R\014stopWhenDone\"\276\001\n\021Sc" +
      "eneSourceReplay\022\035\n\nsegment_id\030\001 \001(\tR\tseg" +
      "mentId\022\'\n\017segment_ordinal\030\002 \001(\rR\016segment" +
      "Ordinal\022\022\n\004path\030\003 \001(\tR\004path\022\026\n\006sha256\030\004 " +
      "\001(\tR\006sha256\022\035\n\nsize_bytes\030\005 \001(\004R\tsizeByt" +
      "es\022\026\n\006format\030\006 \001(\tR\006format\"\270\003\n\013SubjectPo" +
      "se\022\037\n\013server_tick\030\001 \001(\003R\nserverTick\022\035\n\ns" +
      "ession_id\030\002 \001(\tR\tsessionId\022\037\n\013player_uui" +
      "d\030\003 \001(\tR\nplayerUuid\022#\n\rconnection_id\030\004 \001" +
      "(\tR\014connectionId\022\033\n\tentity_id\030\005 \001(\005R\010ent" +
      "ityId\022\034\n\tdimension\030\006 \001(\tR\tdimension\022B\n\010p" +
      "osition\030\007 \001(\0132&.mc_play_recorder.artifac" +
      "ts.v1.Vector3R\010position\022B\n\010velocity\030\010 \001(" +
      "\0132&.mc_play_recorder.artifacts.v1.Vector" +
      "3R\010velocity\022C\n\010rotation\030\t \001(\0132\'.mc_play_" +
      "recorder.artifacts.v1.RotationR\010rotation" +
      "\022\033\n\ton_ground\030\n \001(\010R\010onGround\"\344\006\n\025SceneE" +
      "xtractionResult\022S\n\006status\030\001 \001(\0162;.mc_pla" +
      "y_recorder.artifacts.v1.SceneExtractionR" +
      "esult.StatusR\006status\022\024\n\005error\030\002 \001(\tR\005err" +
      "or\022\025\n\006job_id\030\003 \001(\tR\005jobId\022\035\n\nsession_id\030" +
      "\004 \001(\tR\tsessionId\022\037\n\013player_uuid\030\005 \001(\tR\np" +
      "layerUuid\022#\n\rconnection_id\030\006 \001(\tR\014connec" +
      "tionId\022>\n\005ticks\030\007 \001(\0132(.mc_play_recorder" +
      ".artifacts.v1.TickRangeR\005ticks\022\024\n\005scope\030" +
      "\010 \001(\tR\005scope\022\'\n\017metadata_policy\030\t \001(\tR\016m" +
      "etadataPolicy\022W\n\016source_replays\030\n \003(\01320." +
      "mc_play_recorder.artifacts.v1.SceneSourc" +
      "eReplayR\rsourceReplays\022H\n\006stream\030\013 \001(\01320" +
      ".mc_play_recorder.artifacts.v1.SceneStre" +
      "amResultR\006stream\022\201\001\n\025ignored_packet_coun" +
      "ts\030\014 \003(\0132M.mc_play_recorder.artifacts.v1" +
      ".SceneExtractionResult.IgnoredPacketCoun" +
      "tsEntryR\023ignoredPacketCounts\022,\n\022covered_" +
      "tick_count\030\r \001(\004R\020coveredTickCount\032F\n\030Ig" +
      "noredPacketCountsEntry\022\020\n\003key\030\001 \001(\tR\003key" +
      "\022\024\n\005value\030\002 \001(\004R\005value:\0028\001\"H\n\006Status\022\026\n\022" +
      "STATUS_UNSPECIFIED\020\000\022\023\n\017STATUS_COMPLETE\020" +
      "\001\022\021\n\rSTATUS_FAILED\020\002\"\252\003\n\021SceneStreamResu" +
      "lt\022\022\n\004path\030\001 \001(\tR\004path\022\026\n\006frames\030\002 \001(\tR\006" +
      "frames\022\030\n\007changes\030\003 \001(\tR\007changes\022\'\n\017blob" +
      "s_directory\030\004 \001(\tR\016blobsDirectory\022\037\n\013fra" +
      "me_count\030\005 \001(\004R\nframeCount\022!\n\014change_cou" +
      "nt\030\006 \001(\004R\013changeCount\022\035\n\nblob_count\030\007 \001(" +
      "\004R\tblobCount\022\035\n\nblob_bytes\030\010 \001(\004R\tblobBy" +
      "tes\022#\n\rframes_sha256\030\t \001(\tR\014framesSha256" +
      "\022*\n\021frames_size_bytes\030\n \001(\004R\017framesSizeB" +
      "ytes\022%\n\016changes_sha256\030\013 \001(\tR\rchangesSha" +
      "256\022,\n\022changes_size_bytes\030\014 \001(\004R\020changes" +
      "SizeBytes\"\237\005\n\020SceneFrameRecord\022\037\n\013server" +
      "_tick\030\001 \001(\003R\nserverTick\022\031\n\010frame_id\030\002 \001(" +
      "\tR\007frameId\022\037\n\013replay_tick\030\003 \001(\003R\nreplayT" +
      "ick\022\034\n\tdimension\030\004 \001(\tR\tdimension\022Q\n\020sub" +
      "ject_position\030\005 \001(\0132&.mc_play_recorder.a" +
      "rtifacts.v1.Vector3R\017subjectPosition\022+\n\021" +
      "coverage_complete\030\006 \001(\010R\020coverageComplet" +
      "e\022\035\n\nsegment_id\030\007 \001(\tR\tsegmentId\022\'\n\017segm" +
      "ent_ordinal\030\010 \001(\rR\016segmentOrdinal\022%\n\016eve" +
      "nt_sequence\030\t \001(\004R\reventSequence\022!\n\014enti" +
      "ty_count\030\n \001(\005R\013entityCount\0220\n\024loaded_se" +
      "ction_count\030\013 \001(\005R\022loadedSectionCount\022\'\n" +
      "\017metadata_policy\030\014 \001(\tR\016metadataPolicy\0222" +
      "\n\025scene_snapshot_sha256\030\r \001(\tR\023sceneSnap" +
      "shotSha256\022\024\n\005scope\030\016 \001(\tR\005scope\022*\n\021subj" +
      "ect_entity_id\030\017 \001(\005R\017subjectEntityId\022-\n\022" +
      "incomplete_reasons\030\020 \003(\tR\021incompleteReas" +
      "ons\"\243\006\n\021SceneChangeRecord\022\032\n\010sequence\030\001 " +
      "\001(\004R\010sequence\022\037\n\013server_tick\030\002 \001(\003R\nserv" +
      "erTick\022\037\n\013replay_tick\030\003 \001(\003R\nreplayTick\022" +
      "\035\n\nsegment_id\030\004 \001(\tR\tsegmentId\022\'\n\017segmen" +
      "t_ordinal\030\005 \001(\rR\016segmentOrdinal\022R\n\rsegme" +
      "nt_begin\030\024 \001(\0132+.mc_play_recorder.artifa" +
      "cts.v1.SegmentBeginH\000R\014segmentBegin\022O\n\013s" +
      "ection_set\030\025 \001(\0132,.mc_play_recorder.arti" +
      "facts.v1.SectionChangeH\000R\nsectionSet\022U\n\016" +
      "section_unload\030\026 \001(\0132,.mc_play_recorder." +
      "artifacts.v1.SectionChangeH\000R\rsectionUnl" +
      "oad\022L\n\nentity_set\030\027 \001(\0132+.mc_play_record" +
      "er.artifacts.v1.EntityChangeH\000R\tentitySe" +
      "t\022R\n\rentity_remove\030\030 \001(\0132+.mc_play_recor" +
      "der.artifacts.v1.EntityChangeH\000R\014entityR" +
      "emove\022\\\n\020block_entity_set\030\031 \001(\01320.mc_pla" +
      "y_recorder.artifacts.v1.BlockEntityChang" +
      "eH\000R\016blockEntitySet\022b\n\023block_entity_remo" +
      "ve\030\032 \001(\01320.mc_play_recorder.artifacts.v1" +
      ".BlockEntityChangeH\000R\021blockEntityRemoveB" +
      "\010\n\006change\"E\n\014SegmentBegin\022\026\n\006sha256\030\001 \001(" +
      "\tR\006sha256\022\035\n\nsize_bytes\030\002 \001(\004R\tsizeBytes" +
      "\"x\n\rSectionChange\022\034\n\tdimension\030\001 \001(\tR\tdi" +
      "mension\022\014\n\001x\030\002 \001(\005R\001x\022\014\n\001y\030\003 \001(\005R\001y\022\014\n\001z" +
      "\030\004 \001(\005R\001z\022\037\n\013blob_sha256\030\005 \001(\tR\nblobSha2" +
      "56\"P\n\014EntityChange\022\037\n\013instance_id\030\001 \001(\tR" +
      "\ninstanceId\022\037\n\013blob_sha256\030\002 \001(\tR\nblobSh" +
      "a256\"|\n\021BlockEntityChange\022\034\n\tdimension\030\001" +
      " \001(\tR\tdimension\022\014\n\001x\030\002 \001(\005R\001x\022\014\n\001y\030\003 \001(\005" +
      "R\001y\022\014\n\001z\030\004 \001(\005R\001z\022\037\n\013blob_sha256\030\005 \001(\tR\n" +
      "blobSha256\"\230\003\n\020SceneBlobPayload\022F\n\007secti" +
      "on\030\001 \001(\0132*.mc_play_recorder.artifacts.v1" +
      ".SectionBlobH\000R\007section\022C\n\006entity\030\002 \001(\0132" +
      ").mc_play_recorder.artifacts.v1.EntityBl" +
      "obH\000R\006entity\022S\n\014block_entity\030\003 \001(\0132..mc_" +
      "play_recorder.artifacts.v1.BlockEntityBl" +
      "obH\000R\013blockEntity\022G\n\005frame\030\004 \001(\0132/.mc_pl" +
      "ay_recorder.artifacts.v1.SceneFrameRecor" +
      "dH\000R\005frame\022P\n\014player_state\030\005 \001(\0132+.mc_pl" +
      "ay_recorder.artifacts.v1.CaptureEventH\000R" +
      "\013playerStateB\007\n\005value\"x\n\013SectionBlob\022C\n\007" +
      "palette\030\001 \003(\0132).mc_play_recorder.artifac" +
      "ts.v1.BlockStateR\007palette\022$\n\016indices_le_" +
      "u16\030\002 \001(\014R\014indicesLeU16\"\272\001\n\nBlockState\022\022" +
      "\n\004name\030\001 \001(\tR\004name\022Y\n\nproperties\030\002 \003(\01329" +
      ".mc_play_recorder.artifacts.v1.BlockStat" +
      "e.PropertiesEntryR\nproperties\032=\n\017Propert" +
      "iesEntry\022\020\n\003key\030\001 \001(\tR\003key\022\024\n\005value\030\002 \001(" +
      "\tR\005value:\0028\001\"|\n\014EncodedValue\022!\n\014logical_" +
      "type\030\001 \001(\tR\013logicalType\022\031\n\010codec_id\030\002 \001(" +
      "\005R\007codecId\022\032\n\010encoding\030\003 \001(\tR\010encoding\022\022" +
      "\n\004data\030\004 \001(\014R\004data\"\225\010\n\nEntityBlob\022=\n\006bou" +
      "nds\030\001 \001(\0132%.mc_play_recorder.artifacts.v" +
      "1.BoundsR\006bounds\022\034\n\tdimension\030\002 \001(\tR\tdim" +
      "ension\022\035\n\nnetwork_id\030\003 \001(\005R\tnetworkId\022\027\n" +
      "\004uuid\030\004 \001(\tH\000R\004uuid\210\001\001\022\027\n\007type_id\030\005 \001(\tR" +
      "\006typeId\022B\n\010position\030\006 \001(\0132&.mc_play_reco" +
      "rder.artifacts.v1.Vector3R\010position\022B\n\010v" +
      "elocity\030\007 \001(\0132&.mc_play_recorder.artifac" +
      "ts.v1.Vector3R\010velocity\022C\n\010rotation\030\010 \001(" +
      "\0132\'.mc_play_recorder.artifacts.v1.Rotati" +
      "onR\010rotation\022\024\n\005width\030\t \001(\001R\005width\022\026\n\006he" +
      "ight\030\n \001(\001R\006height\022\033\n\ton_ground\030\013 \001(\010R\010o" +
      "nGround\022\030\n\007subject\030\014 \001(\010R\007subject\022\035\n\nspa" +
      "wn_data\030\r \001(\005R\tspawnData\022D\n\034leash_destin" +
      "ation_network_id\030\016 \001(\005H\001R\031leashDestinati" +
      "onNetworkId\210\001\001\022\036\n\npassengers\030\017 \003(\005R\npass" +
      "engers\022I\n\010metadata\030\020 \003(\0132-.mc_play_recor" +
      "der.artifacts.v1.EntityMetadataR\010metadat" +
      "a\022F\n\tequipment\030\021 \003(\0132(.mc_play_recorder." +
      "artifacts.v1.EquipmentR\tequipment\022N\n\natt" +
      "ributes\030\022 \003(\0132..mc_play_recorder.artifac" +
      "ts.v1.EntityAttributeR\nattributes\022E\n\007eff" +
      "ects\030\023 \003(\0132+.mc_play_recorder.artifacts." +
      "v1.EntityEffectR\007effects\022N\n\013player_info\030" +
      "\024 \001(\0132-.mc_play_recorder.artifacts.v1.Pl" +
      "ayerListInfoR\nplayerInfoB\007\n\005_uuidB\037\n\035_le" +
      "ash_destination_network_id\"\206\001\n\006Bounds\022\023\n" +
      "\005min_x\030\001 \001(\001R\004minX\022\023\n\005min_y\030\002 \001(\001R\004minY\022" +
      "\023\n\005min_z\030\003 \001(\001R\004minZ\022\023\n\005max_x\030\004 \001(\001R\004max" +
      "X\022\023\n\005max_y\030\005 \001(\001R\004maxY\022\023\n\005max_z\030\006 \001(\001R\004m" +
      "axZ\"i\n\016EntityMetadata\022\024\n\005index\030\001 \001(\005R\005in" +
      "dex\022A\n\005value\030\002 \001(\0132+.mc_play_recorder.ar" +
      "tifacts.v1.EncodedValueR\005value\"\240\001\n\tEquip" +
      "ment\022\022\n\004slot\030\001 \001(\tR\004slot\022\027\n\007item_id\030\002 \001(" +
      "\tR\006itemId\022\024\n\005count\030\003 \001(\005R\005count\022P\n\rencod" +
      "ed_stack\030\004 \001(\0132+.mc_play_recorder.artifa" +
      "cts.v1.EncodedValueR\014encodedStack\"\230\001\n\017En" +
      "tityAttribute\022!\n\014attribute_id\030\001 \001(\tR\013att" +
      "ributeId\022\022\n\004base\030\002 \001(\001R\004base\022N\n\tmodifier" +
      "s\030\003 \003(\01320.mc_play_recorder.artifacts.v1." +
      "AttributeModifierR\tmodifiers\"Y\n\021Attribut" +
      "eModifier\022\016\n\002id\030\001 \001(\tR\002id\022\026\n\006amount\030\002 \001(" +
      "\001R\006amount\022\034\n\toperation\030\003 \001(\tR\toperation\"" +
      "\327\001\n\014EntityEffect\022\033\n\teffect_id\030\001 \001(\tR\010eff" +
      "ectId\022\034\n\tamplifier\030\002 \001(\005R\tamplifier\022%\n\016d" +
      "uration_ticks\030\003 \001(\005R\rdurationTicks\022\030\n\007am" +
      "bient\030\004 \001(\010R\007ambient\022\030\n\007visible\030\005 \001(\010R\007v" +
      "isible\022\033\n\tshow_icon\030\006 \001(\010R\010showIcon\022\024\n\005b" +
      "lend\030\007 \001(\010R\005blend\"o\n\016PlayerListInfo\022\030\n\007a" +
      "ctions\030\001 \003(\tR\007actions\022C\n\006packet\030\002 \001(\0132+." +
      "mc_play_recorder.artifacts.v1.EncodedVal" +
      "ueR\006packet\"\261\001\n\017BlockEntityBlob\022\034\n\tdimens" +
      "ion\030\001 \001(\tR\tdimension\022\014\n\001x\030\002 \001(\005R\001x\022\014\n\001y\030" +
      "\003 \001(\005R\001y\022\014\n\001z\030\004 \001(\005R\001z\022\027\n\007type_id\030\005 \001(\tR" +
      "\006typeId\022=\n\003nbt\030\006 \001(\0132+.mc_play_recorder." +
      "artifacts.v1.EncodedValueR\003nbtBy\n\030dev.mi" +
      "nerec.artifacts.v1P\001Z[github.com/proj-ai" +
      "ri/mc-play-recorder/apis/sdk/go/mc-play-" +
      "recorder/artifacts/v1;artifactsv1b\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          dev.minerec.artifacts.v1.Common.getDescriptor(),
          dev.minerec.artifacts.v1.Events.getDescriptor(),
        });
    internal_static_mc_play_recorder_artifacts_v1_SceneExtractionJob_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_mc_play_recorder_artifacts_v1_SceneExtractionJob_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_mc_play_recorder_artifacts_v1_SceneExtractionJob_descriptor,
        new java.lang.String[] { "JobId", "SessionId", "PlayerUuid", "ConnectionId", "Ticks", "Scope", "MetadataPolicy", "FlashbackCaptureContract", "SourceReplays", "SubjectPoses", "SourceEvents", "OutputPath", "StopWhenDone", });
    internal_static_mc_play_recorder_artifacts_v1_SceneSourceReplay_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_mc_play_recorder_artifacts_v1_SceneSourceReplay_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_mc_play_recorder_artifacts_v1_SceneSourceReplay_descriptor,
        new java.lang.String[] { "SegmentId", "SegmentOrdinal", "Path", "Sha256", "SizeBytes", "Format", });
    internal_static_mc_play_recorder_artifacts_v1_SubjectPose_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_mc_play_recorder_artifacts_v1_SubjectPose_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_mc_play_recorder_artifacts_v1_SubjectPose_descriptor,
        new java.lang.String[] { "ServerTick", "SessionId", "PlayerUuid", "ConnectionId", "EntityId", "Dimension", "Position", "Velocity", "Rotation", "OnGround", });
    internal_static_mc_play_recorder_artifacts_v1_SceneExtractionResult_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_mc_play_recorder_artifacts_v1_SceneExtractionResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_mc_play_recorder_artifacts_v1_SceneExtractionResult_descriptor,
        new java.lang.String[] { "Status", "Error", "JobId", "SessionId", "PlayerUuid", "ConnectionId", "Ticks", "Scope", "MetadataPolicy", "SourceReplays", "Stream", "IgnoredPacketCounts", "CoveredTickCount", });
    internal_static_mc_play_recorder_artifacts_v1_SceneExtractionResult_IgnoredPacketCountsEntry_descriptor =
      internal_static_mc_play_recorder_artifacts_v1_SceneExtractionResult_descriptor.getNestedType(0);
    internal_static_mc_play_recorder_artifacts_v1_SceneExtractionResult_IgnoredPacketCountsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_mc_play_recorder_artifacts_v1_SceneExtractionResult_IgnoredPacketCountsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_mc_play_recorder_artifacts_v1_SceneStreamResult_descriptor =
      getDescriptor().getMessageType(4);
    internal_static_mc_play_recorder_artifacts_v1_SceneStreamResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_mc_play_recorder_artifacts_v1_SceneStreamResult_descriptor,
        new java.lang.String[] { "Path", "Frames", "Changes", "BlobsDirectory", "FrameCount", "ChangeCount", "BlobCount", "BlobBytes", "FramesSha256", "FramesSizeBytes", "ChangesSha256", "ChangesSizeBytes", });
    internal_static_mc_play_recorder_artifacts_v1_SceneFrameRecord_descriptor =
      getDescriptor().getMessageType(5);
    internal_static_mc_play_recorder_artifacts_v1_SceneFrameRecord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_mc_play_recorder_artifacts_v1_SceneFrameRecord_descriptor,
        new java.lang.String[] { "ServerTick", "FrameId", "ReplayTick", "Dimension", "SubjectPosition", "CoverageComplete", "SegmentId", "SegmentOrdinal", "EventSequence", "EntityCount", "LoadedSectionCount", "MetadataPolicy", "SceneSnapshotSha256", "Scope", "SubjectEntityId", "IncompleteReasons", });
    internal_static_mc_play_recorder_artifacts_v1_SceneChangeRecord_descriptor =
      getDescriptor().getMessageType(6);
    internal_static_mc_play_recorder_artifacts_v1_SceneChangeRecord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_mc_play_recorder_artifacts_v1_SceneChangeRecord_descriptor,
        new java.lang.String[] { "Sequence", "ServerTick", "ReplayTick", "SegmentId", "SegmentOrdinal", "SegmentBegin", "SectionSet", "SectionUnload", "EntitySet", "EntityRemove", "BlockEntitySet", "BlockEntityRemove", "Change", });
    internal_static_mc_play_recorder_artifacts_v1_SegmentBegin_descriptor =
      getDescriptor().getMessageType(7);
    internal_static_mc_play_recorder_artifacts_v1_SegmentBegin_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_mc_play_recorder_artifacts_v1_SegmentBegin_descriptor,
        new java.lang.String[] { "Sha256", "SizeBytes", });
    internal_static_mc_play_recorder_artifacts_v1_SectionChange_descriptor =
      getDescriptor().getMessageType(8);
    internal_static_mc_play_recorder_artifacts_v1_SectionChange_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_mc_play_recorder_artifacts_v1_SectionChange_descriptor,
        new java.lang.String[] { "Dimension", "X", "Y", "Z", "BlobSha256", });
    internal_static_mc_play_recorder_artifacts_v1_EntityChange_descriptor =
      getDescriptor().getMessageType(9);
    internal_static_mc_play_recorder_artifacts_v1_EntityChange_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_mc_play_recorder_artifacts_v1_EntityChange_descriptor,
        new java.lang.String[] { "InstanceId", "BlobSha256", });
    internal_static_mc_play_recorder_artifacts_v1_BlockEntityChange_descriptor =
      getDescriptor().getMessageType(10);
    internal_static_mc_play_recorder_artifacts_v1_BlockEntityChange_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_mc_play_recorder_artifacts_v1_BlockEntityChange_descriptor,
        new java.lang.String[] { "Dimension", "X", "Y", "Z", "BlobSha256", });
    internal_static_mc_play_recorder_artifacts_v1_SceneBlobPayload_descriptor =
      getDescriptor().getMessageType(11);
    internal_static_mc_play_recorder_artifacts_v1_SceneBlobPayload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_mc_play_recorder_artifacts_v1_SceneBlobPayload_descriptor,
        new java.lang.String[] { "Section", "Entity", "BlockEntity", "Frame", "PlayerState", "Value", });
    internal_static_mc_play_recorder_artifacts_v1_SectionBlob_descriptor =
      getDescriptor().getMessageType(12);
    internal_static_mc_play_recorder_artifacts_v1_SectionBlob_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_mc_play_recorder_artifacts_v1_SectionBlob_descriptor,
        new java.lang.String[] { "Palette", "IndicesLeU16", });
    internal_static_mc_play_recorder_artifacts_v1_BlockState_descriptor =
      getDescriptor().getMessageType(13);
    internal_static_mc_play_recorder_artifacts_v1_BlockState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_mc_play_recorder_artifacts_v1_BlockState_descriptor,
        new java.lang.String[] { "Name", "Properties", });
    internal_static_mc_play_recorder_artifacts_v1_BlockState_PropertiesEntry_descriptor =
      internal_static_mc_play_recorder_artifacts_v1_BlockState_descriptor.getNestedType(0);
    internal_static_mc_play_recorder_artifacts_v1_BlockState_PropertiesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_mc_play_recorder_artifacts_v1_BlockState_PropertiesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_mc_play_recorder_artifacts_v1_EncodedValue_descriptor =
      getDescriptor().getMessageType(14);
    internal_static_mc_play_recorder_artifacts_v1_EncodedValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_mc_play_recorder_artifacts_v1_EncodedValue_descriptor,
        new java.lang.String[] { "LogicalType", "CodecId", "Encoding", "Data", });
    internal_static_mc_play_recorder_artifacts_v1_EntityBlob_descriptor =
      getDescriptor().getMessageType(15);
    internal_static_mc_play_recorder_artifacts_v1_EntityBlob_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_mc_play_recorder_artifacts_v1_EntityBlob_descriptor,
        new java.lang.String[] { "Bounds", "Dimension", "NetworkId", "Uuid", "TypeId", "Position", "Velocity", "Rotation", "Width", "Height", "OnGround", "Subject", "SpawnData", "LeashDestinationNetworkId", "Passengers", "Metadata", "Equipment", "Attributes", "Effects", "PlayerInfo", });
    internal_static_mc_play_recorder_artifacts_v1_Bounds_descriptor =
      getDescriptor().getMessageType(16);
    internal_static_mc_play_recorder_artifacts_v1_Bounds_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_mc_play_recorder_artifacts_v1_Bounds_descriptor,
        new java.lang.String[] { "MinX", "MinY", "MinZ", "MaxX", "MaxY", "MaxZ", });
    internal_static_mc_play_recorder_artifacts_v1_EntityMetadata_descriptor =
      getDescriptor().getMessageType(17);
    internal_static_mc_play_recorder_artifacts_v1_EntityMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_mc_play_recorder_artifacts_v1_EntityMetadata_descriptor,
        new java.lang.String[] { "Index", "Value", });
    internal_static_mc_play_recorder_artifacts_v1_Equipment_descriptor =
      getDescriptor().getMessageType(18);
    internal_static_mc_play_recorder_artifacts_v1_Equipment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_mc_play_recorder_artifacts_v1_Equipment_descriptor,
        new java.lang.String[] { "Slot", "ItemId", "Count", "EncodedStack", });
    internal_static_mc_play_recorder_artifacts_v1_EntityAttribute_descriptor =
      getDescriptor().getMessageType(19);
    internal_static_mc_play_recorder_artifacts_v1_EntityAttribute_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_mc_play_recorder_artifacts_v1_EntityAttribute_descriptor,
        new java.lang.String[] { "AttributeId", "Base", "Modifiers", });
    internal_static_mc_play_recorder_artifacts_v1_AttributeModifier_descriptor =
      getDescriptor().getMessageType(20);
    internal_static_mc_play_recorder_artifacts_v1_AttributeModifier_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_mc_play_recorder_artifacts_v1_AttributeModifier_descriptor,
        new java.lang.String[] { "Id", "Amount", "Operation", });
    internal_static_mc_play_recorder_artifacts_v1_EntityEffect_descriptor =
      getDescriptor().getMessageType(21);
    internal_static_mc_play_recorder_artifacts_v1_EntityEffect_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_mc_play_recorder_artifacts_v1_EntityEffect_descriptor,
        new java.lang.String[] { "EffectId", "Amplifier", "DurationTicks", "Ambient", "Visible", "ShowIcon", "Blend", });
    internal_static_mc_play_recorder_artifacts_v1_PlayerListInfo_descriptor =
      getDescriptor().getMessageType(22);
    internal_static_mc_play_recorder_artifacts_v1_PlayerListInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_mc_play_recorder_artifacts_v1_PlayerListInfo_descriptor,
        new java.lang.String[] { "Actions", "Packet", });
    internal_static_mc_play_recorder_artifacts_v1_BlockEntityBlob_descriptor =
      getDescriptor().getMessageType(23);
    internal_static_mc_play_recorder_artifacts_v1_BlockEntityBlob_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_mc_play_recorder_artifacts_v1_BlockEntityBlob_descriptor,
        new java.lang.String[] { "Dimension", "X", "Y", "Z", "TypeId", "Nbt", });
    descriptor.resolveAllFeaturesImmutable();
    dev.minerec.artifacts.v1.Common.getDescriptor();
    dev.minerec.artifacts.v1.Events.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
