// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mc-play-recorder/artifacts/v1/scene.proto
// Protobuf Java Version: 4.33.2

package dev.minerec.artifacts.v1;

@com.google.protobuf.Generated
public interface SourceReplayOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mc_play_recorder.artifacts.v1.SourceReplay)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string segment_id = 1 [json_name = "segmentId"];</code>
   * @return The segmentId.
   */
  java.lang.String getSegmentId();
  /**
   * <code>string segment_id = 1 [json_name = "segmentId"];</code>
   * @return The bytes for segmentId.
   */
  com.google.protobuf.ByteString
      getSegmentIdBytes();

  /**
   * <code>uint32 segment_ordinal = 2 [json_name = "segmentOrdinal"];</code>
   * @return The segmentOrdinal.
   */
  int getSegmentOrdinal();

  /**
   * <code>string format = 3 [json_name = "format"];</code>
   * @return The format.
   */
  java.lang.String getFormat();
  /**
   * <code>string format = 3 [json_name = "format"];</code>
   * @return The bytes for format.
   */
  com.google.protobuf.ByteString
      getFormatBytes();

  /**
   * <code>.mc_play_recorder.artifacts.v1.ArtifactFile file = 4 [json_name = "file"];</code>
   * @return Whether the file field is set.
   */
  boolean hasFile();
  /**
   * <code>.mc_play_recorder.artifacts.v1.ArtifactFile file = 4 [json_name = "file"];</code>
   * @return The file.
   */
  dev.minerec.artifacts.v1.ArtifactFile getFile();
  /**
   * <code>.mc_play_recorder.artifacts.v1.ArtifactFile file = 4 [json_name = "file"];</code>
   */
  dev.minerec.artifacts.v1.ArtifactFileOrBuilder getFileOrBuilder();
}
