// Code generated by ent, DO NOT EDIT.

package blob

import (
	"entgo.io/ent/dialect/sql"
	"github.com/proj-airi/mc-play-recorder/databases/minerec-scene/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Blob {
	return predicate.Blob(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Blob {
	return predicate.Blob(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Blob {
	return predicate.Blob(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Blob {
	return predicate.Blob(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Blob {
	return predicate.Blob(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Blob {
	return predicate.Blob(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Blob {
	return predicate.Blob(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Blob {
	return predicate.Blob(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Blob {
	return predicate.Blob(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Blob {
	return predicate.Blob(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Blob {
	return predicate.Blob(sql.FieldContainsFold(FieldID, id))
}

// Kind applies equality check predicate on the "kind" field. It's identical to KindEQ.
func Kind(v string) predicate.Blob {
	return predicate.Blob(sql.FieldEQ(FieldKind, v))
}

// Encoding applies equality check predicate on the "encoding" field. It's identical to EncodingEQ.
func Encoding(v string) predicate.Blob {
	return predicate.Blob(sql.FieldEQ(FieldEncoding, v))
}

// UncompressedSize applies equality check predicate on the "uncompressed_size" field. It's identical to UncompressedSizeEQ.
func UncompressedSize(v int64) predicate.Blob {
	return predicate.Blob(sql.FieldEQ(FieldUncompressedSize, v))
}

// CompressedSize applies equality check predicate on the "compressed_size" field. It's identical to CompressedSizeEQ.
func CompressedSize(v int64) predicate.Blob {
	return predicate.Blob(sql.FieldEQ(FieldCompressedSize, v))
}

// Data applies equality check predicate on the "data" field. It's identical to DataEQ.
func Data(v []byte) predicate.Blob {
	return predicate.Blob(sql.FieldEQ(FieldData, v))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v string) predicate.Blob {
	return predicate.Blob(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v string) predicate.Blob {
	return predicate.Blob(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...string) predicate.Blob {
	return predicate.Blob(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...string) predicate.Blob {
	return predicate.Blob(sql.FieldNotIn(FieldKind, vs...))
}

// KindGT applies the GT predicate on the "kind" field.
func KindGT(v string) predicate.Blob {
	return predicate.Blob(sql.FieldGT(FieldKind, v))
}

// KindGTE applies the GTE predicate on the "kind" field.
func KindGTE(v string) predicate.Blob {
	return predicate.Blob(sql.FieldGTE(FieldKind, v))
}

// KindLT applies the LT predicate on the "kind" field.
func KindLT(v string) predicate.Blob {
	return predicate.Blob(sql.FieldLT(FieldKind, v))
}

// KindLTE applies the LTE predicate on the "kind" field.
func KindLTE(v string) predicate.Blob {
	return predicate.Blob(sql.FieldLTE(FieldKind, v))
}

// KindContains applies the Contains predicate on the "kind" field.
func KindContains(v string) predicate.Blob {
	return predicate.Blob(sql.FieldContains(FieldKind, v))
}

// KindHasPrefix applies the HasPrefix predicate on the "kind" field.
func KindHasPrefix(v string) predicate.Blob {
	return predicate.Blob(sql.FieldHasPrefix(FieldKind, v))
}

// KindHasSuffix applies the HasSuffix predicate on the "kind" field.
func KindHasSuffix(v string) predicate.Blob {
	return predicate.Blob(sql.FieldHasSuffix(FieldKind, v))
}

// KindEqualFold applies the EqualFold predicate on the "kind" field.
func KindEqualFold(v string) predicate.Blob {
	return predicate.Blob(sql.FieldEqualFold(FieldKind, v))
}

// KindContainsFold applies the ContainsFold predicate on the "kind" field.
func KindContainsFold(v string) predicate.Blob {
	return predicate.Blob(sql.FieldContainsFold(FieldKind, v))
}

// EncodingEQ applies the EQ predicate on the "encoding" field.
func EncodingEQ(v string) predicate.Blob {
	return predicate.Blob(sql.FieldEQ(FieldEncoding, v))
}

// EncodingNEQ applies the NEQ predicate on the "encoding" field.
func EncodingNEQ(v string) predicate.Blob {
	return predicate.Blob(sql.FieldNEQ(FieldEncoding, v))
}

// EncodingIn applies the In predicate on the "encoding" field.
func EncodingIn(vs ...string) predicate.Blob {
	return predicate.Blob(sql.FieldIn(FieldEncoding, vs...))
}

// EncodingNotIn applies the NotIn predicate on the "encoding" field.
func EncodingNotIn(vs ...string) predicate.Blob {
	return predicate.Blob(sql.FieldNotIn(FieldEncoding, vs...))
}

// EncodingGT applies the GT predicate on the "encoding" field.
func EncodingGT(v string) predicate.Blob {
	return predicate.Blob(sql.FieldGT(FieldEncoding, v))
}

// EncodingGTE applies the GTE predicate on the "encoding" field.
func EncodingGTE(v string) predicate.Blob {
	return predicate.Blob(sql.FieldGTE(FieldEncoding, v))
}

// EncodingLT applies the LT predicate on the "encoding" field.
func EncodingLT(v string) predicate.Blob {
	return predicate.Blob(sql.FieldLT(FieldEncoding, v))
}

// EncodingLTE applies the LTE predicate on the "encoding" field.
func EncodingLTE(v string) predicate.Blob {
	return predicate.Blob(sql.FieldLTE(FieldEncoding, v))
}

// EncodingContains applies the Contains predicate on the "encoding" field.
func EncodingContains(v string) predicate.Blob {
	return predicate.Blob(sql.FieldContains(FieldEncoding, v))
}

// EncodingHasPrefix applies the HasPrefix predicate on the "encoding" field.
func EncodingHasPrefix(v string) predicate.Blob {
	return predicate.Blob(sql.FieldHasPrefix(FieldEncoding, v))
}

// EncodingHasSuffix applies the HasSuffix predicate on the "encoding" field.
func EncodingHasSuffix(v string) predicate.Blob {
	return predicate.Blob(sql.FieldHasSuffix(FieldEncoding, v))
}

// EncodingEqualFold applies the EqualFold predicate on the "encoding" field.
func EncodingEqualFold(v string) predicate.Blob {
	return predicate.Blob(sql.FieldEqualFold(FieldEncoding, v))
}

// EncodingContainsFold applies the ContainsFold predicate on the "encoding" field.
func EncodingContainsFold(v string) predicate.Blob {
	return predicate.Blob(sql.FieldContainsFold(FieldEncoding, v))
}

// UncompressedSizeEQ applies the EQ predicate on the "uncompressed_size" field.
func UncompressedSizeEQ(v int64) predicate.Blob {
	return predicate.Blob(sql.FieldEQ(FieldUncompressedSize, v))
}

// UncompressedSizeNEQ applies the NEQ predicate on the "uncompressed_size" field.
func UncompressedSizeNEQ(v int64) predicate.Blob {
	return predicate.Blob(sql.FieldNEQ(FieldUncompressedSize, v))
}

// UncompressedSizeIn applies the In predicate on the "uncompressed_size" field.
func UncompressedSizeIn(vs ...int64) predicate.Blob {
	return predicate.Blob(sql.FieldIn(FieldUncompressedSize, vs...))
}

// UncompressedSizeNotIn applies the NotIn predicate on the "uncompressed_size" field.
func UncompressedSizeNotIn(vs ...int64) predicate.Blob {
	return predicate.Blob(sql.FieldNotIn(FieldUncompressedSize, vs...))
}

// UncompressedSizeGT applies the GT predicate on the "uncompressed_size" field.
func UncompressedSizeGT(v int64) predicate.Blob {
	return predicate.Blob(sql.FieldGT(FieldUncompressedSize, v))
}

// UncompressedSizeGTE applies the GTE predicate on the "uncompressed_size" field.
func UncompressedSizeGTE(v int64) predicate.Blob {
	return predicate.Blob(sql.FieldGTE(FieldUncompressedSize, v))
}

// UncompressedSizeLT applies the LT predicate on the "uncompressed_size" field.
func UncompressedSizeLT(v int64) predicate.Blob {
	return predicate.Blob(sql.FieldLT(FieldUncompressedSize, v))
}

// UncompressedSizeLTE applies the LTE predicate on the "uncompressed_size" field.
func UncompressedSizeLTE(v int64) predicate.Blob {
	return predicate.Blob(sql.FieldLTE(FieldUncompressedSize, v))
}

// CompressedSizeEQ applies the EQ predicate on the "compressed_size" field.
func CompressedSizeEQ(v int64) predicate.Blob {
	return predicate.Blob(sql.FieldEQ(FieldCompressedSize, v))
}

// CompressedSizeNEQ applies the NEQ predicate on the "compressed_size" field.
func CompressedSizeNEQ(v int64) predicate.Blob {
	return predicate.Blob(sql.FieldNEQ(FieldCompressedSize, v))
}

// CompressedSizeIn applies the In predicate on the "compressed_size" field.
func CompressedSizeIn(vs ...int64) predicate.Blob {
	return predicate.Blob(sql.FieldIn(FieldCompressedSize, vs...))
}

// CompressedSizeNotIn applies the NotIn predicate on the "compressed_size" field.
func CompressedSizeNotIn(vs ...int64) predicate.Blob {
	return predicate.Blob(sql.FieldNotIn(FieldCompressedSize, vs...))
}

// CompressedSizeGT applies the GT predicate on the "compressed_size" field.
func CompressedSizeGT(v int64) predicate.Blob {
	return predicate.Blob(sql.FieldGT(FieldCompressedSize, v))
}

// CompressedSizeGTE applies the GTE predicate on the "compressed_size" field.
func CompressedSizeGTE(v int64) predicate.Blob {
	return predicate.Blob(sql.FieldGTE(FieldCompressedSize, v))
}

// CompressedSizeLT applies the LT predicate on the "compressed_size" field.
func CompressedSizeLT(v int64) predicate.Blob {
	return predicate.Blob(sql.FieldLT(FieldCompressedSize, v))
}

// CompressedSizeLTE applies the LTE predicate on the "compressed_size" field.
func CompressedSizeLTE(v int64) predicate.Blob {
	return predicate.Blob(sql.FieldLTE(FieldCompressedSize, v))
}

// DataEQ applies the EQ predicate on the "data" field.
func DataEQ(v []byte) predicate.Blob {
	return predicate.Blob(sql.FieldEQ(FieldData, v))
}

// DataNEQ applies the NEQ predicate on the "data" field.
func DataNEQ(v []byte) predicate.Blob {
	return predicate.Blob(sql.FieldNEQ(FieldData, v))
}

// DataIn applies the In predicate on the "data" field.
func DataIn(vs ...[]byte) predicate.Blob {
	return predicate.Blob(sql.FieldIn(FieldData, vs...))
}

// DataNotIn applies the NotIn predicate on the "data" field.
func DataNotIn(vs ...[]byte) predicate.Blob {
	return predicate.Blob(sql.FieldNotIn(FieldData, vs...))
}

// DataGT applies the GT predicate on the "data" field.
func DataGT(v []byte) predicate.Blob {
	return predicate.Blob(sql.FieldGT(FieldData, v))
}

// DataGTE applies the GTE predicate on the "data" field.
func DataGTE(v []byte) predicate.Blob {
	return predicate.Blob(sql.FieldGTE(FieldData, v))
}

// DataLT applies the LT predicate on the "data" field.
func DataLT(v []byte) predicate.Blob {
	return predicate.Blob(sql.FieldLT(FieldData, v))
}

// DataLTE applies the LTE predicate on the "data" field.
func DataLTE(v []byte) predicate.Blob {
	return predicate.Blob(sql.FieldLTE(FieldData, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Blob) predicate.Blob {
	return predicate.Blob(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Blob) predicate.Blob {
	return predicate.Blob(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Blob) predicate.Blob {
	return predicate.Blob(sql.NotPredicates(p))
}
