// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type GoogleProtobufAny = {
    '@type'?: string;
    [key: string]: unknown;
};

export type GoogleRpcStatus = {
    code?: number;
    details?: Array<GoogleProtobufAny>;
    message?: string;
};

/**
 * AlignmentParticipant is one Play named in a session alignment header.
 */
export type RecorderMinecraftApiV1AlignmentParticipant = {
    connectionId?: string;
    endServerTick?: string;
    /**
     * True when the alignment was given the Play's perception.jsonl.
     */
    perceptionProvided?: boolean;
    playerName?: string;
    playerUuid?: string;
    /**
     * Connection start and end server tick.
     */
    startServerTick?: string;
};

export type RecorderMinecraftApiV1GetReplayResponse = {
    replay?: RecorderMinecraftApiV1Replay;
};

export type RecorderMinecraftApiV1GetWorldSessionResponse = {
    worldSession?: RecorderMinecraftApiV1WorldSession;
};

export type RecorderMinecraftApiV1ListArtifactsResponse = {
    serverInstances?: Array<RecorderMinecraftApiV1ServerInstance>;
};

export type RecorderMinecraftApiV1ListPlayersResponse = {
    players?: Array<RecorderMinecraftApiV1PlayerSummary>;
};

export type RecorderMinecraftApiV1ListReplaysResponse = {
    replays?: Array<RecorderMinecraftApiV1Replay>;
};

export type RecorderMinecraftApiV1ListServerInstancesResponse = {
    serverInstances?: Array<RecorderMinecraftApiV1ServerInstanceSummary>;
};

export type RecorderMinecraftApiV1ListWorldSessionsResponse = {
    worldSessions?: Array<RecorderMinecraftApiV1WorldSession>;
};

/**
 * PlayExtension describes optional producer-owned data attached to one Play.
 */
export type RecorderMinecraftApiV1PlayExtension = {
    assets?: Array<RecorderMinecraftApiV1PlayExtensionAsset>;
    extensionType?: string;
};

/**
 * PlayExtensionAsset is one browser-readable extension asset. Role and schema
 * are interpreted by the dashboard module for the extension type.
 */
export type RecorderMinecraftApiV1PlayExtensionAsset = {
    mediaType?: string;
    role?: string;
    schema?: string;
    url?: string;
};

export type RecorderMinecraftApiV1Player = {
    name?: string;
    replays?: Array<RecorderMinecraftApiV1Replay>;
    uuid?: string;
};

export type RecorderMinecraftApiV1PlayerSummary = {
    name?: string;
    replayCount?: string;
    serverInstanceId?: string;
    serverName?: string;
    uuid?: string;
};

export type RecorderMinecraftApiV1RefreshCatalogResponse = {
    refreshedAt?: string;
    replayCount?: string;
    serverInstanceCount?: string;
    worldSessionCount?: string;
};

export type RecorderMinecraftApiV1Replay = {
    actionsUrl?: string;
    captureFailure?: string;
    connectionId?: string;
    endServerTick?: string;
    endedAt?: string;
    eventsUrl?: string;
    extensions?: Array<RecorderMinecraftApiV1PlayExtension>;
    /**
     * renders/fpv_frames/frames.jsonl: the frame to server tick index of a render.
     */
    framesIndexUrl?: string;
    /**
     * Derived files under the Play directory. Each URL is present only when the
     * file exists as a regular file.
     */
    perceptionUrl?: string;
    playerName?: string;
    playerUuid?: string;
    replayFormat?: string;
    replayUrl?: string;
    sceneUrl?: string;
    serverInstanceId?: string;
    serverName?: string;
    sessionId?: string;
    startServerTick?: string;
    startedAt?: string;
    summary?: RecorderMinecraftCatalogV1PlaySummary;
    terminalReason?: string;
    validationError?: string;
    video?: RecorderMinecraftApiV1VideoAsset;
    /**
     * WorldSession.id of the world session that covers this Play, when one is
     * readable in the same server instance.
     */
    worldSessionId?: string;
    worldSessionLink?: RecorderMinecraftApiV1WorldSessionLink;
};

export type RecorderMinecraftApiV1ServerInstance = {
    instanceId?: string;
    name?: string;
    players?: Array<RecorderMinecraftApiV1Player>;
    /**
     * World sessions are listed in full; player and time filters do not apply to them.
     */
    worldSessions?: Array<RecorderMinecraftApiV1WorldSession>;
};

export type RecorderMinecraftApiV1ServerInstanceSummary = {
    instanceId?: string;
    name?: string;
    playerCount?: string;
    replayCount?: string;
    worldSessionCount?: string;
};

export type RecorderMinecraftApiV1VideoAsset = {
    durationSeconds?: number;
    frameCount?: string;
    framesPerSecond?: number;
    height?: number;
    mediaType?: string;
    sizeBytes?: string;
    timing?: RecorderMinecraftApiV1VideoTiming;
    url?: string;
    width?: number;
};

/**
 * VideoTiming locates the file that maps video time to server ticks.
 */
export type RecorderMinecraftApiV1VideoTiming = {
    anchorCount?: string;
    /**
     * False when the producer reported a truncated video or index.
     */
    complete?: boolean;
    /**
     * Server ticks of the first and last anchor or frame.
     */
    firstServerTick?: string;
    format?: RecorderMinecraftApiV1VideoTimingFormat;
    lastServerTick?: string;
    url?: string;
};

/**
 *  - FORMAT_FPV_MANIFEST: renders/fpv.json, FpvVideoManifest ProtoJSON. Its frames are sampled
 * {server_tick, video_seconds} anchors. For a server tick T, seek to the
 * video_seconds of the last anchor with server_tick <= T.
 * - FORMAT_RENDER_FRAME_INDEX: renders/fpv_frames/frames.jsonl, RenderFrameIndex ProtoJSON lines with
 * one line per video frame. Frame ordinal N (from 1) starts at
 * (N - 1) / frames_per_second.
 */
export type RecorderMinecraftApiV1VideoTimingFormat = 'FORMAT_UNSPECIFIED' | 'FORMAT_FPV_MANIFEST' | 'FORMAT_RENDER_FRAME_INDEX';

/**
 * WorldSession is one directory under world/sessions/ of a server instance.
 */
export type RecorderMinecraftApiV1WorldSession = {
    /**
     * JSONL files in alignments/, sorted by name.
     */
    alignments?: Array<RecorderMinecraftApiV1WorldSessionAlignment>;
    /**
     * Absent while recording or after a crash.
     */
    endServerTick?: string;
    endedAt?: string;
    eventsUrl?: string;
    /**
     * Directory name, <started-at>--<session-id>. Unique within a server instance.
     */
    id?: string;
    knownGaps?: Array<string>;
    metadataUrl?: string;
    /**
     * Plays in the same server instance that link to this world session.
     */
    plays?: Array<RecorderMinecraftApiV1WorldSessionPlay>;
    serverInstanceId?: string;
    serverName?: string;
    sessionId?: string;
    startServerTick?: string;
    startedAt?: string;
    /**
     * Set when the world stream stopped early; coverage ends at end_server_tick.
     */
    streamFailure?: string;
    terminalReason?: string;
    /**
     * Set when metadata.json is missing, invalid, or describes an open stream.
     */
    validationError?: string;
};

/**
 * WorldSessionAlignment is one session alignment JSONL under alignments/.
 */
export type RecorderMinecraftApiV1WorldSessionAlignment = {
    divergenceCount?: string;
    eventCount?: string;
    /**
     * File name without the .jsonl suffix.
     */
    name?: string;
    /**
     * From the header line.
     */
    participants?: Array<RecorderMinecraftApiV1AlignmentParticipant>;
    sizeBytes?: string;
    url?: string;
    /**
     * Set when the header line cannot be read or names another session.
     */
    validationError?: string;
};

/**
 * WorldSessionLink tells how a Play was joined to its world session.
 *
 * - WORLD_SESSION_LINK_CONTAINER_TRUTH: Play metadata names the world session in world_container_truth.
 * - WORLD_SESSION_LINK_SESSION_ID: Play metadata has no world_container_truth (the stream was not healthy at
 * connection start); the world session has the same session_id.
 */
export type RecorderMinecraftApiV1WorldSessionLink = 'WORLD_SESSION_LINK_UNSPECIFIED' | 'WORLD_SESSION_LINK_CONTAINER_TRUTH' | 'WORLD_SESSION_LINK_SESSION_ID';

/**
 * WorldSessionPlay identifies one Play linked to a world session.
 */
export type RecorderMinecraftApiV1WorldSessionPlay = {
    connectionId?: string;
    link?: RecorderMinecraftApiV1WorldSessionLink;
    playerName?: string;
    playerUuid?: string;
};

export type RecorderMinecraftCatalogV1FinalInventoryItem = {
    count?: number;
    damage?: number;
    /**
     * Namespaced Minecraft item identifier.
     */
    itemId?: string;
    maxDamage?: number;
    /**
     * Player inventory slot number.
     */
    slot?: number;
};

/**
 * PlaySummary is a transient read-only projection of completed Play inputs.
 */
export type RecorderMinecraftCatalogV1PlaySummary = {
    /**
     * Inclusive Server tick count from the metadata start tick through the end tick.
     */
    durationTicks?: string;
    /**
     * Slot-preserving inventory from the final Player state.
     */
    finalInventory?: Array<RecorderMinecraftCatalogV1FinalInventoryItem>;
    /**
     * Percentage from 0 through 100 of duration ticks without recorded player activity.
     */
    idlePercentage?: number;
    /**
     * Sum in blocks of three-dimensional displacement between successive same-dimension Player states.
     */
    observedPathDistanceBlocks?: number;
    /**
     * Number of Player state snapshots used by this summary.
     */
    playerStateCount?: string;
};

export type ArtifactsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Restrict results to one recorder installation UUID.
         */
        serverInstanceId?: string;
        /**
         * Restrict results to one Minecraft player UUID.
         */
        playerUuid?: string;
        /**
         * Include replays whose connection started at or after this instant.
         */
        startedAtOrAfter?: string;
        /**
         * Include replays whose connection started before this instant.
         */
        startedBefore?: string;
    };
    url: '/api/v1/artifacts';
};

export type ArtifactsListErrors = {
    /**
     * An unexpected error response.
     */
    default: GoogleRpcStatus;
};

export type ArtifactsListError = ArtifactsListErrors[keyof ArtifactsListErrors];

export type ArtifactsListResponses = {
    /**
     * A successful response.
     */
    200: RecorderMinecraftApiV1ListArtifactsResponse;
};

export type ArtifactsListResponse = ArtifactsListResponses[keyof ArtifactsListResponses];

export type CatalogRefreshData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/catalog:refresh';
};

export type CatalogRefreshErrors = {
    /**
     * An unexpected error response.
     */
    default: GoogleRpcStatus;
};

export type CatalogRefreshError = CatalogRefreshErrors[keyof CatalogRefreshErrors];

export type CatalogRefreshResponses = {
    /**
     * A successful response.
     */
    200: RecorderMinecraftApiV1RefreshCatalogResponse;
};

export type CatalogRefreshResponse = CatalogRefreshResponses[keyof CatalogRefreshResponses];

export type PlayersListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Restrict results to one recorder installation UUID.
         */
        serverInstanceId?: string;
    };
    url: '/api/v1/players';
};

export type PlayersListErrors = {
    /**
     * An unexpected error response.
     */
    default: GoogleRpcStatus;
};

export type PlayersListError = PlayersListErrors[keyof PlayersListErrors];

export type PlayersListResponses = {
    /**
     * A successful response.
     */
    200: RecorderMinecraftApiV1ListPlayersResponse;
};

export type PlayersListResponse = PlayersListResponses[keyof PlayersListResponses];

export type ReplaysListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Restrict results to one recorder installation UUID.
         */
        serverInstanceId?: string;
        /**
         * Restrict results to one Minecraft player UUID.
         */
        playerUuid?: string;
        /**
         * Include replays whose connection started at or after this instant.
         */
        startedAtOrAfter?: string;
        /**
         * Include replays whose connection started before this instant.
         */
        startedBefore?: string;
        /**
         * Calculate a transient summary for each completed Play after applying the filters.
         */
        includeSummary?: boolean;
    };
    url: '/api/v1/replays';
};

export type ReplaysListErrors = {
    /**
     * An unexpected error response.
     */
    default: GoogleRpcStatus;
};

export type ReplaysListError = ReplaysListErrors[keyof ReplaysListErrors];

export type ReplaysListResponses = {
    /**
     * A successful response.
     */
    200: RecorderMinecraftApiV1ListReplaysResponse;
};

export type ReplaysListResponse = ReplaysListResponses[keyof ReplaysListResponses];

export type ServerInstancesListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/server-instances';
};

export type ServerInstancesListErrors = {
    /**
     * An unexpected error response.
     */
    default: GoogleRpcStatus;
};

export type ServerInstancesListError = ServerInstancesListErrors[keyof ServerInstancesListErrors];

export type ServerInstancesListResponses = {
    /**
     * A successful response.
     */
    200: RecorderMinecraftApiV1ListServerInstancesResponse;
};

export type ServerInstancesListResponse = ServerInstancesListResponses[keyof ServerInstancesListResponses];

export type ReplaysGetData = {
    body?: never;
    path: {
        /**
         * Recorder installation UUID.
         */
        serverInstanceId: string;
        /**
         * Minecraft player UUID.
         */
        playerUuid: string;
        /**
         * Replay connection UUID.
         */
        connectionId: string;
    };
    query?: never;
    url: '/api/v1/server-instances/{serverInstanceId}/players/{playerUuid}/replays/{connectionId}';
};

export type ReplaysGetErrors = {
    /**
     * An unexpected error response.
     */
    default: GoogleRpcStatus;
};

export type ReplaysGetError = ReplaysGetErrors[keyof ReplaysGetErrors];

export type ReplaysGetResponses = {
    /**
     * A successful response.
     */
    200: RecorderMinecraftApiV1GetReplayResponse;
};

export type ReplaysGetResponse = ReplaysGetResponses[keyof ReplaysGetResponses];

export type WorldSessionsGetData = {
    body?: never;
    path: {
        /**
         * Recorder installation UUID.
         */
        serverInstanceId: string;
        /**
         * World session directory name, <started-at>--<session-id>.
         */
        worldSessionId: string;
    };
    query?: never;
    url: '/api/v1/server-instances/{serverInstanceId}/world-sessions/{worldSessionId}';
};

export type WorldSessionsGetErrors = {
    /**
     * An unexpected error response.
     */
    default: GoogleRpcStatus;
};

export type WorldSessionsGetError = WorldSessionsGetErrors[keyof WorldSessionsGetErrors];

export type WorldSessionsGetResponses = {
    /**
     * A successful response.
     */
    200: RecorderMinecraftApiV1GetWorldSessionResponse;
};

export type WorldSessionsGetResponse = WorldSessionsGetResponses[keyof WorldSessionsGetResponses];

export type WorldSessionsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Restrict results to one recorder installation UUID.
         */
        serverInstanceId?: string;
        /**
         * Restrict results to one recorder session_id.
         */
        sessionId?: string;
    };
    url: '/api/v1/world-sessions';
};

export type WorldSessionsListErrors = {
    /**
     * An unexpected error response.
     */
    default: GoogleRpcStatus;
};

export type WorldSessionsListError = WorldSessionsListErrors[keyof WorldSessionsListErrors];

export type WorldSessionsListResponses = {
    /**
     * A successful response.
     */
    200: RecorderMinecraftApiV1ListWorldSessionsResponse;
};

export type WorldSessionsListResponse = WorldSessionsListResponses[keyof WorldSessionsListResponses];
