// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: recorder-minecraft/artifacts/v1/events.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package dev.recorderminecraft.artifacts.v1;

@kotlin.jvm.JvmName("-initializecaptureEvent")
public inline fun captureEvent(block: dev.recorderminecraft.artifacts.v1.CaptureEventKt.Dsl.() -> kotlin.Unit): dev.recorderminecraft.artifacts.v1.CaptureEvent =
  dev.recorderminecraft.artifacts.v1.CaptureEventKt.Dsl._create(dev.recorderminecraft.artifacts.v1.CaptureEvent.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `recorder_minecraft.artifacts.v1.CaptureEvent`
 */
public object CaptureEventKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: dev.recorderminecraft.artifacts.v1.CaptureEvent.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: dev.recorderminecraft.artifacts.v1.CaptureEvent.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): dev.recorderminecraft.artifacts.v1.CaptureEvent = _builder.build()

    /**
     * `.recorder_minecraft.artifacts.v1.EventIdentity identity = 1 [json_name = "identity"];`
     */
    public var identity: dev.recorderminecraft.artifacts.v1.EventIdentity
      @kotlin.jvm.JvmName("getIdentity")
        get() = _builder.identity
      @kotlin.jvm.JvmName("setIdentity")
        set(value) {
        _builder.identity = value
      }
    /**
     * `.recorder_minecraft.artifacts.v1.EventIdentity identity = 1 [json_name = "identity"];`
     */
    public fun clearIdentity() {
      _builder.clearIdentity()
    }
    /**
     * `.recorder_minecraft.artifacts.v1.EventIdentity identity = 1 [json_name = "identity"];`
     * @return Whether the identity field is set.
     */
    public fun hasIdentity(): kotlin.Boolean {
      return _builder.hasIdentity()
    }

    public val CaptureEventKt.Dsl.identityOrNull: dev.recorderminecraft.artifacts.v1.EventIdentity?
      get() = _builder.identityOrNull

    /**
     * `.recorder_minecraft.artifacts.v1.ControlStateEvent control_state = 20 [json_name = "controlState"];`
     */
    public var controlState: dev.recorderminecraft.artifacts.v1.ControlStateEvent
      @kotlin.jvm.JvmName("getControlState")
        get() = _builder.controlState
      @kotlin.jvm.JvmName("setControlState")
        set(value) {
        _builder.controlState = value
      }
    /**
     * `.recorder_minecraft.artifacts.v1.ControlStateEvent control_state = 20 [json_name = "controlState"];`
     */
    public fun clearControlState() {
      _builder.clearControlState()
    }
    /**
     * `.recorder_minecraft.artifacts.v1.ControlStateEvent control_state = 20 [json_name = "controlState"];`
     * @return Whether the controlState field is set.
     */
    public fun hasControlState(): kotlin.Boolean {
      return _builder.hasControlState()
    }

    /**
     * `.recorder_minecraft.artifacts.v1.PacketArrivalEvent packet_arrival = 21 [json_name = "packetArrival"];`
     */
    public var packetArrival: dev.recorderminecraft.artifacts.v1.PacketArrivalEvent
      @kotlin.jvm.JvmName("getPacketArrival")
        get() = _builder.packetArrival
      @kotlin.jvm.JvmName("setPacketArrival")
        set(value) {
        _builder.packetArrival = value
      }
    /**
     * `.recorder_minecraft.artifacts.v1.PacketArrivalEvent packet_arrival = 21 [json_name = "packetArrival"];`
     */
    public fun clearPacketArrival() {
      _builder.clearPacketArrival()
    }
    /**
     * `.recorder_minecraft.artifacts.v1.PacketArrivalEvent packet_arrival = 21 [json_name = "packetArrival"];`
     * @return Whether the packetArrival field is set.
     */
    public fun hasPacketArrival(): kotlin.Boolean {
      return _builder.hasPacketArrival()
    }

    /**
     * `.recorder_minecraft.artifacts.v1.PacketApplyEvent packet_apply = 22 [json_name = "packetApply"];`
     */
    public var packetApply: dev.recorderminecraft.artifacts.v1.PacketApplyEvent
      @kotlin.jvm.JvmName("getPacketApply")
        get() = _builder.packetApply
      @kotlin.jvm.JvmName("setPacketApply")
        set(value) {
        _builder.packetApply = value
      }
    /**
     * `.recorder_minecraft.artifacts.v1.PacketApplyEvent packet_apply = 22 [json_name = "packetApply"];`
     */
    public fun clearPacketApply() {
      _builder.clearPacketApply()
    }
    /**
     * `.recorder_minecraft.artifacts.v1.PacketApplyEvent packet_apply = 22 [json_name = "packetApply"];`
     * @return Whether the packetApply field is set.
     */
    public fun hasPacketApply(): kotlin.Boolean {
      return _builder.hasPacketApply()
    }

    /**
     * `.recorder_minecraft.artifacts.v1.PlayerStateEvent player_state = 23 [json_name = "playerState"];`
     */
    public var playerState: dev.recorderminecraft.artifacts.v1.PlayerStateEvent
      @kotlin.jvm.JvmName("getPlayerState")
        get() = _builder.playerState
      @kotlin.jvm.JvmName("setPlayerState")
        set(value) {
        _builder.playerState = value
      }
    /**
     * `.recorder_minecraft.artifacts.v1.PlayerStateEvent player_state = 23 [json_name = "playerState"];`
     */
    public fun clearPlayerState() {
      _builder.clearPlayerState()
    }
    /**
     * `.recorder_minecraft.artifacts.v1.PlayerStateEvent player_state = 23 [json_name = "playerState"];`
     * @return Whether the playerState field is set.
     */
    public fun hasPlayerState(): kotlin.Boolean {
      return _builder.hasPlayerState()
    }

    /**
     * `.recorder_minecraft.artifacts.v1.ReplayTimelineEvent replay_timeline = 24 [json_name = "replayTimeline"];`
     */
    public var replayTimeline: dev.recorderminecraft.artifacts.v1.ReplayTimelineEvent
      @kotlin.jvm.JvmName("getReplayTimeline")
        get() = _builder.replayTimeline
      @kotlin.jvm.JvmName("setReplayTimeline")
        set(value) {
        _builder.replayTimeline = value
      }
    /**
     * `.recorder_minecraft.artifacts.v1.ReplayTimelineEvent replay_timeline = 24 [json_name = "replayTimeline"];`
     */
    public fun clearReplayTimeline() {
      _builder.clearReplayTimeline()
    }
    /**
     * `.recorder_minecraft.artifacts.v1.ReplayTimelineEvent replay_timeline = 24 [json_name = "replayTimeline"];`
     * @return Whether the replayTimeline field is set.
     */
    public fun hasReplayTimeline(): kotlin.Boolean {
      return _builder.hasReplayTimeline()
    }
    public val recordCase: dev.recorderminecraft.artifacts.v1.CaptureEvent.RecordCase
    @kotlin.jvm.JvmName("getRecordCase")
      get() = _builder.getRecordCase()

    public fun clearRecord() {
      _builder.clearRecord()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun dev.recorderminecraft.artifacts.v1.CaptureEvent.copy(block: `dev.recorderminecraft.artifacts.v1`.CaptureEventKt.Dsl.() -> kotlin.Unit): dev.recorderminecraft.artifacts.v1.CaptureEvent =
  `dev.recorderminecraft.artifacts.v1`.CaptureEventKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val dev.recorderminecraft.artifacts.v1.CaptureEventOrBuilder.identityOrNull: dev.recorderminecraft.artifacts.v1.EventIdentity?
  get() = if (hasIdentity()) getIdentity() else null

public val dev.recorderminecraft.artifacts.v1.CaptureEventOrBuilder.controlStateOrNull: dev.recorderminecraft.artifacts.v1.ControlStateEvent?
  get() = if (hasControlState()) getControlState() else null

public val dev.recorderminecraft.artifacts.v1.CaptureEventOrBuilder.packetArrivalOrNull: dev.recorderminecraft.artifacts.v1.PacketArrivalEvent?
  get() = if (hasPacketArrival()) getPacketArrival() else null

public val dev.recorderminecraft.artifacts.v1.CaptureEventOrBuilder.packetApplyOrNull: dev.recorderminecraft.artifacts.v1.PacketApplyEvent?
  get() = if (hasPacketApply()) getPacketApply() else null

public val dev.recorderminecraft.artifacts.v1.CaptureEventOrBuilder.playerStateOrNull: dev.recorderminecraft.artifacts.v1.PlayerStateEvent?
  get() = if (hasPlayerState()) getPlayerState() else null

public val dev.recorderminecraft.artifacts.v1.CaptureEventOrBuilder.replayTimelineOrNull: dev.recorderminecraft.artifacts.v1.ReplayTimelineEvent?
  get() = if (hasReplayTimeline()) getReplayTimeline() else null

