// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: recorder-minecraft/artifacts/v1/events.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package dev.recorderminecraft.artifacts.v1;

@kotlin.jvm.JvmName("-initializeclientInformationEvent")
public inline fun clientInformationEvent(block: dev.recorderminecraft.artifacts.v1.ClientInformationEventKt.Dsl.() -> kotlin.Unit): dev.recorderminecraft.artifacts.v1.ClientInformationEvent =
  dev.recorderminecraft.artifacts.v1.ClientInformationEventKt.Dsl._create(dev.recorderminecraft.artifacts.v1.ClientInformationEvent.newBuilder()).apply { block() }._build()
/**
 * ```
 * Client-reported settings that bound what this actor can perceive.
 *
 * Scope is actor perception and provenance is captured: values are copied from
 * the server's view of the client, not inferred. FOV, GUI scale, and window
 * aspect are never reported to the server and are therefore absent.
 * ```
 *
 * Protobuf type `recorder_minecraft.artifacts.v1.ClientInformationEvent`
 */
public object ClientInformationEventKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: dev.recorderminecraft.artifacts.v1.ClientInformationEvent.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: dev.recorderminecraft.artifacts.v1.ClientInformationEvent.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): dev.recorderminecraft.artifacts.v1.ClientInformationEvent = _builder.build()

    /**
     * `.recorder_minecraft.artifacts.v1.ClientInformationSource source = 1 [json_name = "source"];`
     */
    public var source: dev.recorderminecraft.artifacts.v1.ClientInformationSource
      @kotlin.jvm.JvmName("getSource")
        get() = _builder.source
      @kotlin.jvm.JvmName("setSource")
        set(value) {
        _builder.source = value
      }
    public var sourceValue: kotlin.Int
      @kotlin.jvm.JvmName("getSourceValue")
        get() = _builder.sourceValue
      @kotlin.jvm.JvmName("setSourceValue")
        set(value) {
        _builder.sourceValue = value
      }
    /**
     * `.recorder_minecraft.artifacts.v1.ClientInformationSource source = 1 [json_name = "source"];`
     */
    public fun clearSource() {
      _builder.clearSource()
    }

    /**
     * `string language = 2 [json_name = "language"];`
     */
    public var language: kotlin.String
      @kotlin.jvm.JvmName("getLanguage")
        get() = _builder.language
      @kotlin.jvm.JvmName("setLanguage")
        set(value) {
        _builder.language = value
      }
    /**
     * `string language = 2 [json_name = "language"];`
     */
    public fun clearLanguage() {
      _builder.clearLanguage()
    }

    /**
     * ```
     * Client render distance in chunks before the server clamps it to its own limit.
     * ```
     *
     * `int32 view_distance = 3 [json_name = "viewDistance"];`
     */
    public var viewDistance: kotlin.Int
      @kotlin.jvm.JvmName("getViewDistance")
        get() = _builder.viewDistance
      @kotlin.jvm.JvmName("setViewDistance")
        set(value) {
        _builder.viewDistance = value
      }
    /**
     * ```
     * Client render distance in chunks before the server clamps it to its own limit.
     * ```
     *
     * `int32 view_distance = 3 [json_name = "viewDistance"];`
     */
    public fun clearViewDistance() {
      _builder.clearViewDistance()
    }

    /**
     * `string chat_visibility = 4 [json_name = "chatVisibility"];`
     */
    public var chatVisibility: kotlin.String
      @kotlin.jvm.JvmName("getChatVisibility")
        get() = _builder.chatVisibility
      @kotlin.jvm.JvmName("setChatVisibility")
        set(value) {
        _builder.chatVisibility = value
      }
    /**
     * `string chat_visibility = 4 [json_name = "chatVisibility"];`
     */
    public fun clearChatVisibility() {
      _builder.clearChatVisibility()
    }

    /**
     * `bool chat_colors = 5 [json_name = "chatColors"];`
     */
    public var chatColors: kotlin.Boolean
      @kotlin.jvm.JvmName("getChatColors")
        get() = _builder.chatColors
      @kotlin.jvm.JvmName("setChatColors")
        set(value) {
        _builder.chatColors = value
      }
    /**
     * `bool chat_colors = 5 [json_name = "chatColors"];`
     */
    public fun clearChatColors() {
      _builder.clearChatColors()
    }

    /**
     * ```
     * Bit mask of visible player model parts.
     * ```
     *
     * `int32 model_customisation = 6 [json_name = "modelCustomisation"];`
     */
    public var modelCustomisation: kotlin.Int
      @kotlin.jvm.JvmName("getModelCustomisation")
        get() = _builder.modelCustomisation
      @kotlin.jvm.JvmName("setModelCustomisation")
        set(value) {
        _builder.modelCustomisation = value
      }
    /**
     * ```
     * Bit mask of visible player model parts.
     * ```
     *
     * `int32 model_customisation = 6 [json_name = "modelCustomisation"];`
     */
    public fun clearModelCustomisation() {
      _builder.clearModelCustomisation()
    }

    /**
     * `string main_hand = 7 [json_name = "mainHand"];`
     */
    public var mainHand: kotlin.String
      @kotlin.jvm.JvmName("getMainHand")
        get() = _builder.mainHand
      @kotlin.jvm.JvmName("setMainHand")
        set(value) {
        _builder.mainHand = value
      }
    /**
     * `string main_hand = 7 [json_name = "mainHand"];`
     */
    public fun clearMainHand() {
      _builder.clearMainHand()
    }

    /**
     * `bool text_filtering = 8 [json_name = "textFiltering"];`
     */
    public var textFiltering: kotlin.Boolean
      @kotlin.jvm.JvmName("getTextFiltering")
        get() = _builder.textFiltering
      @kotlin.jvm.JvmName("setTextFiltering")
        set(value) {
        _builder.textFiltering = value
      }
    /**
     * `bool text_filtering = 8 [json_name = "textFiltering"];`
     */
    public fun clearTextFiltering() {
      _builder.clearTextFiltering()
    }

    /**
     * `bool allows_listing = 9 [json_name = "allowsListing"];`
     */
    public var allowsListing: kotlin.Boolean
      @kotlin.jvm.JvmName("getAllowsListing")
        get() = _builder.allowsListing
      @kotlin.jvm.JvmName("setAllowsListing")
        set(value) {
        _builder.allowsListing = value
      }
    /**
     * `bool allows_listing = 9 [json_name = "allowsListing"];`
     */
    public fun clearAllowsListing() {
      _builder.clearAllowsListing()
    }

    /**
     * `string particle_status = 10 [json_name = "particleStatus"];`
     */
    public var particleStatus: kotlin.String
      @kotlin.jvm.JvmName("getParticleStatus")
        get() = _builder.particleStatus
      @kotlin.jvm.JvmName("setParticleStatus")
        set(value) {
        _builder.particleStatus = value
      }
    /**
     * `string particle_status = 10 [json_name = "particleStatus"];`
     */
    public fun clearParticleStatus() {
      _builder.clearParticleStatus()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun dev.recorderminecraft.artifacts.v1.ClientInformationEvent.copy(block: `dev.recorderminecraft.artifacts.v1`.ClientInformationEventKt.Dsl.() -> kotlin.Unit): dev.recorderminecraft.artifacts.v1.ClientInformationEvent =
  `dev.recorderminecraft.artifacts.v1`.ClientInformationEventKt.Dsl._create(this.toBuilder()).apply { block() }._build()

