// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: recorder-minecraft/artifacts/v1/events.proto
// Protobuf Java Version: 4.33.2

package dev.recorderminecraft.artifacts.v1;

@com.google.protobuf.Generated
public interface ControlStateEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:recorder_minecraft.artifacts.v1.ControlStateEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.recorder_minecraft.artifacts.v1.ControlState state = 1 [json_name = "state"];</code>
   * @return Whether the state field is set.
   */
  boolean hasState();
  /**
   * <code>.recorder_minecraft.artifacts.v1.ControlState state = 1 [json_name = "state"];</code>
   * @return The state.
   */
  dev.recorderminecraft.artifacts.v1.ControlState getState();
  /**
   * <code>.recorder_minecraft.artifacts.v1.ControlState state = 1 [json_name = "state"];</code>
   */
  dev.recorderminecraft.artifacts.v1.ControlStateOrBuilder getStateOrBuilder();
}
