// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: recorder-minecraft/artifacts/v1/events.proto
// Protobuf Java Version: 4.33.2

package dev.recorderminecraft.artifacts.v1;

/**
 * Protobuf type {@code recorder_minecraft.artifacts.v1.PacketApplyEvent}
 */
@com.google.protobuf.Generated
public final class PacketApplyEvent extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:recorder_minecraft.artifacts.v1.PacketApplyEvent)
    PacketApplyEventOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "PacketApplyEvent");
  }
  // Use PacketApplyEvent.newBuilder() to construct.
  private PacketApplyEvent(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PacketApplyEvent() {
    phase_ = "";
    tickPhase_ = "";
    mainThread_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return dev.recorderminecraft.artifacts.v1.Events.internal_static_recorder_minecraft_artifacts_v1_PacketApplyEvent_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return dev.recorderminecraft.artifacts.v1.Events.internal_static_recorder_minecraft_artifacts_v1_PacketApplyEvent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            dev.recorderminecraft.artifacts.v1.PacketApplyEvent.class, dev.recorderminecraft.artifacts.v1.PacketApplyEvent.Builder.class);
  }

  private int bitField0_;
  public static final int APPLY_SEQUENCE_FIELD_NUMBER = 1;
  private long applySequence_ = 0L;
  /**
   * <code>uint64 apply_sequence = 1 [json_name = "applySequence"];</code>
   * @return The applySequence.
   */
  @java.lang.Override
  public long getApplySequence() {
    return applySequence_;
  }

  public static final int PHASE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object phase_ = "";
  /**
   * <code>string phase = 2 [json_name = "phase"];</code>
   * @return The phase.
   */
  @java.lang.Override
  public java.lang.String getPhase() {
    java.lang.Object ref = phase_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      phase_ = s;
      return s;
    }
  }
  /**
   * <code>string phase = 2 [json_name = "phase"];</code>
   * @return The bytes for phase.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPhaseBytes() {
    java.lang.Object ref = phase_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      phase_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TICK_PHASE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tickPhase_ = "";
  /**
   * <code>string tick_phase = 3 [json_name = "tickPhase"];</code>
   * @return The tickPhase.
   */
  @java.lang.Override
  public java.lang.String getTickPhase() {
    java.lang.Object ref = tickPhase_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tickPhase_ = s;
      return s;
    }
  }
  /**
   * <code>string tick_phase = 3 [json_name = "tickPhase"];</code>
   * @return The bytes for tickPhase.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTickPhaseBytes() {
    java.lang.Object ref = tickPhase_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tickPhase_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MAIN_THREAD_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object mainThread_ = "";
  /**
   * <code>string main_thread = 4 [json_name = "mainThread"];</code>
   * @return The mainThread.
   */
  @java.lang.Override
  public java.lang.String getMainThread() {
    java.lang.Object ref = mainThread_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      mainThread_ = s;
      return s;
    }
  }
  /**
   * <code>string main_thread = 4 [json_name = "mainThread"];</code>
   * @return The bytes for mainThread.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMainThreadBytes() {
    java.lang.Object ref = mainThread_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      mainThread_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ARRIVAL_SEQUENCE_FIELD_NUMBER = 5;
  private long arrivalSequence_ = 0L;
  /**
   * <code>optional uint64 arrival_sequence = 5 [json_name = "arrivalSequence"];</code>
   * @return Whether the arrivalSequence field is set.
   */
  @java.lang.Override
  public boolean hasArrivalSequence() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional uint64 arrival_sequence = 5 [json_name = "arrivalSequence"];</code>
   * @return The arrivalSequence.
   */
  @java.lang.Override
  public long getArrivalSequence() {
    return arrivalSequence_;
  }

  public static final int ARRIVAL_SERVER_TICK_FIELD_NUMBER = 6;
  private long arrivalServerTick_ = 0L;
  /**
   * <code>optional int64 arrival_server_tick = 6 [json_name = "arrivalServerTick"];</code>
   * @return Whether the arrivalServerTick field is set.
   */
  @java.lang.Override
  public boolean hasArrivalServerTick() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional int64 arrival_server_tick = 6 [json_name = "arrivalServerTick"];</code>
   * @return The arrivalServerTick.
   */
  @java.lang.Override
  public long getArrivalServerTick() {
    return arrivalServerTick_;
  }

  public static final int ARRIVAL_MISSING_FIELD_NUMBER = 7;
  private boolean arrivalMissing_ = false;
  /**
   * <code>bool arrival_missing = 7 [json_name = "arrivalMissing"];</code>
   * @return The arrivalMissing.
   */
  @java.lang.Override
  public boolean getArrivalMissing() {
    return arrivalMissing_;
  }

  public static final int PACKET_FIELD_NUMBER = 8;
  private dev.recorderminecraft.artifacts.v1.Packet packet_;
  /**
   * <code>.recorder_minecraft.artifacts.v1.Packet packet = 8 [json_name = "packet"];</code>
   * @return Whether the packet field is set.
   */
  @java.lang.Override
  public boolean hasPacket() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>.recorder_minecraft.artifacts.v1.Packet packet = 8 [json_name = "packet"];</code>
   * @return The packet.
   */
  @java.lang.Override
  public dev.recorderminecraft.artifacts.v1.Packet getPacket() {
    return packet_ == null ? dev.recorderminecraft.artifacts.v1.Packet.getDefaultInstance() : packet_;
  }
  /**
   * <code>.recorder_minecraft.artifacts.v1.Packet packet = 8 [json_name = "packet"];</code>
   */
  @java.lang.Override
  public dev.recorderminecraft.artifacts.v1.PacketOrBuilder getPacketOrBuilder() {
    return packet_ == null ? dev.recorderminecraft.artifacts.v1.Packet.getDefaultInstance() : packet_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (applySequence_ != 0L) {
      output.writeUInt64(1, applySequence_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(phase_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, phase_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tickPhase_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, tickPhase_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(mainThread_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, mainThread_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeUInt64(5, arrivalSequence_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeInt64(6, arrivalServerTick_);
    }
    if (arrivalMissing_ != false) {
      output.writeBool(7, arrivalMissing_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(8, getPacket());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (applySequence_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, applySequence_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(phase_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, phase_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tickPhase_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, tickPhase_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(mainThread_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, mainThread_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(5, arrivalSequence_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, arrivalServerTick_);
    }
    if (arrivalMissing_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(7, arrivalMissing_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getPacket());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof dev.recorderminecraft.artifacts.v1.PacketApplyEvent)) {
      return super.equals(obj);
    }
    dev.recorderminecraft.artifacts.v1.PacketApplyEvent other = (dev.recorderminecraft.artifacts.v1.PacketApplyEvent) obj;

    if (getApplySequence()
        != other.getApplySequence()) return false;
    if (!getPhase()
        .equals(other.getPhase())) return false;
    if (!getTickPhase()
        .equals(other.getTickPhase())) return false;
    if (!getMainThread()
        .equals(other.getMainThread())) return false;
    if (hasArrivalSequence() != other.hasArrivalSequence()) return false;
    if (hasArrivalSequence()) {
      if (getArrivalSequence()
          != other.getArrivalSequence()) return false;
    }
    if (hasArrivalServerTick() != other.hasArrivalServerTick()) return false;
    if (hasArrivalServerTick()) {
      if (getArrivalServerTick()
          != other.getArrivalServerTick()) return false;
    }
    if (getArrivalMissing()
        != other.getArrivalMissing()) return false;
    if (hasPacket() != other.hasPacket()) return false;
    if (hasPacket()) {
      if (!getPacket()
          .equals(other.getPacket())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + APPLY_SEQUENCE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getApplySequence());
    hash = (37 * hash) + PHASE_FIELD_NUMBER;
    hash = (53 * hash) + getPhase().hashCode();
    hash = (37 * hash) + TICK_PHASE_FIELD_NUMBER;
    hash = (53 * hash) + getTickPhase().hashCode();
    hash = (37 * hash) + MAIN_THREAD_FIELD_NUMBER;
    hash = (53 * hash) + getMainThread().hashCode();
    if (hasArrivalSequence()) {
      hash = (37 * hash) + ARRIVAL_SEQUENCE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getArrivalSequence());
    }
    if (hasArrivalServerTick()) {
      hash = (37 * hash) + ARRIVAL_SERVER_TICK_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getArrivalServerTick());
    }
    hash = (37 * hash) + ARRIVAL_MISSING_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getArrivalMissing());
    if (hasPacket()) {
      hash = (37 * hash) + PACKET_FIELD_NUMBER;
      hash = (53 * hash) + getPacket().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static dev.recorderminecraft.artifacts.v1.PacketApplyEvent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.recorderminecraft.artifacts.v1.PacketApplyEvent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.recorderminecraft.artifacts.v1.PacketApplyEvent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.recorderminecraft.artifacts.v1.PacketApplyEvent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.recorderminecraft.artifacts.v1.PacketApplyEvent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.recorderminecraft.artifacts.v1.PacketApplyEvent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.recorderminecraft.artifacts.v1.PacketApplyEvent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static dev.recorderminecraft.artifacts.v1.PacketApplyEvent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static dev.recorderminecraft.artifacts.v1.PacketApplyEvent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static dev.recorderminecraft.artifacts.v1.PacketApplyEvent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static dev.recorderminecraft.artifacts.v1.PacketApplyEvent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static dev.recorderminecraft.artifacts.v1.PacketApplyEvent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(dev.recorderminecraft.artifacts.v1.PacketApplyEvent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code recorder_minecraft.artifacts.v1.PacketApplyEvent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:recorder_minecraft.artifacts.v1.PacketApplyEvent)
      dev.recorderminecraft.artifacts.v1.PacketApplyEventOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dev.recorderminecraft.artifacts.v1.Events.internal_static_recorder_minecraft_artifacts_v1_PacketApplyEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dev.recorderminecraft.artifacts.v1.Events.internal_static_recorder_minecraft_artifacts_v1_PacketApplyEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dev.recorderminecraft.artifacts.v1.PacketApplyEvent.class, dev.recorderminecraft.artifacts.v1.PacketApplyEvent.Builder.class);
    }

    // Construct using dev.recorderminecraft.artifacts.v1.PacketApplyEvent.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetPacketFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      applySequence_ = 0L;
      phase_ = "";
      tickPhase_ = "";
      mainThread_ = "";
      arrivalSequence_ = 0L;
      arrivalServerTick_ = 0L;
      arrivalMissing_ = false;
      packet_ = null;
      if (packetBuilder_ != null) {
        packetBuilder_.dispose();
        packetBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return dev.recorderminecraft.artifacts.v1.Events.internal_static_recorder_minecraft_artifacts_v1_PacketApplyEvent_descriptor;
    }

    @java.lang.Override
    public dev.recorderminecraft.artifacts.v1.PacketApplyEvent getDefaultInstanceForType() {
      return dev.recorderminecraft.artifacts.v1.PacketApplyEvent.getDefaultInstance();
    }

    @java.lang.Override
    public dev.recorderminecraft.artifacts.v1.PacketApplyEvent build() {
      dev.recorderminecraft.artifacts.v1.PacketApplyEvent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public dev.recorderminecraft.artifacts.v1.PacketApplyEvent buildPartial() {
      dev.recorderminecraft.artifacts.v1.PacketApplyEvent result = new dev.recorderminecraft.artifacts.v1.PacketApplyEvent(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(dev.recorderminecraft.artifacts.v1.PacketApplyEvent result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.applySequence_ = applySequence_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.phase_ = phase_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.tickPhase_ = tickPhase_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.mainThread_ = mainThread_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.arrivalSequence_ = arrivalSequence_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.arrivalServerTick_ = arrivalServerTick_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.arrivalMissing_ = arrivalMissing_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.packet_ = packetBuilder_ == null
            ? packet_
            : packetBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof dev.recorderminecraft.artifacts.v1.PacketApplyEvent) {
        return mergeFrom((dev.recorderminecraft.artifacts.v1.PacketApplyEvent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(dev.recorderminecraft.artifacts.v1.PacketApplyEvent other) {
      if (other == dev.recorderminecraft.artifacts.v1.PacketApplyEvent.getDefaultInstance()) return this;
      if (other.getApplySequence() != 0L) {
        setApplySequence(other.getApplySequence());
      }
      if (!other.getPhase().isEmpty()) {
        phase_ = other.phase_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getTickPhase().isEmpty()) {
        tickPhase_ = other.tickPhase_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getMainThread().isEmpty()) {
        mainThread_ = other.mainThread_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.hasArrivalSequence()) {
        setArrivalSequence(other.getArrivalSequence());
      }
      if (other.hasArrivalServerTick()) {
        setArrivalServerTick(other.getArrivalServerTick());
      }
      if (other.getArrivalMissing() != false) {
        setArrivalMissing(other.getArrivalMissing());
      }
      if (other.hasPacket()) {
        mergePacket(other.getPacket());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              applySequence_ = input.readUInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              phase_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              tickPhase_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              mainThread_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 40: {
              arrivalSequence_ = input.readUInt64();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              arrivalServerTick_ = input.readInt64();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              arrivalMissing_ = input.readBool();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 66: {
              input.readMessage(
                  internalGetPacketFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long applySequence_ ;
    /**
     * <code>uint64 apply_sequence = 1 [json_name = "applySequence"];</code>
     * @return The applySequence.
     */
    @java.lang.Override
    public long getApplySequence() {
      return applySequence_;
    }
    /**
     * <code>uint64 apply_sequence = 1 [json_name = "applySequence"];</code>
     * @param value The applySequence to set.
     * @return This builder for chaining.
     */
    public Builder setApplySequence(long value) {

      applySequence_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 apply_sequence = 1 [json_name = "applySequence"];</code>
     * @return This builder for chaining.
     */
    public Builder clearApplySequence() {
      bitField0_ = (bitField0_ & ~0x00000001);
      applySequence_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object phase_ = "";
    /**
     * <code>string phase = 2 [json_name = "phase"];</code>
     * @return The phase.
     */
    public java.lang.String getPhase() {
      java.lang.Object ref = phase_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        phase_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string phase = 2 [json_name = "phase"];</code>
     * @return The bytes for phase.
     */
    public com.google.protobuf.ByteString
        getPhaseBytes() {
      java.lang.Object ref = phase_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phase_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string phase = 2 [json_name = "phase"];</code>
     * @param value The phase to set.
     * @return This builder for chaining.
     */
    public Builder setPhase(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      phase_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string phase = 2 [json_name = "phase"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPhase() {
      phase_ = getDefaultInstance().getPhase();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string phase = 2 [json_name = "phase"];</code>
     * @param value The bytes for phase to set.
     * @return This builder for chaining.
     */
    public Builder setPhaseBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      phase_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object tickPhase_ = "";
    /**
     * <code>string tick_phase = 3 [json_name = "tickPhase"];</code>
     * @return The tickPhase.
     */
    public java.lang.String getTickPhase() {
      java.lang.Object ref = tickPhase_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tickPhase_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string tick_phase = 3 [json_name = "tickPhase"];</code>
     * @return The bytes for tickPhase.
     */
    public com.google.protobuf.ByteString
        getTickPhaseBytes() {
      java.lang.Object ref = tickPhase_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tickPhase_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tick_phase = 3 [json_name = "tickPhase"];</code>
     * @param value The tickPhase to set.
     * @return This builder for chaining.
     */
    public Builder setTickPhase(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tickPhase_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string tick_phase = 3 [json_name = "tickPhase"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTickPhase() {
      tickPhase_ = getDefaultInstance().getTickPhase();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string tick_phase = 3 [json_name = "tickPhase"];</code>
     * @param value The bytes for tickPhase to set.
     * @return This builder for chaining.
     */
    public Builder setTickPhaseBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tickPhase_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object mainThread_ = "";
    /**
     * <code>string main_thread = 4 [json_name = "mainThread"];</code>
     * @return The mainThread.
     */
    public java.lang.String getMainThread() {
      java.lang.Object ref = mainThread_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mainThread_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string main_thread = 4 [json_name = "mainThread"];</code>
     * @return The bytes for mainThread.
     */
    public com.google.protobuf.ByteString
        getMainThreadBytes() {
      java.lang.Object ref = mainThread_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mainThread_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string main_thread = 4 [json_name = "mainThread"];</code>
     * @param value The mainThread to set.
     * @return This builder for chaining.
     */
    public Builder setMainThread(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      mainThread_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string main_thread = 4 [json_name = "mainThread"];</code>
     * @return This builder for chaining.
     */
    public Builder clearMainThread() {
      mainThread_ = getDefaultInstance().getMainThread();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string main_thread = 4 [json_name = "mainThread"];</code>
     * @param value The bytes for mainThread to set.
     * @return This builder for chaining.
     */
    public Builder setMainThreadBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      mainThread_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private long arrivalSequence_ ;
    /**
     * <code>optional uint64 arrival_sequence = 5 [json_name = "arrivalSequence"];</code>
     * @return Whether the arrivalSequence field is set.
     */
    @java.lang.Override
    public boolean hasArrivalSequence() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional uint64 arrival_sequence = 5 [json_name = "arrivalSequence"];</code>
     * @return The arrivalSequence.
     */
    @java.lang.Override
    public long getArrivalSequence() {
      return arrivalSequence_;
    }
    /**
     * <code>optional uint64 arrival_sequence = 5 [json_name = "arrivalSequence"];</code>
     * @param value The arrivalSequence to set.
     * @return This builder for chaining.
     */
    public Builder setArrivalSequence(long value) {

      arrivalSequence_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint64 arrival_sequence = 5 [json_name = "arrivalSequence"];</code>
     * @return This builder for chaining.
     */
    public Builder clearArrivalSequence() {
      bitField0_ = (bitField0_ & ~0x00000010);
      arrivalSequence_ = 0L;
      onChanged();
      return this;
    }

    private long arrivalServerTick_ ;
    /**
     * <code>optional int64 arrival_server_tick = 6 [json_name = "arrivalServerTick"];</code>
     * @return Whether the arrivalServerTick field is set.
     */
    @java.lang.Override
    public boolean hasArrivalServerTick() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional int64 arrival_server_tick = 6 [json_name = "arrivalServerTick"];</code>
     * @return The arrivalServerTick.
     */
    @java.lang.Override
    public long getArrivalServerTick() {
      return arrivalServerTick_;
    }
    /**
     * <code>optional int64 arrival_server_tick = 6 [json_name = "arrivalServerTick"];</code>
     * @param value The arrivalServerTick to set.
     * @return This builder for chaining.
     */
    public Builder setArrivalServerTick(long value) {

      arrivalServerTick_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 arrival_server_tick = 6 [json_name = "arrivalServerTick"];</code>
     * @return This builder for chaining.
     */
    public Builder clearArrivalServerTick() {
      bitField0_ = (bitField0_ & ~0x00000020);
      arrivalServerTick_ = 0L;
      onChanged();
      return this;
    }

    private boolean arrivalMissing_ ;
    /**
     * <code>bool arrival_missing = 7 [json_name = "arrivalMissing"];</code>
     * @return The arrivalMissing.
     */
    @java.lang.Override
    public boolean getArrivalMissing() {
      return arrivalMissing_;
    }
    /**
     * <code>bool arrival_missing = 7 [json_name = "arrivalMissing"];</code>
     * @param value The arrivalMissing to set.
     * @return This builder for chaining.
     */
    public Builder setArrivalMissing(boolean value) {

      arrivalMissing_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>bool arrival_missing = 7 [json_name = "arrivalMissing"];</code>
     * @return This builder for chaining.
     */
    public Builder clearArrivalMissing() {
      bitField0_ = (bitField0_ & ~0x00000040);
      arrivalMissing_ = false;
      onChanged();
      return this;
    }

    private dev.recorderminecraft.artifacts.v1.Packet packet_;
    private com.google.protobuf.SingleFieldBuilder<
        dev.recorderminecraft.artifacts.v1.Packet, dev.recorderminecraft.artifacts.v1.Packet.Builder, dev.recorderminecraft.artifacts.v1.PacketOrBuilder> packetBuilder_;
    /**
     * <code>.recorder_minecraft.artifacts.v1.Packet packet = 8 [json_name = "packet"];</code>
     * @return Whether the packet field is set.
     */
    public boolean hasPacket() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>.recorder_minecraft.artifacts.v1.Packet packet = 8 [json_name = "packet"];</code>
     * @return The packet.
     */
    public dev.recorderminecraft.artifacts.v1.Packet getPacket() {
      if (packetBuilder_ == null) {
        return packet_ == null ? dev.recorderminecraft.artifacts.v1.Packet.getDefaultInstance() : packet_;
      } else {
        return packetBuilder_.getMessage();
      }
    }
    /**
     * <code>.recorder_minecraft.artifacts.v1.Packet packet = 8 [json_name = "packet"];</code>
     */
    public Builder setPacket(dev.recorderminecraft.artifacts.v1.Packet value) {
      if (packetBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        packet_ = value;
      } else {
        packetBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>.recorder_minecraft.artifacts.v1.Packet packet = 8 [json_name = "packet"];</code>
     */
    public Builder setPacket(
        dev.recorderminecraft.artifacts.v1.Packet.Builder builderForValue) {
      if (packetBuilder_ == null) {
        packet_ = builderForValue.build();
      } else {
        packetBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>.recorder_minecraft.artifacts.v1.Packet packet = 8 [json_name = "packet"];</code>
     */
    public Builder mergePacket(dev.recorderminecraft.artifacts.v1.Packet value) {
      if (packetBuilder_ == null) {
        if (((bitField0_ & 0x00000080) != 0) &&
          packet_ != null &&
          packet_ != dev.recorderminecraft.artifacts.v1.Packet.getDefaultInstance()) {
          getPacketBuilder().mergeFrom(value);
        } else {
          packet_ = value;
        }
      } else {
        packetBuilder_.mergeFrom(value);
      }
      if (packet_ != null) {
        bitField0_ |= 0x00000080;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.recorder_minecraft.artifacts.v1.Packet packet = 8 [json_name = "packet"];</code>
     */
    public Builder clearPacket() {
      bitField0_ = (bitField0_ & ~0x00000080);
      packet_ = null;
      if (packetBuilder_ != null) {
        packetBuilder_.dispose();
        packetBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.recorder_minecraft.artifacts.v1.Packet packet = 8 [json_name = "packet"];</code>
     */
    public dev.recorderminecraft.artifacts.v1.Packet.Builder getPacketBuilder() {
      bitField0_ |= 0x00000080;
      onChanged();
      return internalGetPacketFieldBuilder().getBuilder();
    }
    /**
     * <code>.recorder_minecraft.artifacts.v1.Packet packet = 8 [json_name = "packet"];</code>
     */
    public dev.recorderminecraft.artifacts.v1.PacketOrBuilder getPacketOrBuilder() {
      if (packetBuilder_ != null) {
        return packetBuilder_.getMessageOrBuilder();
      } else {
        return packet_ == null ?
            dev.recorderminecraft.artifacts.v1.Packet.getDefaultInstance() : packet_;
      }
    }
    /**
     * <code>.recorder_minecraft.artifacts.v1.Packet packet = 8 [json_name = "packet"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        dev.recorderminecraft.artifacts.v1.Packet, dev.recorderminecraft.artifacts.v1.Packet.Builder, dev.recorderminecraft.artifacts.v1.PacketOrBuilder> 
        internalGetPacketFieldBuilder() {
      if (packetBuilder_ == null) {
        packetBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            dev.recorderminecraft.artifacts.v1.Packet, dev.recorderminecraft.artifacts.v1.Packet.Builder, dev.recorderminecraft.artifacts.v1.PacketOrBuilder>(
                getPacket(),
                getParentForChildren(),
                isClean());
        packet_ = null;
      }
      return packetBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:recorder_minecraft.artifacts.v1.PacketApplyEvent)
  }

  // @@protoc_insertion_point(class_scope:recorder_minecraft.artifacts.v1.PacketApplyEvent)
  private static final dev.recorderminecraft.artifacts.v1.PacketApplyEvent DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new dev.recorderminecraft.artifacts.v1.PacketApplyEvent();
  }

  public static dev.recorderminecraft.artifacts.v1.PacketApplyEvent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PacketApplyEvent>
      PARSER = new com.google.protobuf.AbstractParser<PacketApplyEvent>() {
    @java.lang.Override
    public PacketApplyEvent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PacketApplyEvent> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PacketApplyEvent> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public dev.recorderminecraft.artifacts.v1.PacketApplyEvent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

