// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: recorder-minecraft/artifacts/v1/perception.proto
// Protobuf Java Version: 4.33.2

package dev.recorderminecraft.artifacts.v1;

@com.google.protobuf.Generated
public interface PerceptionObserverOrBuilder extends
    // @@protoc_insertion_point(interface_extends:recorder_minecraft.artifacts.v1.PerceptionObserver)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Scene network id of the observer entity, excluded from targets.
   * </pre>
   *
   * <code>int32 entity_id = 1 [json_name = "entityId"];</code>
   * @return The entityId.
   */
  int getEntityId();

  /**
   * <pre>
   * Feet position from the authoritative post-tick player state.
   * </pre>
   *
   * <code>.recorder_minecraft.artifacts.v1.Vector3 position = 2 [json_name = "position"];</code>
   * @return Whether the position field is set.
   */
  boolean hasPosition();
  /**
   * <pre>
   * Feet position from the authoritative post-tick player state.
   * </pre>
   *
   * <code>.recorder_minecraft.artifacts.v1.Vector3 position = 2 [json_name = "position"];</code>
   * @return The position.
   */
  dev.recorderminecraft.artifacts.v1.Vector3 getPosition();
  /**
   * <pre>
   * Feet position from the authoritative post-tick player state.
   * </pre>
   *
   * <code>.recorder_minecraft.artifacts.v1.Vector3 position = 2 [json_name = "position"];</code>
   */
  dev.recorderminecraft.artifacts.v1.Vector3OrBuilder getPositionOrBuilder();

  /**
   * <code>.recorder_minecraft.artifacts.v1.Vector3 eye = 3 [json_name = "eye"];</code>
   * @return Whether the eye field is set.
   */
  boolean hasEye();
  /**
   * <code>.recorder_minecraft.artifacts.v1.Vector3 eye = 3 [json_name = "eye"];</code>
   * @return The eye.
   */
  dev.recorderminecraft.artifacts.v1.Vector3 getEye();
  /**
   * <code>.recorder_minecraft.artifacts.v1.Vector3 eye = 3 [json_name = "eye"];</code>
   */
  dev.recorderminecraft.artifacts.v1.Vector3OrBuilder getEyeOrBuilder();

  /**
   * <code>.recorder_minecraft.artifacts.v1.Rotation rotation = 4 [json_name = "rotation"];</code>
   * @return Whether the rotation field is set.
   */
  boolean hasRotation();
  /**
   * <code>.recorder_minecraft.artifacts.v1.Rotation rotation = 4 [json_name = "rotation"];</code>
   * @return The rotation.
   */
  dev.recorderminecraft.artifacts.v1.Rotation getRotation();
  /**
   * <code>.recorder_minecraft.artifacts.v1.Rotation rotation = 4 [json_name = "rotation"];</code>
   */
  dev.recorderminecraft.artifacts.v1.RotationOrBuilder getRotationOrBuilder();

  /**
   * <code>string pose = 5 [json_name = "pose"];</code>
   * @return The pose.
   */
  java.lang.String getPose();
  /**
   * <code>string pose = 5 [json_name = "pose"];</code>
   * @return The bytes for pose.
   */
  com.google.protobuf.ByteString
      getPoseBytes();

  /**
   * <code>double eye_height = 6 [json_name = "eyeHeight"];</code>
   * @return The eyeHeight.
   */
  double getEyeHeight();
}
