// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: recorder-minecraft/artifacts/v1/events.proto
// Protobuf Java Version: 4.33.2

package dev.recorderminecraft.artifacts.v1;

@com.google.protobuf.Generated
public interface PlayerStateEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:recorder_minecraft.artifacts.v1.PlayerStateEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string dimension = 1 [json_name = "dimension"];</code>
   * @return The dimension.
   */
  java.lang.String getDimension();
  /**
   * <code>string dimension = 1 [json_name = "dimension"];</code>
   * @return The bytes for dimension.
   */
  com.google.protobuf.ByteString
      getDimensionBytes();

  /**
   * <code>.recorder_minecraft.artifacts.v1.Vector3 position = 2 [json_name = "position"];</code>
   * @return Whether the position field is set.
   */
  boolean hasPosition();
  /**
   * <code>.recorder_minecraft.artifacts.v1.Vector3 position = 2 [json_name = "position"];</code>
   * @return The position.
   */
  dev.recorderminecraft.artifacts.v1.Vector3 getPosition();
  /**
   * <code>.recorder_minecraft.artifacts.v1.Vector3 position = 2 [json_name = "position"];</code>
   */
  dev.recorderminecraft.artifacts.v1.Vector3OrBuilder getPositionOrBuilder();

  /**
   * <code>.recorder_minecraft.artifacts.v1.Rotation rotation = 3 [json_name = "rotation"];</code>
   * @return Whether the rotation field is set.
   */
  boolean hasRotation();
  /**
   * <code>.recorder_minecraft.artifacts.v1.Rotation rotation = 3 [json_name = "rotation"];</code>
   * @return The rotation.
   */
  dev.recorderminecraft.artifacts.v1.Rotation getRotation();
  /**
   * <code>.recorder_minecraft.artifacts.v1.Rotation rotation = 3 [json_name = "rotation"];</code>
   */
  dev.recorderminecraft.artifacts.v1.RotationOrBuilder getRotationOrBuilder();

  /**
   * <code>.recorder_minecraft.artifacts.v1.Vector3 velocity = 4 [json_name = "velocity"];</code>
   * @return Whether the velocity field is set.
   */
  boolean hasVelocity();
  /**
   * <code>.recorder_minecraft.artifacts.v1.Vector3 velocity = 4 [json_name = "velocity"];</code>
   * @return The velocity.
   */
  dev.recorderminecraft.artifacts.v1.Vector3 getVelocity();
  /**
   * <code>.recorder_minecraft.artifacts.v1.Vector3 velocity = 4 [json_name = "velocity"];</code>
   */
  dev.recorderminecraft.artifacts.v1.Vector3OrBuilder getVelocityOrBuilder();

  /**
   * <code>bool alive = 5 [json_name = "alive"];</code>
   * @return The alive.
   */
  boolean getAlive();

  /**
   * <code>bool on_ground = 6 [json_name = "onGround"];</code>
   * @return The onGround.
   */
  boolean getOnGround();

  /**
   * <code>string pose = 7 [json_name = "pose"];</code>
   * @return The pose.
   */
  java.lang.String getPose();
  /**
   * <code>string pose = 7 [json_name = "pose"];</code>
   * @return The bytes for pose.
   */
  com.google.protobuf.ByteString
      getPoseBytes();

  /**
   * <code>bool sprinting = 8 [json_name = "sprinting"];</code>
   * @return The sprinting.
   */
  boolean getSprinting();

  /**
   * <code>bool sneaking = 9 [json_name = "sneaking"];</code>
   * @return The sneaking.
   */
  boolean getSneaking();

  /**
   * <code>bool swimming = 10 [json_name = "swimming"];</code>
   * @return The swimming.
   */
  boolean getSwimming();

  /**
   * <code>bool fall_flying = 11 [json_name = "fallFlying"];</code>
   * @return The fallFlying.
   */
  boolean getFallFlying();

  /**
   * <code>bool using_item = 12 [json_name = "usingItem"];</code>
   * @return The usingItem.
   */
  boolean getUsingItem();

  /**
   * <code>int32 use_item_remaining_ticks = 13 [json_name = "useItemRemainingTicks"];</code>
   * @return The useItemRemainingTicks.
   */
  int getUseItemRemainingTicks();

  /**
   * <code>string game_mode = 14 [json_name = "gameMode"];</code>
   * @return The gameMode.
   */
  java.lang.String getGameMode();
  /**
   * <code>string game_mode = 14 [json_name = "gameMode"];</code>
   * @return The bytes for gameMode.
   */
  com.google.protobuf.ByteString
      getGameModeBytes();

  /**
   * <code>double health = 15 [json_name = "health"];</code>
   * @return The health.
   */
  double getHealth();

  /**
   * <code>double max_health = 16 [json_name = "maxHealth"];</code>
   * @return The maxHealth.
   */
  double getMaxHealth();

  /**
   * <code>double absorption = 17 [json_name = "absorption"];</code>
   * @return The absorption.
   */
  double getAbsorption();

  /**
   * <code>int32 armor = 18 [json_name = "armor"];</code>
   * @return The armor.
   */
  int getArmor();

  /**
   * <code>int32 air = 19 [json_name = "air"];</code>
   * @return The air.
   */
  int getAir();

  /**
   * <code>int32 max_air = 20 [json_name = "maxAir"];</code>
   * @return The maxAir.
   */
  int getMaxAir();

  /**
   * <code>int32 food_level = 21 [json_name = "foodLevel"];</code>
   * @return The foodLevel.
   */
  int getFoodLevel();

  /**
   * <code>double saturation = 22 [json_name = "saturation"];</code>
   * @return The saturation.
   */
  double getSaturation();

  /**
   * <code>int32 experience_level = 23 [json_name = "experienceLevel"];</code>
   * @return The experienceLevel.
   */
  int getExperienceLevel();

  /**
   * <code>double experience_progress = 24 [json_name = "experienceProgress"];</code>
   * @return The experienceProgress.
   */
  double getExperienceProgress();

  /**
   * <code>int32 total_experience = 25 [json_name = "totalExperience"];</code>
   * @return The totalExperience.
   */
  int getTotalExperience();

  /**
   * <code>uint32 selected_slot = 26 [json_name = "selectedSlot"];</code>
   * @return The selectedSlot.
   */
  int getSelectedSlot();

  /**
   * <code>.recorder_minecraft.artifacts.v1.Abilities abilities = 27 [json_name = "abilities"];</code>
   * @return Whether the abilities field is set.
   */
  boolean hasAbilities();
  /**
   * <code>.recorder_minecraft.artifacts.v1.Abilities abilities = 27 [json_name = "abilities"];</code>
   * @return The abilities.
   */
  dev.recorderminecraft.artifacts.v1.Abilities getAbilities();
  /**
   * <code>.recorder_minecraft.artifacts.v1.Abilities abilities = 27 [json_name = "abilities"];</code>
   */
  dev.recorderminecraft.artifacts.v1.AbilitiesOrBuilder getAbilitiesOrBuilder();

  /**
   * <code>repeated .recorder_minecraft.artifacts.v1.StatusEffect effects = 28 [json_name = "effects"];</code>
   */
  java.util.List<dev.recorderminecraft.artifacts.v1.StatusEffect> 
      getEffectsList();
  /**
   * <code>repeated .recorder_minecraft.artifacts.v1.StatusEffect effects = 28 [json_name = "effects"];</code>
   */
  dev.recorderminecraft.artifacts.v1.StatusEffect getEffects(int index);
  /**
   * <code>repeated .recorder_minecraft.artifacts.v1.StatusEffect effects = 28 [json_name = "effects"];</code>
   */
  int getEffectsCount();
  /**
   * <code>repeated .recorder_minecraft.artifacts.v1.StatusEffect effects = 28 [json_name = "effects"];</code>
   */
  java.util.List<? extends dev.recorderminecraft.artifacts.v1.StatusEffectOrBuilder> 
      getEffectsOrBuilderList();
  /**
   * <code>repeated .recorder_minecraft.artifacts.v1.StatusEffect effects = 28 [json_name = "effects"];</code>
   */
  dev.recorderminecraft.artifacts.v1.StatusEffectOrBuilder getEffectsOrBuilder(
      int index);

  /**
   * <code>repeated .recorder_minecraft.artifacts.v1.Passenger passengers = 29 [json_name = "passengers"];</code>
   */
  java.util.List<dev.recorderminecraft.artifacts.v1.Passenger> 
      getPassengersList();
  /**
   * <code>repeated .recorder_minecraft.artifacts.v1.Passenger passengers = 29 [json_name = "passengers"];</code>
   */
  dev.recorderminecraft.artifacts.v1.Passenger getPassengers(int index);
  /**
   * <code>repeated .recorder_minecraft.artifacts.v1.Passenger passengers = 29 [json_name = "passengers"];</code>
   */
  int getPassengersCount();
  /**
   * <code>repeated .recorder_minecraft.artifacts.v1.Passenger passengers = 29 [json_name = "passengers"];</code>
   */
  java.util.List<? extends dev.recorderminecraft.artifacts.v1.PassengerOrBuilder> 
      getPassengersOrBuilderList();
  /**
   * <code>repeated .recorder_minecraft.artifacts.v1.Passenger passengers = 29 [json_name = "passengers"];</code>
   */
  dev.recorderminecraft.artifacts.v1.PassengerOrBuilder getPassengersOrBuilder(
      int index);

  /**
   * <code>repeated .recorder_minecraft.artifacts.v1.InventorySlot inventory = 30 [json_name = "inventory"];</code>
   */
  java.util.List<dev.recorderminecraft.artifacts.v1.InventorySlot> 
      getInventoryList();
  /**
   * <code>repeated .recorder_minecraft.artifacts.v1.InventorySlot inventory = 30 [json_name = "inventory"];</code>
   */
  dev.recorderminecraft.artifacts.v1.InventorySlot getInventory(int index);
  /**
   * <code>repeated .recorder_minecraft.artifacts.v1.InventorySlot inventory = 30 [json_name = "inventory"];</code>
   */
  int getInventoryCount();
  /**
   * <code>repeated .recorder_minecraft.artifacts.v1.InventorySlot inventory = 30 [json_name = "inventory"];</code>
   */
  java.util.List<? extends dev.recorderminecraft.artifacts.v1.InventorySlotOrBuilder> 
      getInventoryOrBuilderList();
  /**
   * <code>repeated .recorder_minecraft.artifacts.v1.InventorySlot inventory = 30 [json_name = "inventory"];</code>
   */
  dev.recorderminecraft.artifacts.v1.InventorySlotOrBuilder getInventoryOrBuilder(
      int index);

  /**
   * <code>uint64 state_barrier_apply_sequence = 31 [json_name = "stateBarrierApplySequence"];</code>
   * @return The stateBarrierApplySequence.
   */
  long getStateBarrierApplySequence();

  /**
   * <code>.recorder_minecraft.artifacts.v1.ReplayCoverage replay_coverage = 32 [json_name = "replayCoverage"];</code>
   * @return Whether the replayCoverage field is set.
   */
  boolean hasReplayCoverage();
  /**
   * <code>.recorder_minecraft.artifacts.v1.ReplayCoverage replay_coverage = 32 [json_name = "replayCoverage"];</code>
   * @return The replayCoverage.
   */
  dev.recorderminecraft.artifacts.v1.ReplayCoverage getReplayCoverage();
  /**
   * <code>.recorder_minecraft.artifacts.v1.ReplayCoverage replay_coverage = 32 [json_name = "replayCoverage"];</code>
   */
  dev.recorderminecraft.artifacts.v1.ReplayCoverageOrBuilder getReplayCoverageOrBuilder();

  /**
   * <code>.recorder_minecraft.artifacts.v1.EntityReference vehicle = 33 [json_name = "vehicle"];</code>
   * @return Whether the vehicle field is set.
   */
  boolean hasVehicle();
  /**
   * <code>.recorder_minecraft.artifacts.v1.EntityReference vehicle = 33 [json_name = "vehicle"];</code>
   * @return The vehicle.
   */
  dev.recorderminecraft.artifacts.v1.EntityReference getVehicle();
  /**
   * <code>.recorder_minecraft.artifacts.v1.EntityReference vehicle = 33 [json_name = "vehicle"];</code>
   */
  dev.recorderminecraft.artifacts.v1.EntityReferenceOrBuilder getVehicleOrBuilder();
}
