// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: recorder-minecraft/artifacts/v1/session_alignment.proto
// Protobuf Java Version: 4.33.2

package dev.recorderminecraft.artifacts.v1;

@com.google.protobuf.Generated
public interface RecordRefOrBuilder extends
    // @@protoc_insertion_point(interface_extends:recorder_minecraft.artifacts.v1.RecordRef)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.recorder_minecraft.artifacts.v1.RecordStream stream = 1 [json_name = "stream"];</code>
   * @return The enum numeric value on the wire for stream.
   */
  int getStreamValue();
  /**
   * <code>.recorder_minecraft.artifacts.v1.RecordStream stream = 1 [json_name = "stream"];</code>
   * @return The stream.
   */
  dev.recorderminecraft.artifacts.v1.RecordStream getStream();

  /**
   * <pre>
   * Actor that owns a capture or perception record; empty for the world stream.
   * </pre>
   *
   * <code>string connection_id = 2 [json_name = "connectionId"];</code>
   * @return The connectionId.
   */
  java.lang.String getConnectionId();
  /**
   * <pre>
   * Actor that owns a capture or perception record; empty for the world stream.
   * </pre>
   *
   * <code>string connection_id = 2 [json_name = "connectionId"];</code>
   * @return The bytes for connectionId.
   */
  com.google.protobuf.ByteString
      getConnectionIdBytes();

  /**
   * <code>int64 server_tick = 3 [json_name = "serverTick"];</code>
   * @return The serverTick.
   */
  long getServerTick();

  /**
   * <pre>
   * Stream sequence of a world or capture event. Zero for capture metadata
   * and perception samples, which the tick identifies.
   * </pre>
   *
   * <code>uint64 sequence = 4 [json_name = "sequence"];</code>
   * @return The sequence.
   */
  long getSequence();
}
