// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: recorder-minecraft/artifacts/v1/session_alignment.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package dev.recorderminecraft.artifacts.v1;

@kotlin.jvm.JvmName("-initializerecordRef")
public inline fun recordRef(block: dev.recorderminecraft.artifacts.v1.RecordRefKt.Dsl.() -> kotlin.Unit): dev.recorderminecraft.artifacts.v1.RecordRef =
  dev.recorderminecraft.artifacts.v1.RecordRefKt.Dsl._create(dev.recorderminecraft.artifacts.v1.RecordRef.newBuilder()).apply { block() }._build()
/**
 * ```
 * RecordRef points at one source record instead of copying it.
 * ```
 *
 * Protobuf type `recorder_minecraft.artifacts.v1.RecordRef`
 */
public object RecordRefKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: dev.recorderminecraft.artifacts.v1.RecordRef.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: dev.recorderminecraft.artifacts.v1.RecordRef.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): dev.recorderminecraft.artifacts.v1.RecordRef = _builder.build()

    /**
     * `.recorder_minecraft.artifacts.v1.RecordStream stream = 1 [json_name = "stream"];`
     */
    public var stream: dev.recorderminecraft.artifacts.v1.RecordStream
      @kotlin.jvm.JvmName("getStream")
        get() = _builder.stream
      @kotlin.jvm.JvmName("setStream")
        set(value) {
        _builder.stream = value
      }
    public var streamValue: kotlin.Int
      @kotlin.jvm.JvmName("getStreamValue")
        get() = _builder.streamValue
      @kotlin.jvm.JvmName("setStreamValue")
        set(value) {
        _builder.streamValue = value
      }
    /**
     * `.recorder_minecraft.artifacts.v1.RecordStream stream = 1 [json_name = "stream"];`
     */
    public fun clearStream() {
      _builder.clearStream()
    }

    /**
     * ```
     * Actor that owns a capture or perception record; empty for the world stream.
     * ```
     *
     * `string connection_id = 2 [json_name = "connectionId"];`
     */
    public var connectionId: kotlin.String
      @kotlin.jvm.JvmName("getConnectionId")
        get() = _builder.connectionId
      @kotlin.jvm.JvmName("setConnectionId")
        set(value) {
        _builder.connectionId = value
      }
    /**
     * ```
     * Actor that owns a capture or perception record; empty for the world stream.
     * ```
     *
     * `string connection_id = 2 [json_name = "connectionId"];`
     */
    public fun clearConnectionId() {
      _builder.clearConnectionId()
    }

    /**
     * `int64 server_tick = 3 [json_name = "serverTick"];`
     */
    public var serverTick: kotlin.Long
      @kotlin.jvm.JvmName("getServerTick")
        get() = _builder.serverTick
      @kotlin.jvm.JvmName("setServerTick")
        set(value) {
        _builder.serverTick = value
      }
    /**
     * `int64 server_tick = 3 [json_name = "serverTick"];`
     */
    public fun clearServerTick() {
      _builder.clearServerTick()
    }

    /**
     * ```
     * Stream sequence of a world or capture event. Zero for capture metadata
     * and perception samples, which the tick identifies.
     * ```
     *
     * `uint64 sequence = 4 [json_name = "sequence"];`
     */
    public var sequence: kotlin.Long
      @kotlin.jvm.JvmName("getSequence")
        get() = _builder.sequence
      @kotlin.jvm.JvmName("setSequence")
        set(value) {
        _builder.sequence = value
      }
    /**
     * ```
     * Stream sequence of a world or capture event. Zero for capture metadata
     * and perception samples, which the tick identifies.
     * ```
     *
     * `uint64 sequence = 4 [json_name = "sequence"];`
     */
    public fun clearSequence() {
      _builder.clearSequence()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun dev.recorderminecraft.artifacts.v1.RecordRef.copy(block: `dev.recorderminecraft.artifacts.v1`.RecordRefKt.Dsl.() -> kotlin.Unit): dev.recorderminecraft.artifacts.v1.RecordRef =
  `dev.recorderminecraft.artifacts.v1`.RecordRefKt.Dsl._create(this.toBuilder()).apply { block() }._build()

