// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: recorder-minecraft/artifacts/v1/scene_extraction.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package dev.recorderminecraft.artifacts.v1;

@kotlin.jvm.JvmName("-initializesceneToleratedMod")
public inline fun sceneToleratedMod(block: dev.recorderminecraft.artifacts.v1.SceneToleratedModKt.Dsl.() -> kotlin.Unit): dev.recorderminecraft.artifacts.v1.SceneToleratedMod =
  dev.recorderminecraft.artifacts.v1.SceneToleratedModKt.Dsl._create(dev.recorderminecraft.artifacts.v1.SceneToleratedMod.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `recorder_minecraft.artifacts.v1.SceneToleratedMod`
 */
public object SceneToleratedModKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: dev.recorderminecraft.artifacts.v1.SceneToleratedMod.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: dev.recorderminecraft.artifacts.v1.SceneToleratedMod.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): dev.recorderminecraft.artifacts.v1.SceneToleratedMod = _builder.build()

    /**
     * `string mod_id = 1 [json_name = "modId"];`
     */
    public var modId: kotlin.String
      @kotlin.jvm.JvmName("getModId")
        get() = _builder.modId
      @kotlin.jvm.JvmName("setModId")
        set(value) {
        _builder.modId = value
      }
    /**
     * `string mod_id = 1 [json_name = "modId"];`
     */
    public fun clearModId() {
      _builder.clearModId()
    }

    /**
     * `string source_version = 2 [json_name = "sourceVersion"];`
     */
    public var sourceVersion: kotlin.String
      @kotlin.jvm.JvmName("getSourceVersion")
        get() = _builder.sourceVersion
      @kotlin.jvm.JvmName("setSourceVersion")
        set(value) {
        _builder.sourceVersion = value
      }
    /**
     * `string source_version = 2 [json_name = "sourceVersion"];`
     */
    public fun clearSourceVersion() {
      _builder.clearSourceVersion()
    }

    /**
     * ```
     * Empty for DIFFERENCE_NOT_IN_EXTRACTOR.
     * ```
     *
     * `string extractor_version = 3 [json_name = "extractorVersion"];`
     */
    public var extractorVersion: kotlin.String
      @kotlin.jvm.JvmName("getExtractorVersion")
        get() = _builder.extractorVersion
      @kotlin.jvm.JvmName("setExtractorVersion")
        set(value) {
        _builder.extractorVersion = value
      }
    /**
     * ```
     * Empty for DIFFERENCE_NOT_IN_EXTRACTOR.
     * ```
     *
     * `string extractor_version = 3 [json_name = "extractorVersion"];`
     */
    public fun clearExtractorVersion() {
      _builder.clearExtractorVersion()
    }

    /**
     * `.recorder_minecraft.artifacts.v1.SceneToleratedMod.Difference difference = 4 [json_name = "difference"];`
     */
    public var difference: dev.recorderminecraft.artifacts.v1.SceneToleratedMod.Difference
      @kotlin.jvm.JvmName("getDifference")
        get() = _builder.difference
      @kotlin.jvm.JvmName("setDifference")
        set(value) {
        _builder.difference = value
      }
    public var differenceValue: kotlin.Int
      @kotlin.jvm.JvmName("getDifferenceValue")
        get() = _builder.differenceValue
      @kotlin.jvm.JvmName("setDifferenceValue")
        set(value) {
        _builder.differenceValue = value
      }
    /**
     * `.recorder_minecraft.artifacts.v1.SceneToleratedMod.Difference difference = 4 [json_name = "difference"];`
     */
    public fun clearDifference() {
      _builder.clearDifference()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun dev.recorderminecraft.artifacts.v1.SceneToleratedMod.copy(block: `dev.recorderminecraft.artifacts.v1`.SceneToleratedModKt.Dsl.() -> kotlin.Unit): dev.recorderminecraft.artifacts.v1.SceneToleratedMod =
  `dev.recorderminecraft.artifacts.v1`.SceneToleratedModKt.Dsl._create(this.toBuilder()).apply { block() }._build()

