// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: recorder-minecraft/artifacts/v1/scene_extraction.proto
// Protobuf Java Version: 4.33.2

package dev.recorderminecraft.artifacts.v1;

/**
 * Protobuf type {@code recorder_minecraft.artifacts.v1.SceneStreamResult}
 */
@com.google.protobuf.Generated
public final class SceneStreamResult extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:recorder_minecraft.artifacts.v1.SceneStreamResult)
    SceneStreamResultOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "SceneStreamResult");
  }
  // Use SceneStreamResult.newBuilder() to construct.
  private SceneStreamResult(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private SceneStreamResult() {
    path_ = "";
    frames_ = "";
    changes_ = "";
    blobsDirectory_ = "";
    framesSha256_ = "";
    changesSha256_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return dev.recorderminecraft.artifacts.v1.SceneExtraction.internal_static_recorder_minecraft_artifacts_v1_SceneStreamResult_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return dev.recorderminecraft.artifacts.v1.SceneExtraction.internal_static_recorder_minecraft_artifacts_v1_SceneStreamResult_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            dev.recorderminecraft.artifacts.v1.SceneStreamResult.class, dev.recorderminecraft.artifacts.v1.SceneStreamResult.Builder.class);
  }

  public static final int PATH_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object path_ = "";
  /**
   * <code>string path = 1 [json_name = "path"];</code>
   * @return The path.
   */
  @java.lang.Override
  public java.lang.String getPath() {
    java.lang.Object ref = path_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      path_ = s;
      return s;
    }
  }
  /**
   * <code>string path = 1 [json_name = "path"];</code>
   * @return The bytes for path.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPathBytes() {
    java.lang.Object ref = path_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      path_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FRAMES_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object frames_ = "";
  /**
   * <code>string frames = 2 [json_name = "frames"];</code>
   * @return The frames.
   */
  @java.lang.Override
  public java.lang.String getFrames() {
    java.lang.Object ref = frames_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      frames_ = s;
      return s;
    }
  }
  /**
   * <code>string frames = 2 [json_name = "frames"];</code>
   * @return The bytes for frames.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFramesBytes() {
    java.lang.Object ref = frames_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      frames_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CHANGES_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object changes_ = "";
  /**
   * <code>string changes = 3 [json_name = "changes"];</code>
   * @return The changes.
   */
  @java.lang.Override
  public java.lang.String getChanges() {
    java.lang.Object ref = changes_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      changes_ = s;
      return s;
    }
  }
  /**
   * <code>string changes = 3 [json_name = "changes"];</code>
   * @return The bytes for changes.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getChangesBytes() {
    java.lang.Object ref = changes_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      changes_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BLOBS_DIRECTORY_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object blobsDirectory_ = "";
  /**
   * <code>string blobs_directory = 4 [json_name = "blobsDirectory"];</code>
   * @return The blobsDirectory.
   */
  @java.lang.Override
  public java.lang.String getBlobsDirectory() {
    java.lang.Object ref = blobsDirectory_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      blobsDirectory_ = s;
      return s;
    }
  }
  /**
   * <code>string blobs_directory = 4 [json_name = "blobsDirectory"];</code>
   * @return The bytes for blobsDirectory.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBlobsDirectoryBytes() {
    java.lang.Object ref = blobsDirectory_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      blobsDirectory_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FRAME_COUNT_FIELD_NUMBER = 5;
  private long frameCount_ = 0L;
  /**
   * <code>uint64 frame_count = 5 [json_name = "frameCount"];</code>
   * @return The frameCount.
   */
  @java.lang.Override
  public long getFrameCount() {
    return frameCount_;
  }

  public static final int CHANGE_COUNT_FIELD_NUMBER = 6;
  private long changeCount_ = 0L;
  /**
   * <code>uint64 change_count = 6 [json_name = "changeCount"];</code>
   * @return The changeCount.
   */
  @java.lang.Override
  public long getChangeCount() {
    return changeCount_;
  }

  public static final int BLOB_COUNT_FIELD_NUMBER = 7;
  private long blobCount_ = 0L;
  /**
   * <code>uint64 blob_count = 7 [json_name = "blobCount"];</code>
   * @return The blobCount.
   */
  @java.lang.Override
  public long getBlobCount() {
    return blobCount_;
  }

  public static final int BLOB_BYTES_FIELD_NUMBER = 8;
  private long blobBytes_ = 0L;
  /**
   * <code>uint64 blob_bytes = 8 [json_name = "blobBytes"];</code>
   * @return The blobBytes.
   */
  @java.lang.Override
  public long getBlobBytes() {
    return blobBytes_;
  }

  public static final int FRAMES_SHA256_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private volatile java.lang.Object framesSha256_ = "";
  /**
   * <code>string frames_sha256 = 9 [json_name = "framesSha256"];</code>
   * @return The framesSha256.
   */
  @java.lang.Override
  public java.lang.String getFramesSha256() {
    java.lang.Object ref = framesSha256_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      framesSha256_ = s;
      return s;
    }
  }
  /**
   * <code>string frames_sha256 = 9 [json_name = "framesSha256"];</code>
   * @return The bytes for framesSha256.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFramesSha256Bytes() {
    java.lang.Object ref = framesSha256_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      framesSha256_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FRAMES_SIZE_BYTES_FIELD_NUMBER = 10;
  private long framesSizeBytes_ = 0L;
  /**
   * <code>uint64 frames_size_bytes = 10 [json_name = "framesSizeBytes"];</code>
   * @return The framesSizeBytes.
   */
  @java.lang.Override
  public long getFramesSizeBytes() {
    return framesSizeBytes_;
  }

  public static final int CHANGES_SHA256_FIELD_NUMBER = 11;
  @SuppressWarnings("serial")
  private volatile java.lang.Object changesSha256_ = "";
  /**
   * <code>string changes_sha256 = 11 [json_name = "changesSha256"];</code>
   * @return The changesSha256.
   */
  @java.lang.Override
  public java.lang.String getChangesSha256() {
    java.lang.Object ref = changesSha256_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      changesSha256_ = s;
      return s;
    }
  }
  /**
   * <code>string changes_sha256 = 11 [json_name = "changesSha256"];</code>
   * @return The bytes for changesSha256.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getChangesSha256Bytes() {
    java.lang.Object ref = changesSha256_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      changesSha256_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CHANGES_SIZE_BYTES_FIELD_NUMBER = 12;
  private long changesSizeBytes_ = 0L;
  /**
   * <code>uint64 changes_size_bytes = 12 [json_name = "changesSizeBytes"];</code>
   * @return The changesSizeBytes.
   */
  @java.lang.Override
  public long getChangesSizeBytes() {
    return changesSizeBytes_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(path_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, path_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(frames_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, frames_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(changes_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, changes_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(blobsDirectory_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, blobsDirectory_);
    }
    if (frameCount_ != 0L) {
      output.writeUInt64(5, frameCount_);
    }
    if (changeCount_ != 0L) {
      output.writeUInt64(6, changeCount_);
    }
    if (blobCount_ != 0L) {
      output.writeUInt64(7, blobCount_);
    }
    if (blobBytes_ != 0L) {
      output.writeUInt64(8, blobBytes_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(framesSha256_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 9, framesSha256_);
    }
    if (framesSizeBytes_ != 0L) {
      output.writeUInt64(10, framesSizeBytes_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(changesSha256_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 11, changesSha256_);
    }
    if (changesSizeBytes_ != 0L) {
      output.writeUInt64(12, changesSizeBytes_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(path_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, path_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(frames_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, frames_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(changes_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, changes_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(blobsDirectory_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, blobsDirectory_);
    }
    if (frameCount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(5, frameCount_);
    }
    if (changeCount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(6, changeCount_);
    }
    if (blobCount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(7, blobCount_);
    }
    if (blobBytes_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(8, blobBytes_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(framesSha256_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(9, framesSha256_);
    }
    if (framesSizeBytes_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(10, framesSizeBytes_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(changesSha256_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(11, changesSha256_);
    }
    if (changesSizeBytes_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(12, changesSizeBytes_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof dev.recorderminecraft.artifacts.v1.SceneStreamResult)) {
      return super.equals(obj);
    }
    dev.recorderminecraft.artifacts.v1.SceneStreamResult other = (dev.recorderminecraft.artifacts.v1.SceneStreamResult) obj;

    if (!getPath()
        .equals(other.getPath())) return false;
    if (!getFrames()
        .equals(other.getFrames())) return false;
    if (!getChanges()
        .equals(other.getChanges())) return false;
    if (!getBlobsDirectory()
        .equals(other.getBlobsDirectory())) return false;
    if (getFrameCount()
        != other.getFrameCount()) return false;
    if (getChangeCount()
        != other.getChangeCount()) return false;
    if (getBlobCount()
        != other.getBlobCount()) return false;
    if (getBlobBytes()
        != other.getBlobBytes()) return false;
    if (!getFramesSha256()
        .equals(other.getFramesSha256())) return false;
    if (getFramesSizeBytes()
        != other.getFramesSizeBytes()) return false;
    if (!getChangesSha256()
        .equals(other.getChangesSha256())) return false;
    if (getChangesSizeBytes()
        != other.getChangesSizeBytes()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PATH_FIELD_NUMBER;
    hash = (53 * hash) + getPath().hashCode();
    hash = (37 * hash) + FRAMES_FIELD_NUMBER;
    hash = (53 * hash) + getFrames().hashCode();
    hash = (37 * hash) + CHANGES_FIELD_NUMBER;
    hash = (53 * hash) + getChanges().hashCode();
    hash = (37 * hash) + BLOBS_DIRECTORY_FIELD_NUMBER;
    hash = (53 * hash) + getBlobsDirectory().hashCode();
    hash = (37 * hash) + FRAME_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getFrameCount());
    hash = (37 * hash) + CHANGE_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getChangeCount());
    hash = (37 * hash) + BLOB_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getBlobCount());
    hash = (37 * hash) + BLOB_BYTES_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getBlobBytes());
    hash = (37 * hash) + FRAMES_SHA256_FIELD_NUMBER;
    hash = (53 * hash) + getFramesSha256().hashCode();
    hash = (37 * hash) + FRAMES_SIZE_BYTES_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getFramesSizeBytes());
    hash = (37 * hash) + CHANGES_SHA256_FIELD_NUMBER;
    hash = (53 * hash) + getChangesSha256().hashCode();
    hash = (37 * hash) + CHANGES_SIZE_BYTES_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getChangesSizeBytes());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static dev.recorderminecraft.artifacts.v1.SceneStreamResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.recorderminecraft.artifacts.v1.SceneStreamResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.recorderminecraft.artifacts.v1.SceneStreamResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.recorderminecraft.artifacts.v1.SceneStreamResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.recorderminecraft.artifacts.v1.SceneStreamResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.recorderminecraft.artifacts.v1.SceneStreamResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.recorderminecraft.artifacts.v1.SceneStreamResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static dev.recorderminecraft.artifacts.v1.SceneStreamResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static dev.recorderminecraft.artifacts.v1.SceneStreamResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static dev.recorderminecraft.artifacts.v1.SceneStreamResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static dev.recorderminecraft.artifacts.v1.SceneStreamResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static dev.recorderminecraft.artifacts.v1.SceneStreamResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(dev.recorderminecraft.artifacts.v1.SceneStreamResult prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code recorder_minecraft.artifacts.v1.SceneStreamResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:recorder_minecraft.artifacts.v1.SceneStreamResult)
      dev.recorderminecraft.artifacts.v1.SceneStreamResultOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dev.recorderminecraft.artifacts.v1.SceneExtraction.internal_static_recorder_minecraft_artifacts_v1_SceneStreamResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dev.recorderminecraft.artifacts.v1.SceneExtraction.internal_static_recorder_minecraft_artifacts_v1_SceneStreamResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dev.recorderminecraft.artifacts.v1.SceneStreamResult.class, dev.recorderminecraft.artifacts.v1.SceneStreamResult.Builder.class);
    }

    // Construct using dev.recorderminecraft.artifacts.v1.SceneStreamResult.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      path_ = "";
      frames_ = "";
      changes_ = "";
      blobsDirectory_ = "";
      frameCount_ = 0L;
      changeCount_ = 0L;
      blobCount_ = 0L;
      blobBytes_ = 0L;
      framesSha256_ = "";
      framesSizeBytes_ = 0L;
      changesSha256_ = "";
      changesSizeBytes_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return dev.recorderminecraft.artifacts.v1.SceneExtraction.internal_static_recorder_minecraft_artifacts_v1_SceneStreamResult_descriptor;
    }

    @java.lang.Override
    public dev.recorderminecraft.artifacts.v1.SceneStreamResult getDefaultInstanceForType() {
      return dev.recorderminecraft.artifacts.v1.SceneStreamResult.getDefaultInstance();
    }

    @java.lang.Override
    public dev.recorderminecraft.artifacts.v1.SceneStreamResult build() {
      dev.recorderminecraft.artifacts.v1.SceneStreamResult result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public dev.recorderminecraft.artifacts.v1.SceneStreamResult buildPartial() {
      dev.recorderminecraft.artifacts.v1.SceneStreamResult result = new dev.recorderminecraft.artifacts.v1.SceneStreamResult(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(dev.recorderminecraft.artifacts.v1.SceneStreamResult result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.path_ = path_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.frames_ = frames_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.changes_ = changes_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.blobsDirectory_ = blobsDirectory_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.frameCount_ = frameCount_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.changeCount_ = changeCount_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.blobCount_ = blobCount_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.blobBytes_ = blobBytes_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.framesSha256_ = framesSha256_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.framesSizeBytes_ = framesSizeBytes_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.changesSha256_ = changesSha256_;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.changesSizeBytes_ = changesSizeBytes_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof dev.recorderminecraft.artifacts.v1.SceneStreamResult) {
        return mergeFrom((dev.recorderminecraft.artifacts.v1.SceneStreamResult)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(dev.recorderminecraft.artifacts.v1.SceneStreamResult other) {
      if (other == dev.recorderminecraft.artifacts.v1.SceneStreamResult.getDefaultInstance()) return this;
      if (!other.getPath().isEmpty()) {
        path_ = other.path_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getFrames().isEmpty()) {
        frames_ = other.frames_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getChanges().isEmpty()) {
        changes_ = other.changes_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getBlobsDirectory().isEmpty()) {
        blobsDirectory_ = other.blobsDirectory_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.getFrameCount() != 0L) {
        setFrameCount(other.getFrameCount());
      }
      if (other.getChangeCount() != 0L) {
        setChangeCount(other.getChangeCount());
      }
      if (other.getBlobCount() != 0L) {
        setBlobCount(other.getBlobCount());
      }
      if (other.getBlobBytes() != 0L) {
        setBlobBytes(other.getBlobBytes());
      }
      if (!other.getFramesSha256().isEmpty()) {
        framesSha256_ = other.framesSha256_;
        bitField0_ |= 0x00000100;
        onChanged();
      }
      if (other.getFramesSizeBytes() != 0L) {
        setFramesSizeBytes(other.getFramesSizeBytes());
      }
      if (!other.getChangesSha256().isEmpty()) {
        changesSha256_ = other.changesSha256_;
        bitField0_ |= 0x00000400;
        onChanged();
      }
      if (other.getChangesSizeBytes() != 0L) {
        setChangesSizeBytes(other.getChangesSizeBytes());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              path_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              frames_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              changes_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              blobsDirectory_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 40: {
              frameCount_ = input.readUInt64();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              changeCount_ = input.readUInt64();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              blobCount_ = input.readUInt64();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 64: {
              blobBytes_ = input.readUInt64();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            case 74: {
              framesSha256_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            case 80: {
              framesSizeBytes_ = input.readUInt64();
              bitField0_ |= 0x00000200;
              break;
            } // case 80
            case 90: {
              changesSha256_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000400;
              break;
            } // case 90
            case 96: {
              changesSizeBytes_ = input.readUInt64();
              bitField0_ |= 0x00000800;
              break;
            } // case 96
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object path_ = "";
    /**
     * <code>string path = 1 [json_name = "path"];</code>
     * @return The path.
     */
    public java.lang.String getPath() {
      java.lang.Object ref = path_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        path_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string path = 1 [json_name = "path"];</code>
     * @return The bytes for path.
     */
    public com.google.protobuf.ByteString
        getPathBytes() {
      java.lang.Object ref = path_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        path_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string path = 1 [json_name = "path"];</code>
     * @param value The path to set.
     * @return This builder for chaining.
     */
    public Builder setPath(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      path_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string path = 1 [json_name = "path"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPath() {
      path_ = getDefaultInstance().getPath();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string path = 1 [json_name = "path"];</code>
     * @param value The bytes for path to set.
     * @return This builder for chaining.
     */
    public Builder setPathBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      path_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object frames_ = "";
    /**
     * <code>string frames = 2 [json_name = "frames"];</code>
     * @return The frames.
     */
    public java.lang.String getFrames() {
      java.lang.Object ref = frames_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        frames_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string frames = 2 [json_name = "frames"];</code>
     * @return The bytes for frames.
     */
    public com.google.protobuf.ByteString
        getFramesBytes() {
      java.lang.Object ref = frames_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        frames_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string frames = 2 [json_name = "frames"];</code>
     * @param value The frames to set.
     * @return This builder for chaining.
     */
    public Builder setFrames(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      frames_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string frames = 2 [json_name = "frames"];</code>
     * @return This builder for chaining.
     */
    public Builder clearFrames() {
      frames_ = getDefaultInstance().getFrames();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string frames = 2 [json_name = "frames"];</code>
     * @param value The bytes for frames to set.
     * @return This builder for chaining.
     */
    public Builder setFramesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      frames_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object changes_ = "";
    /**
     * <code>string changes = 3 [json_name = "changes"];</code>
     * @return The changes.
     */
    public java.lang.String getChanges() {
      java.lang.Object ref = changes_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        changes_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string changes = 3 [json_name = "changes"];</code>
     * @return The bytes for changes.
     */
    public com.google.protobuf.ByteString
        getChangesBytes() {
      java.lang.Object ref = changes_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        changes_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string changes = 3 [json_name = "changes"];</code>
     * @param value The changes to set.
     * @return This builder for chaining.
     */
    public Builder setChanges(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      changes_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string changes = 3 [json_name = "changes"];</code>
     * @return This builder for chaining.
     */
    public Builder clearChanges() {
      changes_ = getDefaultInstance().getChanges();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string changes = 3 [json_name = "changes"];</code>
     * @param value The bytes for changes to set.
     * @return This builder for chaining.
     */
    public Builder setChangesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      changes_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object blobsDirectory_ = "";
    /**
     * <code>string blobs_directory = 4 [json_name = "blobsDirectory"];</code>
     * @return The blobsDirectory.
     */
    public java.lang.String getBlobsDirectory() {
      java.lang.Object ref = blobsDirectory_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        blobsDirectory_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string blobs_directory = 4 [json_name = "blobsDirectory"];</code>
     * @return The bytes for blobsDirectory.
     */
    public com.google.protobuf.ByteString
        getBlobsDirectoryBytes() {
      java.lang.Object ref = blobsDirectory_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        blobsDirectory_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string blobs_directory = 4 [json_name = "blobsDirectory"];</code>
     * @param value The blobsDirectory to set.
     * @return This builder for chaining.
     */
    public Builder setBlobsDirectory(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      blobsDirectory_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string blobs_directory = 4 [json_name = "blobsDirectory"];</code>
     * @return This builder for chaining.
     */
    public Builder clearBlobsDirectory() {
      blobsDirectory_ = getDefaultInstance().getBlobsDirectory();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string blobs_directory = 4 [json_name = "blobsDirectory"];</code>
     * @param value The bytes for blobsDirectory to set.
     * @return This builder for chaining.
     */
    public Builder setBlobsDirectoryBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      blobsDirectory_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private long frameCount_ ;
    /**
     * <code>uint64 frame_count = 5 [json_name = "frameCount"];</code>
     * @return The frameCount.
     */
    @java.lang.Override
    public long getFrameCount() {
      return frameCount_;
    }
    /**
     * <code>uint64 frame_count = 5 [json_name = "frameCount"];</code>
     * @param value The frameCount to set.
     * @return This builder for chaining.
     */
    public Builder setFrameCount(long value) {

      frameCount_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 frame_count = 5 [json_name = "frameCount"];</code>
     * @return This builder for chaining.
     */
    public Builder clearFrameCount() {
      bitField0_ = (bitField0_ & ~0x00000010);
      frameCount_ = 0L;
      onChanged();
      return this;
    }

    private long changeCount_ ;
    /**
     * <code>uint64 change_count = 6 [json_name = "changeCount"];</code>
     * @return The changeCount.
     */
    @java.lang.Override
    public long getChangeCount() {
      return changeCount_;
    }
    /**
     * <code>uint64 change_count = 6 [json_name = "changeCount"];</code>
     * @param value The changeCount to set.
     * @return This builder for chaining.
     */
    public Builder setChangeCount(long value) {

      changeCount_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 change_count = 6 [json_name = "changeCount"];</code>
     * @return This builder for chaining.
     */
    public Builder clearChangeCount() {
      bitField0_ = (bitField0_ & ~0x00000020);
      changeCount_ = 0L;
      onChanged();
      return this;
    }

    private long blobCount_ ;
    /**
     * <code>uint64 blob_count = 7 [json_name = "blobCount"];</code>
     * @return The blobCount.
     */
    @java.lang.Override
    public long getBlobCount() {
      return blobCount_;
    }
    /**
     * <code>uint64 blob_count = 7 [json_name = "blobCount"];</code>
     * @param value The blobCount to set.
     * @return This builder for chaining.
     */
    public Builder setBlobCount(long value) {

      blobCount_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 blob_count = 7 [json_name = "blobCount"];</code>
     * @return This builder for chaining.
     */
    public Builder clearBlobCount() {
      bitField0_ = (bitField0_ & ~0x00000040);
      blobCount_ = 0L;
      onChanged();
      return this;
    }

    private long blobBytes_ ;
    /**
     * <code>uint64 blob_bytes = 8 [json_name = "blobBytes"];</code>
     * @return The blobBytes.
     */
    @java.lang.Override
    public long getBlobBytes() {
      return blobBytes_;
    }
    /**
     * <code>uint64 blob_bytes = 8 [json_name = "blobBytes"];</code>
     * @param value The blobBytes to set.
     * @return This builder for chaining.
     */
    public Builder setBlobBytes(long value) {

      blobBytes_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 blob_bytes = 8 [json_name = "blobBytes"];</code>
     * @return This builder for chaining.
     */
    public Builder clearBlobBytes() {
      bitField0_ = (bitField0_ & ~0x00000080);
      blobBytes_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object framesSha256_ = "";
    /**
     * <code>string frames_sha256 = 9 [json_name = "framesSha256"];</code>
     * @return The framesSha256.
     */
    public java.lang.String getFramesSha256() {
      java.lang.Object ref = framesSha256_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        framesSha256_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string frames_sha256 = 9 [json_name = "framesSha256"];</code>
     * @return The bytes for framesSha256.
     */
    public com.google.protobuf.ByteString
        getFramesSha256Bytes() {
      java.lang.Object ref = framesSha256_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        framesSha256_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string frames_sha256 = 9 [json_name = "framesSha256"];</code>
     * @param value The framesSha256 to set.
     * @return This builder for chaining.
     */
    public Builder setFramesSha256(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      framesSha256_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>string frames_sha256 = 9 [json_name = "framesSha256"];</code>
     * @return This builder for chaining.
     */
    public Builder clearFramesSha256() {
      framesSha256_ = getDefaultInstance().getFramesSha256();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <code>string frames_sha256 = 9 [json_name = "framesSha256"];</code>
     * @param value The bytes for framesSha256 to set.
     * @return This builder for chaining.
     */
    public Builder setFramesSha256Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      framesSha256_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    private long framesSizeBytes_ ;
    /**
     * <code>uint64 frames_size_bytes = 10 [json_name = "framesSizeBytes"];</code>
     * @return The framesSizeBytes.
     */
    @java.lang.Override
    public long getFramesSizeBytes() {
      return framesSizeBytes_;
    }
    /**
     * <code>uint64 frames_size_bytes = 10 [json_name = "framesSizeBytes"];</code>
     * @param value The framesSizeBytes to set.
     * @return This builder for chaining.
     */
    public Builder setFramesSizeBytes(long value) {

      framesSizeBytes_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 frames_size_bytes = 10 [json_name = "framesSizeBytes"];</code>
     * @return This builder for chaining.
     */
    public Builder clearFramesSizeBytes() {
      bitField0_ = (bitField0_ & ~0x00000200);
      framesSizeBytes_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object changesSha256_ = "";
    /**
     * <code>string changes_sha256 = 11 [json_name = "changesSha256"];</code>
     * @return The changesSha256.
     */
    public java.lang.String getChangesSha256() {
      java.lang.Object ref = changesSha256_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        changesSha256_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string changes_sha256 = 11 [json_name = "changesSha256"];</code>
     * @return The bytes for changesSha256.
     */
    public com.google.protobuf.ByteString
        getChangesSha256Bytes() {
      java.lang.Object ref = changesSha256_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        changesSha256_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string changes_sha256 = 11 [json_name = "changesSha256"];</code>
     * @param value The changesSha256 to set.
     * @return This builder for chaining.
     */
    public Builder setChangesSha256(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      changesSha256_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>string changes_sha256 = 11 [json_name = "changesSha256"];</code>
     * @return This builder for chaining.
     */
    public Builder clearChangesSha256() {
      changesSha256_ = getDefaultInstance().getChangesSha256();
      bitField0_ = (bitField0_ & ~0x00000400);
      onChanged();
      return this;
    }
    /**
     * <code>string changes_sha256 = 11 [json_name = "changesSha256"];</code>
     * @param value The bytes for changesSha256 to set.
     * @return This builder for chaining.
     */
    public Builder setChangesSha256Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      changesSha256_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }

    private long changesSizeBytes_ ;
    /**
     * <code>uint64 changes_size_bytes = 12 [json_name = "changesSizeBytes"];</code>
     * @return The changesSizeBytes.
     */
    @java.lang.Override
    public long getChangesSizeBytes() {
      return changesSizeBytes_;
    }
    /**
     * <code>uint64 changes_size_bytes = 12 [json_name = "changesSizeBytes"];</code>
     * @param value The changesSizeBytes to set.
     * @return This builder for chaining.
     */
    public Builder setChangesSizeBytes(long value) {

      changesSizeBytes_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 changes_size_bytes = 12 [json_name = "changesSizeBytes"];</code>
     * @return This builder for chaining.
     */
    public Builder clearChangesSizeBytes() {
      bitField0_ = (bitField0_ & ~0x00000800);
      changesSizeBytes_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:recorder_minecraft.artifacts.v1.SceneStreamResult)
  }

  // @@protoc_insertion_point(class_scope:recorder_minecraft.artifacts.v1.SceneStreamResult)
  private static final dev.recorderminecraft.artifacts.v1.SceneStreamResult DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new dev.recorderminecraft.artifacts.v1.SceneStreamResult();
  }

  public static dev.recorderminecraft.artifacts.v1.SceneStreamResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SceneStreamResult>
      PARSER = new com.google.protobuf.AbstractParser<SceneStreamResult>() {
    @java.lang.Override
    public SceneStreamResult parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SceneStreamResult> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SceneStreamResult> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public dev.recorderminecraft.artifacts.v1.SceneStreamResult getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

