// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: recorder-minecraft/artifacts/v1/scene.proto
// Protobuf Java Version: 4.33.2

package dev.recorderminecraft.artifacts.v1;

/**
 * Protobuf type {@code recorder_minecraft.artifacts.v1.SceneProvenance}
 */
@com.google.protobuf.Generated
public final class SceneProvenance extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:recorder_minecraft.artifacts.v1.SceneProvenance)
    SceneProvenanceOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "SceneProvenance");
  }
  // Use SceneProvenance.newBuilder() to construct.
  private SceneProvenance(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private SceneProvenance() {
    scope_ = "";
    metadataPolicy_ = "";
    resultType_ = "";
    jobId_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return dev.recorderminecraft.artifacts.v1.Scene.internal_static_recorder_minecraft_artifacts_v1_SceneProvenance_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
      int number) {
    switch (number) {
      case 5:
        return internalGetIgnoredPacketCounts();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return dev.recorderminecraft.artifacts.v1.Scene.internal_static_recorder_minecraft_artifacts_v1_SceneProvenance_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            dev.recorderminecraft.artifacts.v1.SceneProvenance.class, dev.recorderminecraft.artifacts.v1.SceneProvenance.Builder.class);
  }

  public static final int SCOPE_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object scope_ = "";
  /**
   * <code>string scope = 1 [json_name = "scope"];</code>
   * @return The scope.
   */
  @java.lang.Override
  public java.lang.String getScope() {
    java.lang.Object ref = scope_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      scope_ = s;
      return s;
    }
  }
  /**
   * <code>string scope = 1 [json_name = "scope"];</code>
   * @return The bytes for scope.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getScopeBytes() {
    java.lang.Object ref = scope_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      scope_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int METADATA_POLICY_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object metadataPolicy_ = "";
  /**
   * <code>string metadata_policy = 2 [json_name = "metadataPolicy"];</code>
   * @return The metadataPolicy.
   */
  @java.lang.Override
  public java.lang.String getMetadataPolicy() {
    java.lang.Object ref = metadataPolicy_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      metadataPolicy_ = s;
      return s;
    }
  }
  /**
   * <code>string metadata_policy = 2 [json_name = "metadataPolicy"];</code>
   * @return The bytes for metadataPolicy.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMetadataPolicyBytes() {
    java.lang.Object ref = metadataPolicy_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      metadataPolicy_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RESULT_TYPE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object resultType_ = "";
  /**
   * <code>string result_type = 3 [json_name = "resultType"];</code>
   * @return The resultType.
   */
  @java.lang.Override
  public java.lang.String getResultType() {
    java.lang.Object ref = resultType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      resultType_ = s;
      return s;
    }
  }
  /**
   * <code>string result_type = 3 [json_name = "resultType"];</code>
   * @return The bytes for resultType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getResultTypeBytes() {
    java.lang.Object ref = resultType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      resultType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int JOB_ID_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object jobId_ = "";
  /**
   * <code>string job_id = 4 [json_name = "jobId"];</code>
   * @return The jobId.
   */
  @java.lang.Override
  public java.lang.String getJobId() {
    java.lang.Object ref = jobId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      jobId_ = s;
      return s;
    }
  }
  /**
   * <code>string job_id = 4 [json_name = "jobId"];</code>
   * @return The bytes for jobId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getJobIdBytes() {
    java.lang.Object ref = jobId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      jobId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IGNORED_PACKET_COUNTS_FIELD_NUMBER = 5;
  private static final class IgnoredPacketCountsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.Long> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.Long>newDefaultInstance(
                dev.recorderminecraft.artifacts.v1.Scene.internal_static_recorder_minecraft_artifacts_v1_SceneProvenance_IgnoredPacketCountsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.UINT64,
                0L);
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.Long> ignoredPacketCounts_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.Long>
  internalGetIgnoredPacketCounts() {
    if (ignoredPacketCounts_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          IgnoredPacketCountsDefaultEntryHolder.defaultEntry);
    }
    return ignoredPacketCounts_;
  }
  public int getIgnoredPacketCountsCount() {
    return internalGetIgnoredPacketCounts().getMap().size();
  }
  /**
   * <code>map&lt;string, uint64&gt; ignored_packet_counts = 5 [json_name = "ignoredPacketCounts"];</code>
   */
  @java.lang.Override
  public boolean containsIgnoredPacketCounts(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetIgnoredPacketCounts().getMap().containsKey(key);
  }
  /**
   * Use {@link #getIgnoredPacketCountsMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.Long> getIgnoredPacketCounts() {
    return getIgnoredPacketCountsMap();
  }
  /**
   * <code>map&lt;string, uint64&gt; ignored_packet_counts = 5 [json_name = "ignoredPacketCounts"];</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, java.lang.Long> getIgnoredPacketCountsMap() {
    return internalGetIgnoredPacketCounts().getMap();
  }
  /**
   * <code>map&lt;string, uint64&gt; ignored_packet_counts = 5 [json_name = "ignoredPacketCounts"];</code>
   */
  @java.lang.Override
  public long getIgnoredPacketCountsOrDefault(
      java.lang.String key,
      long defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.Long> map =
        internalGetIgnoredPacketCounts().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, uint64&gt; ignored_packet_counts = 5 [json_name = "ignoredPacketCounts"];</code>
   */
  @java.lang.Override
  public long getIgnoredPacketCountsOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.Long> map =
        internalGetIgnoredPacketCounts().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(scope_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, scope_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(metadataPolicy_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, metadataPolicy_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(resultType_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, resultType_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(jobId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, jobId_);
    }
    com.google.protobuf.GeneratedMessage
      .serializeStringMapTo(
        output,
        internalGetIgnoredPacketCounts(),
        IgnoredPacketCountsDefaultEntryHolder.defaultEntry,
        5);
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(scope_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, scope_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(metadataPolicy_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, metadataPolicy_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(resultType_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, resultType_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(jobId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, jobId_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.Long> entry
         : internalGetIgnoredPacketCounts().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.Long>
      ignoredPacketCounts__ = IgnoredPacketCountsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, ignoredPacketCounts__);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof dev.recorderminecraft.artifacts.v1.SceneProvenance)) {
      return super.equals(obj);
    }
    dev.recorderminecraft.artifacts.v1.SceneProvenance other = (dev.recorderminecraft.artifacts.v1.SceneProvenance) obj;

    if (!getScope()
        .equals(other.getScope())) return false;
    if (!getMetadataPolicy()
        .equals(other.getMetadataPolicy())) return false;
    if (!getResultType()
        .equals(other.getResultType())) return false;
    if (!getJobId()
        .equals(other.getJobId())) return false;
    if (!internalGetIgnoredPacketCounts().equals(
        other.internalGetIgnoredPacketCounts())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SCOPE_FIELD_NUMBER;
    hash = (53 * hash) + getScope().hashCode();
    hash = (37 * hash) + METADATA_POLICY_FIELD_NUMBER;
    hash = (53 * hash) + getMetadataPolicy().hashCode();
    hash = (37 * hash) + RESULT_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getResultType().hashCode();
    hash = (37 * hash) + JOB_ID_FIELD_NUMBER;
    hash = (53 * hash) + getJobId().hashCode();
    if (!internalGetIgnoredPacketCounts().getMap().isEmpty()) {
      hash = (37 * hash) + IGNORED_PACKET_COUNTS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetIgnoredPacketCounts().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static dev.recorderminecraft.artifacts.v1.SceneProvenance parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.recorderminecraft.artifacts.v1.SceneProvenance parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.recorderminecraft.artifacts.v1.SceneProvenance parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.recorderminecraft.artifacts.v1.SceneProvenance parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.recorderminecraft.artifacts.v1.SceneProvenance parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.recorderminecraft.artifacts.v1.SceneProvenance parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.recorderminecraft.artifacts.v1.SceneProvenance parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static dev.recorderminecraft.artifacts.v1.SceneProvenance parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static dev.recorderminecraft.artifacts.v1.SceneProvenance parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static dev.recorderminecraft.artifacts.v1.SceneProvenance parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static dev.recorderminecraft.artifacts.v1.SceneProvenance parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static dev.recorderminecraft.artifacts.v1.SceneProvenance parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(dev.recorderminecraft.artifacts.v1.SceneProvenance prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code recorder_minecraft.artifacts.v1.SceneProvenance}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:recorder_minecraft.artifacts.v1.SceneProvenance)
      dev.recorderminecraft.artifacts.v1.SceneProvenanceOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dev.recorderminecraft.artifacts.v1.Scene.internal_static_recorder_minecraft_artifacts_v1_SceneProvenance_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 5:
          return internalGetIgnoredPacketCounts();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
        int number) {
      switch (number) {
        case 5:
          return internalGetMutableIgnoredPacketCounts();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dev.recorderminecraft.artifacts.v1.Scene.internal_static_recorder_minecraft_artifacts_v1_SceneProvenance_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dev.recorderminecraft.artifacts.v1.SceneProvenance.class, dev.recorderminecraft.artifacts.v1.SceneProvenance.Builder.class);
    }

    // Construct using dev.recorderminecraft.artifacts.v1.SceneProvenance.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      scope_ = "";
      metadataPolicy_ = "";
      resultType_ = "";
      jobId_ = "";
      internalGetMutableIgnoredPacketCounts().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return dev.recorderminecraft.artifacts.v1.Scene.internal_static_recorder_minecraft_artifacts_v1_SceneProvenance_descriptor;
    }

    @java.lang.Override
    public dev.recorderminecraft.artifacts.v1.SceneProvenance getDefaultInstanceForType() {
      return dev.recorderminecraft.artifacts.v1.SceneProvenance.getDefaultInstance();
    }

    @java.lang.Override
    public dev.recorderminecraft.artifacts.v1.SceneProvenance build() {
      dev.recorderminecraft.artifacts.v1.SceneProvenance result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public dev.recorderminecraft.artifacts.v1.SceneProvenance buildPartial() {
      dev.recorderminecraft.artifacts.v1.SceneProvenance result = new dev.recorderminecraft.artifacts.v1.SceneProvenance(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(dev.recorderminecraft.artifacts.v1.SceneProvenance result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.scope_ = scope_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.metadataPolicy_ = metadataPolicy_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.resultType_ = resultType_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.jobId_ = jobId_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.ignoredPacketCounts_ = internalGetIgnoredPacketCounts();
        result.ignoredPacketCounts_.makeImmutable();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof dev.recorderminecraft.artifacts.v1.SceneProvenance) {
        return mergeFrom((dev.recorderminecraft.artifacts.v1.SceneProvenance)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(dev.recorderminecraft.artifacts.v1.SceneProvenance other) {
      if (other == dev.recorderminecraft.artifacts.v1.SceneProvenance.getDefaultInstance()) return this;
      if (!other.getScope().isEmpty()) {
        scope_ = other.scope_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getMetadataPolicy().isEmpty()) {
        metadataPolicy_ = other.metadataPolicy_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getResultType().isEmpty()) {
        resultType_ = other.resultType_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getJobId().isEmpty()) {
        jobId_ = other.jobId_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      internalGetMutableIgnoredPacketCounts().mergeFrom(
          other.internalGetIgnoredPacketCounts());
      bitField0_ |= 0x00000010;
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              scope_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              metadataPolicy_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              resultType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              jobId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              com.google.protobuf.MapEntry<java.lang.String, java.lang.Long>
              ignoredPacketCounts__ = input.readMessage(
                  IgnoredPacketCountsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableIgnoredPacketCounts().getMutableMap().put(
                  ignoredPacketCounts__.getKey(), ignoredPacketCounts__.getValue());
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object scope_ = "";
    /**
     * <code>string scope = 1 [json_name = "scope"];</code>
     * @return The scope.
     */
    public java.lang.String getScope() {
      java.lang.Object ref = scope_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        scope_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string scope = 1 [json_name = "scope"];</code>
     * @return The bytes for scope.
     */
    public com.google.protobuf.ByteString
        getScopeBytes() {
      java.lang.Object ref = scope_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        scope_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string scope = 1 [json_name = "scope"];</code>
     * @param value The scope to set.
     * @return This builder for chaining.
     */
    public Builder setScope(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      scope_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string scope = 1 [json_name = "scope"];</code>
     * @return This builder for chaining.
     */
    public Builder clearScope() {
      scope_ = getDefaultInstance().getScope();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string scope = 1 [json_name = "scope"];</code>
     * @param value The bytes for scope to set.
     * @return This builder for chaining.
     */
    public Builder setScopeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      scope_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object metadataPolicy_ = "";
    /**
     * <code>string metadata_policy = 2 [json_name = "metadataPolicy"];</code>
     * @return The metadataPolicy.
     */
    public java.lang.String getMetadataPolicy() {
      java.lang.Object ref = metadataPolicy_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        metadataPolicy_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string metadata_policy = 2 [json_name = "metadataPolicy"];</code>
     * @return The bytes for metadataPolicy.
     */
    public com.google.protobuf.ByteString
        getMetadataPolicyBytes() {
      java.lang.Object ref = metadataPolicy_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        metadataPolicy_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string metadata_policy = 2 [json_name = "metadataPolicy"];</code>
     * @param value The metadataPolicy to set.
     * @return This builder for chaining.
     */
    public Builder setMetadataPolicy(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      metadataPolicy_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string metadata_policy = 2 [json_name = "metadataPolicy"];</code>
     * @return This builder for chaining.
     */
    public Builder clearMetadataPolicy() {
      metadataPolicy_ = getDefaultInstance().getMetadataPolicy();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string metadata_policy = 2 [json_name = "metadataPolicy"];</code>
     * @param value The bytes for metadataPolicy to set.
     * @return This builder for chaining.
     */
    public Builder setMetadataPolicyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      metadataPolicy_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object resultType_ = "";
    /**
     * <code>string result_type = 3 [json_name = "resultType"];</code>
     * @return The resultType.
     */
    public java.lang.String getResultType() {
      java.lang.Object ref = resultType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        resultType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string result_type = 3 [json_name = "resultType"];</code>
     * @return The bytes for resultType.
     */
    public com.google.protobuf.ByteString
        getResultTypeBytes() {
      java.lang.Object ref = resultType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resultType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string result_type = 3 [json_name = "resultType"];</code>
     * @param value The resultType to set.
     * @return This builder for chaining.
     */
    public Builder setResultType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      resultType_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string result_type = 3 [json_name = "resultType"];</code>
     * @return This builder for chaining.
     */
    public Builder clearResultType() {
      resultType_ = getDefaultInstance().getResultType();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string result_type = 3 [json_name = "resultType"];</code>
     * @param value The bytes for resultType to set.
     * @return This builder for chaining.
     */
    public Builder setResultTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      resultType_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object jobId_ = "";
    /**
     * <code>string job_id = 4 [json_name = "jobId"];</code>
     * @return The jobId.
     */
    public java.lang.String getJobId() {
      java.lang.Object ref = jobId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        jobId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string job_id = 4 [json_name = "jobId"];</code>
     * @return The bytes for jobId.
     */
    public com.google.protobuf.ByteString
        getJobIdBytes() {
      java.lang.Object ref = jobId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jobId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string job_id = 4 [json_name = "jobId"];</code>
     * @param value The jobId to set.
     * @return This builder for chaining.
     */
    public Builder setJobId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      jobId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string job_id = 4 [json_name = "jobId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearJobId() {
      jobId_ = getDefaultInstance().getJobId();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string job_id = 4 [json_name = "jobId"];</code>
     * @param value The bytes for jobId to set.
     * @return This builder for chaining.
     */
    public Builder setJobIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      jobId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.Long> ignoredPacketCounts_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.Long>
        internalGetIgnoredPacketCounts() {
      if (ignoredPacketCounts_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            IgnoredPacketCountsDefaultEntryHolder.defaultEntry);
      }
      return ignoredPacketCounts_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.Long>
        internalGetMutableIgnoredPacketCounts() {
      if (ignoredPacketCounts_ == null) {
        ignoredPacketCounts_ = com.google.protobuf.MapField.newMapField(
            IgnoredPacketCountsDefaultEntryHolder.defaultEntry);
      }
      if (!ignoredPacketCounts_.isMutable()) {
        ignoredPacketCounts_ = ignoredPacketCounts_.copy();
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return ignoredPacketCounts_;
    }
    public int getIgnoredPacketCountsCount() {
      return internalGetIgnoredPacketCounts().getMap().size();
    }
    /**
     * <code>map&lt;string, uint64&gt; ignored_packet_counts = 5 [json_name = "ignoredPacketCounts"];</code>
     */
    @java.lang.Override
    public boolean containsIgnoredPacketCounts(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetIgnoredPacketCounts().getMap().containsKey(key);
    }
    /**
     * Use {@link #getIgnoredPacketCountsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Long> getIgnoredPacketCounts() {
      return getIgnoredPacketCountsMap();
    }
    /**
     * <code>map&lt;string, uint64&gt; ignored_packet_counts = 5 [json_name = "ignoredPacketCounts"];</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.Long> getIgnoredPacketCountsMap() {
      return internalGetIgnoredPacketCounts().getMap();
    }
    /**
     * <code>map&lt;string, uint64&gt; ignored_packet_counts = 5 [json_name = "ignoredPacketCounts"];</code>
     */
    @java.lang.Override
    public long getIgnoredPacketCountsOrDefault(
        java.lang.String key,
        long defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.Long> map =
          internalGetIgnoredPacketCounts().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, uint64&gt; ignored_packet_counts = 5 [json_name = "ignoredPacketCounts"];</code>
     */
    @java.lang.Override
    public long getIgnoredPacketCountsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.Long> map =
          internalGetIgnoredPacketCounts().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearIgnoredPacketCounts() {
      bitField0_ = (bitField0_ & ~0x00000010);
      internalGetMutableIgnoredPacketCounts().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, uint64&gt; ignored_packet_counts = 5 [json_name = "ignoredPacketCounts"];</code>
     */
    public Builder removeIgnoredPacketCounts(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableIgnoredPacketCounts().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Long>
        getMutableIgnoredPacketCounts() {
      bitField0_ |= 0x00000010;
      return internalGetMutableIgnoredPacketCounts().getMutableMap();
    }
    /**
     * <code>map&lt;string, uint64&gt; ignored_packet_counts = 5 [json_name = "ignoredPacketCounts"];</code>
     */
    public Builder putIgnoredPacketCounts(
        java.lang.String key,
        long value) {
      if (key == null) { throw new NullPointerException("map key"); }

      internalGetMutableIgnoredPacketCounts().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000010;
      return this;
    }
    /**
     * <code>map&lt;string, uint64&gt; ignored_packet_counts = 5 [json_name = "ignoredPacketCounts"];</code>
     */
    public Builder putAllIgnoredPacketCounts(
        java.util.Map<java.lang.String, java.lang.Long> values) {
      internalGetMutableIgnoredPacketCounts().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000010;
      return this;
    }

    // @@protoc_insertion_point(builder_scope:recorder_minecraft.artifacts.v1.SceneProvenance)
  }

  // @@protoc_insertion_point(class_scope:recorder_minecraft.artifacts.v1.SceneProvenance)
  private static final dev.recorderminecraft.artifacts.v1.SceneProvenance DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new dev.recorderminecraft.artifacts.v1.SceneProvenance();
  }

  public static dev.recorderminecraft.artifacts.v1.SceneProvenance getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SceneProvenance>
      PARSER = new com.google.protobuf.AbstractParser<SceneProvenance>() {
    @java.lang.Override
    public SceneProvenance parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SceneProvenance> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SceneProvenance> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public dev.recorderminecraft.artifacts.v1.SceneProvenance getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

