// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: recorder-minecraft/artifacts/v1/scene.proto
// Protobuf Java Version: 4.33.2

package dev.recorderminecraft.artifacts.v1;

@com.google.protobuf.Generated
public interface SceneProvenanceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:recorder_minecraft.artifacts.v1.SceneProvenance)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string scope = 1 [json_name = "scope"];</code>
   * @return The scope.
   */
  java.lang.String getScope();
  /**
   * <code>string scope = 1 [json_name = "scope"];</code>
   * @return The bytes for scope.
   */
  com.google.protobuf.ByteString
      getScopeBytes();

  /**
   * <code>string metadata_policy = 2 [json_name = "metadataPolicy"];</code>
   * @return The metadataPolicy.
   */
  java.lang.String getMetadataPolicy();
  /**
   * <code>string metadata_policy = 2 [json_name = "metadataPolicy"];</code>
   * @return The bytes for metadataPolicy.
   */
  com.google.protobuf.ByteString
      getMetadataPolicyBytes();

  /**
   * <code>string result_type = 3 [json_name = "resultType"];</code>
   * @return The resultType.
   */
  java.lang.String getResultType();
  /**
   * <code>string result_type = 3 [json_name = "resultType"];</code>
   * @return The bytes for resultType.
   */
  com.google.protobuf.ByteString
      getResultTypeBytes();

  /**
   * <code>string job_id = 4 [json_name = "jobId"];</code>
   * @return The jobId.
   */
  java.lang.String getJobId();
  /**
   * <code>string job_id = 4 [json_name = "jobId"];</code>
   * @return The bytes for jobId.
   */
  com.google.protobuf.ByteString
      getJobIdBytes();

  /**
   * <code>map&lt;string, uint64&gt; ignored_packet_counts = 5 [json_name = "ignoredPacketCounts"];</code>
   */
  int getIgnoredPacketCountsCount();
  /**
   * <code>map&lt;string, uint64&gt; ignored_packet_counts = 5 [json_name = "ignoredPacketCounts"];</code>
   */
  boolean containsIgnoredPacketCounts(
      java.lang.String key);
  /**
   * Use {@link #getIgnoredPacketCountsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.Long>
  getIgnoredPacketCounts();
  /**
   * <code>map&lt;string, uint64&gt; ignored_packet_counts = 5 [json_name = "ignoredPacketCounts"];</code>
   */
  java.util.Map<java.lang.String, java.lang.Long>
  getIgnoredPacketCountsMap();
  /**
   * <code>map&lt;string, uint64&gt; ignored_packet_counts = 5 [json_name = "ignoredPacketCounts"];</code>
   */
  long getIgnoredPacketCountsOrDefault(
      java.lang.String key,
      long defaultValue);
  /**
   * <code>map&lt;string, uint64&gt; ignored_packet_counts = 5 [json_name = "ignoredPacketCounts"];</code>
   */
  long getIgnoredPacketCountsOrThrow(
      java.lang.String key);
}
